
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Category` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Category
 * 
 */
export type CategoryModel = runtime.Types.Result.DefaultSelection<Prisma.$CategoryPayload>

export type AggregateCategory = {
  _count: CategoryCountAggregateOutputType | null
  _avg: CategoryAvgAggregateOutputType | null
  _sum: CategorySumAggregateOutputType | null
  _min: CategoryMinAggregateOutputType | null
  _max: CategoryMaxAggregateOutputType | null
}

export type CategoryAvgAggregateOutputType = {
  categoryId: number | null
  sequence: runtime.Decimal | null
  userId: number | null
}

export type CategorySumAggregateOutputType = {
  categoryId: number | null
  sequence: runtime.Decimal | null
  userId: number | null
}

export type CategoryMinAggregateOutputType = {
  categoryId: number | null
  categoryName: string | null
  logoPath: string | null
  isExpense: boolean | null
  isIncome: boolean | null
  isActive: boolean | null
  isDeleted: boolean | null
  description: string | null
  sequence: runtime.Decimal | null
  userId: number | null
  created: Date | null
  modified: Date | null
}

export type CategoryMaxAggregateOutputType = {
  categoryId: number | null
  categoryName: string | null
  logoPath: string | null
  isExpense: boolean | null
  isIncome: boolean | null
  isActive: boolean | null
  isDeleted: boolean | null
  description: string | null
  sequence: runtime.Decimal | null
  userId: number | null
  created: Date | null
  modified: Date | null
}

export type CategoryCountAggregateOutputType = {
  categoryId: number
  categoryName: number
  logoPath: number
  isExpense: number
  isIncome: number
  isActive: number
  isDeleted: number
  description: number
  sequence: number
  userId: number
  created: number
  modified: number
  _all: number
}


export type CategoryAvgAggregateInputType = {
  categoryId?: true
  sequence?: true
  userId?: true
}

export type CategorySumAggregateInputType = {
  categoryId?: true
  sequence?: true
  userId?: true
}

export type CategoryMinAggregateInputType = {
  categoryId?: true
  categoryName?: true
  logoPath?: true
  isExpense?: true
  isIncome?: true
  isActive?: true
  isDeleted?: true
  description?: true
  sequence?: true
  userId?: true
  created?: true
  modified?: true
}

export type CategoryMaxAggregateInputType = {
  categoryId?: true
  categoryName?: true
  logoPath?: true
  isExpense?: true
  isIncome?: true
  isActive?: true
  isDeleted?: true
  description?: true
  sequence?: true
  userId?: true
  created?: true
  modified?: true
}

export type CategoryCountAggregateInputType = {
  categoryId?: true
  categoryName?: true
  logoPath?: true
  isExpense?: true
  isIncome?: true
  isActive?: true
  isDeleted?: true
  description?: true
  sequence?: true
  userId?: true
  created?: true
  modified?: true
  _all?: true
}

export type CategoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Category to aggregate.
   */
  where?: Prisma.CategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Categories to fetch.
   */
  orderBy?: Prisma.CategoryOrderByWithRelationInput | Prisma.CategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Categories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Categories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Categories
  **/
  _count?: true | CategoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CategoryAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CategorySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CategoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CategoryMaxAggregateInputType
}

export type GetCategoryAggregateType<T extends CategoryAggregateArgs> = {
      [P in keyof T & keyof AggregateCategory]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCategory[P]>
    : Prisma.GetScalarType<T[P], AggregateCategory[P]>
}




export type CategoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CategoryWhereInput
  orderBy?: Prisma.CategoryOrderByWithAggregationInput | Prisma.CategoryOrderByWithAggregationInput[]
  by: Prisma.CategoryScalarFieldEnum[] | Prisma.CategoryScalarFieldEnum
  having?: Prisma.CategoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CategoryCountAggregateInputType | true
  _avg?: CategoryAvgAggregateInputType
  _sum?: CategorySumAggregateInputType
  _min?: CategoryMinAggregateInputType
  _max?: CategoryMaxAggregateInputType
}

export type CategoryGroupByOutputType = {
  categoryId: number
  categoryName: string
  logoPath: string | null
  isExpense: boolean
  isIncome: boolean
  isActive: boolean
  isDeleted: boolean
  description: string | null
  sequence: runtime.Decimal | null
  userId: number
  created: Date
  modified: Date
  _count: CategoryCountAggregateOutputType | null
  _avg: CategoryAvgAggregateOutputType | null
  _sum: CategorySumAggregateOutputType | null
  _min: CategoryMinAggregateOutputType | null
  _max: CategoryMaxAggregateOutputType | null
}

type GetCategoryGroupByPayload<T extends CategoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CategoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CategoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CategoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CategoryGroupByOutputType[P]>
      }
    >
  >



export type CategoryWhereInput = {
  AND?: Prisma.CategoryWhereInput | Prisma.CategoryWhereInput[]
  OR?: Prisma.CategoryWhereInput[]
  NOT?: Prisma.CategoryWhereInput | Prisma.CategoryWhereInput[]
  categoryId?: Prisma.IntFilter<"Category"> | number
  categoryName?: Prisma.StringFilter<"Category"> | string
  logoPath?: Prisma.StringNullableFilter<"Category"> | string | null
  isExpense?: Prisma.BoolFilter<"Category"> | boolean
  isIncome?: Prisma.BoolFilter<"Category"> | boolean
  isActive?: Prisma.BoolFilter<"Category"> | boolean
  isDeleted?: Prisma.BoolFilter<"Category"> | boolean
  description?: Prisma.StringNullableFilter<"Category"> | string | null
  sequence?: Prisma.DecimalNullableFilter<"Category"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  userId?: Prisma.IntFilter<"Category"> | number
  created?: Prisma.DateTimeFilter<"Category"> | Date | string
  modified?: Prisma.DateTimeFilter<"Category"> | Date | string
  subCategories?: Prisma.SubCategoryListRelationFilter
  expenses?: Prisma.ExpenseListRelationFilter
  incomes?: Prisma.IncomeListRelationFilter
  budgets?: Prisma.BudgetListRelationFilter
}

export type CategoryOrderByWithRelationInput = {
  categoryId?: Prisma.SortOrder
  categoryName?: Prisma.SortOrder
  logoPath?: Prisma.SortOrderInput | Prisma.SortOrder
  isExpense?: Prisma.SortOrder
  isIncome?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  sequence?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrder
  created?: Prisma.SortOrder
  modified?: Prisma.SortOrder
  subCategories?: Prisma.SubCategoryOrderByRelationAggregateInput
  expenses?: Prisma.ExpenseOrderByRelationAggregateInput
  incomes?: Prisma.IncomeOrderByRelationAggregateInput
  budgets?: Prisma.BudgetOrderByRelationAggregateInput
}

export type CategoryWhereUniqueInput = Prisma.AtLeast<{
  categoryId?: number
  AND?: Prisma.CategoryWhereInput | Prisma.CategoryWhereInput[]
  OR?: Prisma.CategoryWhereInput[]
  NOT?: Prisma.CategoryWhereInput | Prisma.CategoryWhereInput[]
  categoryName?: Prisma.StringFilter<"Category"> | string
  logoPath?: Prisma.StringNullableFilter<"Category"> | string | null
  isExpense?: Prisma.BoolFilter<"Category"> | boolean
  isIncome?: Prisma.BoolFilter<"Category"> | boolean
  isActive?: Prisma.BoolFilter<"Category"> | boolean
  isDeleted?: Prisma.BoolFilter<"Category"> | boolean
  description?: Prisma.StringNullableFilter<"Category"> | string | null
  sequence?: Prisma.DecimalNullableFilter<"Category"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  userId?: Prisma.IntFilter<"Category"> | number
  created?: Prisma.DateTimeFilter<"Category"> | Date | string
  modified?: Prisma.DateTimeFilter<"Category"> | Date | string
  subCategories?: Prisma.SubCategoryListRelationFilter
  expenses?: Prisma.ExpenseListRelationFilter
  incomes?: Prisma.IncomeListRelationFilter
  budgets?: Prisma.BudgetListRelationFilter
}, "categoryId">

export type CategoryOrderByWithAggregationInput = {
  categoryId?: Prisma.SortOrder
  categoryName?: Prisma.SortOrder
  logoPath?: Prisma.SortOrderInput | Prisma.SortOrder
  isExpense?: Prisma.SortOrder
  isIncome?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  sequence?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrder
  created?: Prisma.SortOrder
  modified?: Prisma.SortOrder
  _count?: Prisma.CategoryCountOrderByAggregateInput
  _avg?: Prisma.CategoryAvgOrderByAggregateInput
  _max?: Prisma.CategoryMaxOrderByAggregateInput
  _min?: Prisma.CategoryMinOrderByAggregateInput
  _sum?: Prisma.CategorySumOrderByAggregateInput
}

export type CategoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.CategoryScalarWhereWithAggregatesInput | Prisma.CategoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.CategoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CategoryScalarWhereWithAggregatesInput | Prisma.CategoryScalarWhereWithAggregatesInput[]
  categoryId?: Prisma.IntWithAggregatesFilter<"Category"> | number
  categoryName?: Prisma.StringWithAggregatesFilter<"Category"> | string
  logoPath?: Prisma.StringNullableWithAggregatesFilter<"Category"> | string | null
  isExpense?: Prisma.BoolWithAggregatesFilter<"Category"> | boolean
  isIncome?: Prisma.BoolWithAggregatesFilter<"Category"> | boolean
  isActive?: Prisma.BoolWithAggregatesFilter<"Category"> | boolean
  isDeleted?: Prisma.BoolWithAggregatesFilter<"Category"> | boolean
  description?: Prisma.StringNullableWithAggregatesFilter<"Category"> | string | null
  sequence?: Prisma.DecimalNullableWithAggregatesFilter<"Category"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  userId?: Prisma.IntWithAggregatesFilter<"Category"> | number
  created?: Prisma.DateTimeWithAggregatesFilter<"Category"> | Date | string
  modified?: Prisma.DateTimeWithAggregatesFilter<"Category"> | Date | string
}

export type CategoryCreateInput = {
  categoryName: string
  logoPath?: string | null
  isExpense: boolean
  isIncome: boolean
  isActive?: boolean
  isDeleted?: boolean
  description?: string | null
  sequence?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  userId: number
  created?: Date | string
  modified?: Date | string
  subCategories?: Prisma.SubCategoryCreateNestedManyWithoutCategoryInput
  expenses?: Prisma.ExpenseCreateNestedManyWithoutCategoryInput
  incomes?: Prisma.IncomeCreateNestedManyWithoutCategoryInput
  budgets?: Prisma.BudgetCreateNestedManyWithoutCategoryInput
}

export type CategoryUncheckedCreateInput = {
  categoryId?: number
  categoryName: string
  logoPath?: string | null
  isExpense: boolean
  isIncome: boolean
  isActive?: boolean
  isDeleted?: boolean
  description?: string | null
  sequence?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  userId: number
  created?: Date | string
  modified?: Date | string
  subCategories?: Prisma.SubCategoryUncheckedCreateNestedManyWithoutCategoryInput
  expenses?: Prisma.ExpenseUncheckedCreateNestedManyWithoutCategoryInput
  incomes?: Prisma.IncomeUncheckedCreateNestedManyWithoutCategoryInput
  budgets?: Prisma.BudgetUncheckedCreateNestedManyWithoutCategoryInput
}

export type CategoryUpdateInput = {
  categoryName?: Prisma.StringFieldUpdateOperationsInput | string
  logoPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isExpense?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isIncome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sequence?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subCategories?: Prisma.SubCategoryUpdateManyWithoutCategoryNestedInput
  expenses?: Prisma.ExpenseUpdateManyWithoutCategoryNestedInput
  incomes?: Prisma.IncomeUpdateManyWithoutCategoryNestedInput
  budgets?: Prisma.BudgetUpdateManyWithoutCategoryNestedInput
}

export type CategoryUncheckedUpdateInput = {
  categoryId?: Prisma.IntFieldUpdateOperationsInput | number
  categoryName?: Prisma.StringFieldUpdateOperationsInput | string
  logoPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isExpense?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isIncome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sequence?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subCategories?: Prisma.SubCategoryUncheckedUpdateManyWithoutCategoryNestedInput
  expenses?: Prisma.ExpenseUncheckedUpdateManyWithoutCategoryNestedInput
  incomes?: Prisma.IncomeUncheckedUpdateManyWithoutCategoryNestedInput
  budgets?: Prisma.BudgetUncheckedUpdateManyWithoutCategoryNestedInput
}

export type CategoryCreateManyInput = {
  categoryId?: number
  categoryName: string
  logoPath?: string | null
  isExpense: boolean
  isIncome: boolean
  isActive?: boolean
  isDeleted?: boolean
  description?: string | null
  sequence?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  userId: number
  created?: Date | string
  modified?: Date | string
}

export type CategoryUpdateManyMutationInput = {
  categoryName?: Prisma.StringFieldUpdateOperationsInput | string
  logoPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isExpense?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isIncome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sequence?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CategoryUncheckedUpdateManyInput = {
  categoryId?: Prisma.IntFieldUpdateOperationsInput | number
  categoryName?: Prisma.StringFieldUpdateOperationsInput | string
  logoPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isExpense?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isIncome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sequence?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CategoryCountOrderByAggregateInput = {
  categoryId?: Prisma.SortOrder
  categoryName?: Prisma.SortOrder
  logoPath?: Prisma.SortOrder
  isExpense?: Prisma.SortOrder
  isIncome?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  description?: Prisma.SortOrder
  sequence?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  created?: Prisma.SortOrder
  modified?: Prisma.SortOrder
}

export type CategoryAvgOrderByAggregateInput = {
  categoryId?: Prisma.SortOrder
  sequence?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type CategoryMaxOrderByAggregateInput = {
  categoryId?: Prisma.SortOrder
  categoryName?: Prisma.SortOrder
  logoPath?: Prisma.SortOrder
  isExpense?: Prisma.SortOrder
  isIncome?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  description?: Prisma.SortOrder
  sequence?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  created?: Prisma.SortOrder
  modified?: Prisma.SortOrder
}

export type CategoryMinOrderByAggregateInput = {
  categoryId?: Prisma.SortOrder
  categoryName?: Prisma.SortOrder
  logoPath?: Prisma.SortOrder
  isExpense?: Prisma.SortOrder
  isIncome?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  description?: Prisma.SortOrder
  sequence?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  created?: Prisma.SortOrder
  modified?: Prisma.SortOrder
}

export type CategorySumOrderByAggregateInput = {
  categoryId?: Prisma.SortOrder
  sequence?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type CategoryScalarRelationFilter = {
  is?: Prisma.CategoryWhereInput
  isNot?: Prisma.CategoryWhereInput
}

export type CategoryNullableScalarRelationFilter = {
  is?: Prisma.CategoryWhereInput | null
  isNot?: Prisma.CategoryWhereInput | null
}

export type NullableDecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type CategoryCreateNestedOneWithoutSubCategoriesInput = {
  create?: Prisma.XOR<Prisma.CategoryCreateWithoutSubCategoriesInput, Prisma.CategoryUncheckedCreateWithoutSubCategoriesInput>
  connectOrCreate?: Prisma.CategoryCreateOrConnectWithoutSubCategoriesInput
  connect?: Prisma.CategoryWhereUniqueInput
}

export type CategoryUpdateOneRequiredWithoutSubCategoriesNestedInput = {
  create?: Prisma.XOR<Prisma.CategoryCreateWithoutSubCategoriesInput, Prisma.CategoryUncheckedCreateWithoutSubCategoriesInput>
  connectOrCreate?: Prisma.CategoryCreateOrConnectWithoutSubCategoriesInput
  upsert?: Prisma.CategoryUpsertWithoutSubCategoriesInput
  connect?: Prisma.CategoryWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CategoryUpdateToOneWithWhereWithoutSubCategoriesInput, Prisma.CategoryUpdateWithoutSubCategoriesInput>, Prisma.CategoryUncheckedUpdateWithoutSubCategoriesInput>
}

export type CategoryCreateNestedOneWithoutExpensesInput = {
  create?: Prisma.XOR<Prisma.CategoryCreateWithoutExpensesInput, Prisma.CategoryUncheckedCreateWithoutExpensesInput>
  connectOrCreate?: Prisma.CategoryCreateOrConnectWithoutExpensesInput
  connect?: Prisma.CategoryWhereUniqueInput
}

export type CategoryUpdateOneWithoutExpensesNestedInput = {
  create?: Prisma.XOR<Prisma.CategoryCreateWithoutExpensesInput, Prisma.CategoryUncheckedCreateWithoutExpensesInput>
  connectOrCreate?: Prisma.CategoryCreateOrConnectWithoutExpensesInput
  upsert?: Prisma.CategoryUpsertWithoutExpensesInput
  disconnect?: Prisma.CategoryWhereInput | boolean
  delete?: Prisma.CategoryWhereInput | boolean
  connect?: Prisma.CategoryWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CategoryUpdateToOneWithWhereWithoutExpensesInput, Prisma.CategoryUpdateWithoutExpensesInput>, Prisma.CategoryUncheckedUpdateWithoutExpensesInput>
}

export type CategoryCreateNestedOneWithoutIncomesInput = {
  create?: Prisma.XOR<Prisma.CategoryCreateWithoutIncomesInput, Prisma.CategoryUncheckedCreateWithoutIncomesInput>
  connectOrCreate?: Prisma.CategoryCreateOrConnectWithoutIncomesInput
  connect?: Prisma.CategoryWhereUniqueInput
}

export type CategoryUpdateOneWithoutIncomesNestedInput = {
  create?: Prisma.XOR<Prisma.CategoryCreateWithoutIncomesInput, Prisma.CategoryUncheckedCreateWithoutIncomesInput>
  connectOrCreate?: Prisma.CategoryCreateOrConnectWithoutIncomesInput
  upsert?: Prisma.CategoryUpsertWithoutIncomesInput
  disconnect?: Prisma.CategoryWhereInput | boolean
  delete?: Prisma.CategoryWhereInput | boolean
  connect?: Prisma.CategoryWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CategoryUpdateToOneWithWhereWithoutIncomesInput, Prisma.CategoryUpdateWithoutIncomesInput>, Prisma.CategoryUncheckedUpdateWithoutIncomesInput>
}

export type CategoryCreateNestedOneWithoutBudgetsInput = {
  create?: Prisma.XOR<Prisma.CategoryCreateWithoutBudgetsInput, Prisma.CategoryUncheckedCreateWithoutBudgetsInput>
  connectOrCreate?: Prisma.CategoryCreateOrConnectWithoutBudgetsInput
  connect?: Prisma.CategoryWhereUniqueInput
}

export type CategoryUpdateOneWithoutBudgetsNestedInput = {
  create?: Prisma.XOR<Prisma.CategoryCreateWithoutBudgetsInput, Prisma.CategoryUncheckedCreateWithoutBudgetsInput>
  connectOrCreate?: Prisma.CategoryCreateOrConnectWithoutBudgetsInput
  upsert?: Prisma.CategoryUpsertWithoutBudgetsInput
  disconnect?: Prisma.CategoryWhereInput | boolean
  delete?: Prisma.CategoryWhereInput | boolean
  connect?: Prisma.CategoryWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CategoryUpdateToOneWithWhereWithoutBudgetsInput, Prisma.CategoryUpdateWithoutBudgetsInput>, Prisma.CategoryUncheckedUpdateWithoutBudgetsInput>
}

export type CategoryCreateWithoutSubCategoriesInput = {
  categoryName: string
  logoPath?: string | null
  isExpense: boolean
  isIncome: boolean
  isActive?: boolean
  isDeleted?: boolean
  description?: string | null
  sequence?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  userId: number
  created?: Date | string
  modified?: Date | string
  expenses?: Prisma.ExpenseCreateNestedManyWithoutCategoryInput
  incomes?: Prisma.IncomeCreateNestedManyWithoutCategoryInput
  budgets?: Prisma.BudgetCreateNestedManyWithoutCategoryInput
}

export type CategoryUncheckedCreateWithoutSubCategoriesInput = {
  categoryId?: number
  categoryName: string
  logoPath?: string | null
  isExpense: boolean
  isIncome: boolean
  isActive?: boolean
  isDeleted?: boolean
  description?: string | null
  sequence?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  userId: number
  created?: Date | string
  modified?: Date | string
  expenses?: Prisma.ExpenseUncheckedCreateNestedManyWithoutCategoryInput
  incomes?: Prisma.IncomeUncheckedCreateNestedManyWithoutCategoryInput
  budgets?: Prisma.BudgetUncheckedCreateNestedManyWithoutCategoryInput
}

export type CategoryCreateOrConnectWithoutSubCategoriesInput = {
  where: Prisma.CategoryWhereUniqueInput
  create: Prisma.XOR<Prisma.CategoryCreateWithoutSubCategoriesInput, Prisma.CategoryUncheckedCreateWithoutSubCategoriesInput>
}

export type CategoryUpsertWithoutSubCategoriesInput = {
  update: Prisma.XOR<Prisma.CategoryUpdateWithoutSubCategoriesInput, Prisma.CategoryUncheckedUpdateWithoutSubCategoriesInput>
  create: Prisma.XOR<Prisma.CategoryCreateWithoutSubCategoriesInput, Prisma.CategoryUncheckedCreateWithoutSubCategoriesInput>
  where?: Prisma.CategoryWhereInput
}

export type CategoryUpdateToOneWithWhereWithoutSubCategoriesInput = {
  where?: Prisma.CategoryWhereInput
  data: Prisma.XOR<Prisma.CategoryUpdateWithoutSubCategoriesInput, Prisma.CategoryUncheckedUpdateWithoutSubCategoriesInput>
}

export type CategoryUpdateWithoutSubCategoriesInput = {
  categoryName?: Prisma.StringFieldUpdateOperationsInput | string
  logoPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isExpense?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isIncome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sequence?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expenses?: Prisma.ExpenseUpdateManyWithoutCategoryNestedInput
  incomes?: Prisma.IncomeUpdateManyWithoutCategoryNestedInput
  budgets?: Prisma.BudgetUpdateManyWithoutCategoryNestedInput
}

export type CategoryUncheckedUpdateWithoutSubCategoriesInput = {
  categoryId?: Prisma.IntFieldUpdateOperationsInput | number
  categoryName?: Prisma.StringFieldUpdateOperationsInput | string
  logoPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isExpense?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isIncome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sequence?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expenses?: Prisma.ExpenseUncheckedUpdateManyWithoutCategoryNestedInput
  incomes?: Prisma.IncomeUncheckedUpdateManyWithoutCategoryNestedInput
  budgets?: Prisma.BudgetUncheckedUpdateManyWithoutCategoryNestedInput
}

export type CategoryCreateWithoutExpensesInput = {
  categoryName: string
  logoPath?: string | null
  isExpense: boolean
  isIncome: boolean
  isActive?: boolean
  isDeleted?: boolean
  description?: string | null
  sequence?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  userId: number
  created?: Date | string
  modified?: Date | string
  subCategories?: Prisma.SubCategoryCreateNestedManyWithoutCategoryInput
  incomes?: Prisma.IncomeCreateNestedManyWithoutCategoryInput
  budgets?: Prisma.BudgetCreateNestedManyWithoutCategoryInput
}

export type CategoryUncheckedCreateWithoutExpensesInput = {
  categoryId?: number
  categoryName: string
  logoPath?: string | null
  isExpense: boolean
  isIncome: boolean
  isActive?: boolean
  isDeleted?: boolean
  description?: string | null
  sequence?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  userId: number
  created?: Date | string
  modified?: Date | string
  subCategories?: Prisma.SubCategoryUncheckedCreateNestedManyWithoutCategoryInput
  incomes?: Prisma.IncomeUncheckedCreateNestedManyWithoutCategoryInput
  budgets?: Prisma.BudgetUncheckedCreateNestedManyWithoutCategoryInput
}

export type CategoryCreateOrConnectWithoutExpensesInput = {
  where: Prisma.CategoryWhereUniqueInput
  create: Prisma.XOR<Prisma.CategoryCreateWithoutExpensesInput, Prisma.CategoryUncheckedCreateWithoutExpensesInput>
}

export type CategoryUpsertWithoutExpensesInput = {
  update: Prisma.XOR<Prisma.CategoryUpdateWithoutExpensesInput, Prisma.CategoryUncheckedUpdateWithoutExpensesInput>
  create: Prisma.XOR<Prisma.CategoryCreateWithoutExpensesInput, Prisma.CategoryUncheckedCreateWithoutExpensesInput>
  where?: Prisma.CategoryWhereInput
}

export type CategoryUpdateToOneWithWhereWithoutExpensesInput = {
  where?: Prisma.CategoryWhereInput
  data: Prisma.XOR<Prisma.CategoryUpdateWithoutExpensesInput, Prisma.CategoryUncheckedUpdateWithoutExpensesInput>
}

export type CategoryUpdateWithoutExpensesInput = {
  categoryName?: Prisma.StringFieldUpdateOperationsInput | string
  logoPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isExpense?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isIncome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sequence?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subCategories?: Prisma.SubCategoryUpdateManyWithoutCategoryNestedInput
  incomes?: Prisma.IncomeUpdateManyWithoutCategoryNestedInput
  budgets?: Prisma.BudgetUpdateManyWithoutCategoryNestedInput
}

export type CategoryUncheckedUpdateWithoutExpensesInput = {
  categoryId?: Prisma.IntFieldUpdateOperationsInput | number
  categoryName?: Prisma.StringFieldUpdateOperationsInput | string
  logoPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isExpense?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isIncome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sequence?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subCategories?: Prisma.SubCategoryUncheckedUpdateManyWithoutCategoryNestedInput
  incomes?: Prisma.IncomeUncheckedUpdateManyWithoutCategoryNestedInput
  budgets?: Prisma.BudgetUncheckedUpdateManyWithoutCategoryNestedInput
}

export type CategoryCreateWithoutIncomesInput = {
  categoryName: string
  logoPath?: string | null
  isExpense: boolean
  isIncome: boolean
  isActive?: boolean
  isDeleted?: boolean
  description?: string | null
  sequence?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  userId: number
  created?: Date | string
  modified?: Date | string
  subCategories?: Prisma.SubCategoryCreateNestedManyWithoutCategoryInput
  expenses?: Prisma.ExpenseCreateNestedManyWithoutCategoryInput
  budgets?: Prisma.BudgetCreateNestedManyWithoutCategoryInput
}

export type CategoryUncheckedCreateWithoutIncomesInput = {
  categoryId?: number
  categoryName: string
  logoPath?: string | null
  isExpense: boolean
  isIncome: boolean
  isActive?: boolean
  isDeleted?: boolean
  description?: string | null
  sequence?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  userId: number
  created?: Date | string
  modified?: Date | string
  subCategories?: Prisma.SubCategoryUncheckedCreateNestedManyWithoutCategoryInput
  expenses?: Prisma.ExpenseUncheckedCreateNestedManyWithoutCategoryInput
  budgets?: Prisma.BudgetUncheckedCreateNestedManyWithoutCategoryInput
}

export type CategoryCreateOrConnectWithoutIncomesInput = {
  where: Prisma.CategoryWhereUniqueInput
  create: Prisma.XOR<Prisma.CategoryCreateWithoutIncomesInput, Prisma.CategoryUncheckedCreateWithoutIncomesInput>
}

export type CategoryUpsertWithoutIncomesInput = {
  update: Prisma.XOR<Prisma.CategoryUpdateWithoutIncomesInput, Prisma.CategoryUncheckedUpdateWithoutIncomesInput>
  create: Prisma.XOR<Prisma.CategoryCreateWithoutIncomesInput, Prisma.CategoryUncheckedCreateWithoutIncomesInput>
  where?: Prisma.CategoryWhereInput
}

export type CategoryUpdateToOneWithWhereWithoutIncomesInput = {
  where?: Prisma.CategoryWhereInput
  data: Prisma.XOR<Prisma.CategoryUpdateWithoutIncomesInput, Prisma.CategoryUncheckedUpdateWithoutIncomesInput>
}

export type CategoryUpdateWithoutIncomesInput = {
  categoryName?: Prisma.StringFieldUpdateOperationsInput | string
  logoPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isExpense?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isIncome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sequence?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subCategories?: Prisma.SubCategoryUpdateManyWithoutCategoryNestedInput
  expenses?: Prisma.ExpenseUpdateManyWithoutCategoryNestedInput
  budgets?: Prisma.BudgetUpdateManyWithoutCategoryNestedInput
}

export type CategoryUncheckedUpdateWithoutIncomesInput = {
  categoryId?: Prisma.IntFieldUpdateOperationsInput | number
  categoryName?: Prisma.StringFieldUpdateOperationsInput | string
  logoPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isExpense?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isIncome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sequence?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subCategories?: Prisma.SubCategoryUncheckedUpdateManyWithoutCategoryNestedInput
  expenses?: Prisma.ExpenseUncheckedUpdateManyWithoutCategoryNestedInput
  budgets?: Prisma.BudgetUncheckedUpdateManyWithoutCategoryNestedInput
}

export type CategoryCreateWithoutBudgetsInput = {
  categoryName: string
  logoPath?: string | null
  isExpense: boolean
  isIncome: boolean
  isActive?: boolean
  isDeleted?: boolean
  description?: string | null
  sequence?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  userId: number
  created?: Date | string
  modified?: Date | string
  subCategories?: Prisma.SubCategoryCreateNestedManyWithoutCategoryInput
  expenses?: Prisma.ExpenseCreateNestedManyWithoutCategoryInput
  incomes?: Prisma.IncomeCreateNestedManyWithoutCategoryInput
}

export type CategoryUncheckedCreateWithoutBudgetsInput = {
  categoryId?: number
  categoryName: string
  logoPath?: string | null
  isExpense: boolean
  isIncome: boolean
  isActive?: boolean
  isDeleted?: boolean
  description?: string | null
  sequence?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  userId: number
  created?: Date | string
  modified?: Date | string
  subCategories?: Prisma.SubCategoryUncheckedCreateNestedManyWithoutCategoryInput
  expenses?: Prisma.ExpenseUncheckedCreateNestedManyWithoutCategoryInput
  incomes?: Prisma.IncomeUncheckedCreateNestedManyWithoutCategoryInput
}

export type CategoryCreateOrConnectWithoutBudgetsInput = {
  where: Prisma.CategoryWhereUniqueInput
  create: Prisma.XOR<Prisma.CategoryCreateWithoutBudgetsInput, Prisma.CategoryUncheckedCreateWithoutBudgetsInput>
}

export type CategoryUpsertWithoutBudgetsInput = {
  update: Prisma.XOR<Prisma.CategoryUpdateWithoutBudgetsInput, Prisma.CategoryUncheckedUpdateWithoutBudgetsInput>
  create: Prisma.XOR<Prisma.CategoryCreateWithoutBudgetsInput, Prisma.CategoryUncheckedCreateWithoutBudgetsInput>
  where?: Prisma.CategoryWhereInput
}

export type CategoryUpdateToOneWithWhereWithoutBudgetsInput = {
  where?: Prisma.CategoryWhereInput
  data: Prisma.XOR<Prisma.CategoryUpdateWithoutBudgetsInput, Prisma.CategoryUncheckedUpdateWithoutBudgetsInput>
}

export type CategoryUpdateWithoutBudgetsInput = {
  categoryName?: Prisma.StringFieldUpdateOperationsInput | string
  logoPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isExpense?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isIncome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sequence?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subCategories?: Prisma.SubCategoryUpdateManyWithoutCategoryNestedInput
  expenses?: Prisma.ExpenseUpdateManyWithoutCategoryNestedInput
  incomes?: Prisma.IncomeUpdateManyWithoutCategoryNestedInput
}

export type CategoryUncheckedUpdateWithoutBudgetsInput = {
  categoryId?: Prisma.IntFieldUpdateOperationsInput | number
  categoryName?: Prisma.StringFieldUpdateOperationsInput | string
  logoPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isExpense?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isIncome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sequence?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subCategories?: Prisma.SubCategoryUncheckedUpdateManyWithoutCategoryNestedInput
  expenses?: Prisma.ExpenseUncheckedUpdateManyWithoutCategoryNestedInput
  incomes?: Prisma.IncomeUncheckedUpdateManyWithoutCategoryNestedInput
}


/**
 * Count Type CategoryCountOutputType
 */

export type CategoryCountOutputType = {
  subCategories: number
  expenses: number
  incomes: number
  budgets: number
}

export type CategoryCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subCategories?: boolean | CategoryCountOutputTypeCountSubCategoriesArgs
  expenses?: boolean | CategoryCountOutputTypeCountExpensesArgs
  incomes?: boolean | CategoryCountOutputTypeCountIncomesArgs
  budgets?: boolean | CategoryCountOutputTypeCountBudgetsArgs
}

/**
 * CategoryCountOutputType without action
 */
export type CategoryCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CategoryCountOutputType
   */
  select?: Prisma.CategoryCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CategoryCountOutputType without action
 */
export type CategoryCountOutputTypeCountSubCategoriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SubCategoryWhereInput
}

/**
 * CategoryCountOutputType without action
 */
export type CategoryCountOutputTypeCountExpensesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ExpenseWhereInput
}

/**
 * CategoryCountOutputType without action
 */
export type CategoryCountOutputTypeCountIncomesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.IncomeWhereInput
}

/**
 * CategoryCountOutputType without action
 */
export type CategoryCountOutputTypeCountBudgetsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BudgetWhereInput
}


export type CategorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  categoryId?: boolean
  categoryName?: boolean
  logoPath?: boolean
  isExpense?: boolean
  isIncome?: boolean
  isActive?: boolean
  isDeleted?: boolean
  description?: boolean
  sequence?: boolean
  userId?: boolean
  created?: boolean
  modified?: boolean
  subCategories?: boolean | Prisma.Category$subCategoriesArgs<ExtArgs>
  expenses?: boolean | Prisma.Category$expensesArgs<ExtArgs>
  incomes?: boolean | Prisma.Category$incomesArgs<ExtArgs>
  budgets?: boolean | Prisma.Category$budgetsArgs<ExtArgs>
  _count?: boolean | Prisma.CategoryCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["category"]>

export type CategorySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  categoryId?: boolean
  categoryName?: boolean
  logoPath?: boolean
  isExpense?: boolean
  isIncome?: boolean
  isActive?: boolean
  isDeleted?: boolean
  description?: boolean
  sequence?: boolean
  userId?: boolean
  created?: boolean
  modified?: boolean
}, ExtArgs["result"]["category"]>

export type CategorySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  categoryId?: boolean
  categoryName?: boolean
  logoPath?: boolean
  isExpense?: boolean
  isIncome?: boolean
  isActive?: boolean
  isDeleted?: boolean
  description?: boolean
  sequence?: boolean
  userId?: boolean
  created?: boolean
  modified?: boolean
}, ExtArgs["result"]["category"]>

export type CategorySelectScalar = {
  categoryId?: boolean
  categoryName?: boolean
  logoPath?: boolean
  isExpense?: boolean
  isIncome?: boolean
  isActive?: boolean
  isDeleted?: boolean
  description?: boolean
  sequence?: boolean
  userId?: boolean
  created?: boolean
  modified?: boolean
}

export type CategoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"categoryId" | "categoryName" | "logoPath" | "isExpense" | "isIncome" | "isActive" | "isDeleted" | "description" | "sequence" | "userId" | "created" | "modified", ExtArgs["result"]["category"]>
export type CategoryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subCategories?: boolean | Prisma.Category$subCategoriesArgs<ExtArgs>
  expenses?: boolean | Prisma.Category$expensesArgs<ExtArgs>
  incomes?: boolean | Prisma.Category$incomesArgs<ExtArgs>
  budgets?: boolean | Prisma.Category$budgetsArgs<ExtArgs>
  _count?: boolean | Prisma.CategoryCountOutputTypeDefaultArgs<ExtArgs>
}
export type CategoryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type CategoryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $CategoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Category"
  objects: {
    subCategories: Prisma.$SubCategoryPayload<ExtArgs>[]
    expenses: Prisma.$ExpensePayload<ExtArgs>[]
    incomes: Prisma.$IncomePayload<ExtArgs>[]
    budgets: Prisma.$BudgetPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    categoryId: number
    categoryName: string
    logoPath: string | null
    isExpense: boolean
    isIncome: boolean
    isActive: boolean
    isDeleted: boolean
    description: string | null
    sequence: runtime.Decimal | null
    userId: number
    created: Date
    modified: Date
  }, ExtArgs["result"]["category"]>
  composites: {}
}

export type CategoryGetPayload<S extends boolean | null | undefined | CategoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CategoryPayload, S>

export type CategoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CategoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CategoryCountAggregateInputType | true
  }

export interface CategoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Category'], meta: { name: 'Category' } }
  /**
   * Find zero or one Category that matches the filter.
   * @param {CategoryFindUniqueArgs} args - Arguments to find a Category
   * @example
   * // Get one Category
   * const category = await prisma.category.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CategoryFindUniqueArgs>(args: Prisma.SelectSubset<T, CategoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Category that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CategoryFindUniqueOrThrowArgs} args - Arguments to find a Category
   * @example
   * // Get one Category
   * const category = await prisma.category.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CategoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CategoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Category that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CategoryFindFirstArgs} args - Arguments to find a Category
   * @example
   * // Get one Category
   * const category = await prisma.category.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CategoryFindFirstArgs>(args?: Prisma.SelectSubset<T, CategoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Category that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CategoryFindFirstOrThrowArgs} args - Arguments to find a Category
   * @example
   * // Get one Category
   * const category = await prisma.category.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CategoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CategoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Categories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CategoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Categories
   * const categories = await prisma.category.findMany()
   * 
   * // Get first 10 Categories
   * const categories = await prisma.category.findMany({ take: 10 })
   * 
   * // Only select the `categoryId`
   * const categoryWithCategoryIdOnly = await prisma.category.findMany({ select: { categoryId: true } })
   * 
   */
  findMany<T extends CategoryFindManyArgs>(args?: Prisma.SelectSubset<T, CategoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Category.
   * @param {CategoryCreateArgs} args - Arguments to create a Category.
   * @example
   * // Create one Category
   * const Category = await prisma.category.create({
   *   data: {
   *     // ... data to create a Category
   *   }
   * })
   * 
   */
  create<T extends CategoryCreateArgs>(args: Prisma.SelectSubset<T, CategoryCreateArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Categories.
   * @param {CategoryCreateManyArgs} args - Arguments to create many Categories.
   * @example
   * // Create many Categories
   * const category = await prisma.category.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CategoryCreateManyArgs>(args?: Prisma.SelectSubset<T, CategoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Categories and returns the data saved in the database.
   * @param {CategoryCreateManyAndReturnArgs} args - Arguments to create many Categories.
   * @example
   * // Create many Categories
   * const category = await prisma.category.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Categories and only return the `categoryId`
   * const categoryWithCategoryIdOnly = await prisma.category.createManyAndReturn({
   *   select: { categoryId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CategoryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CategoryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Category.
   * @param {CategoryDeleteArgs} args - Arguments to delete one Category.
   * @example
   * // Delete one Category
   * const Category = await prisma.category.delete({
   *   where: {
   *     // ... filter to delete one Category
   *   }
   * })
   * 
   */
  delete<T extends CategoryDeleteArgs>(args: Prisma.SelectSubset<T, CategoryDeleteArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Category.
   * @param {CategoryUpdateArgs} args - Arguments to update one Category.
   * @example
   * // Update one Category
   * const category = await prisma.category.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CategoryUpdateArgs>(args: Prisma.SelectSubset<T, CategoryUpdateArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Categories.
   * @param {CategoryDeleteManyArgs} args - Arguments to filter Categories to delete.
   * @example
   * // Delete a few Categories
   * const { count } = await prisma.category.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CategoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, CategoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Categories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CategoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Categories
   * const category = await prisma.category.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CategoryUpdateManyArgs>(args: Prisma.SelectSubset<T, CategoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Categories and returns the data updated in the database.
   * @param {CategoryUpdateManyAndReturnArgs} args - Arguments to update many Categories.
   * @example
   * // Update many Categories
   * const category = await prisma.category.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Categories and only return the `categoryId`
   * const categoryWithCategoryIdOnly = await prisma.category.updateManyAndReturn({
   *   select: { categoryId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CategoryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CategoryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Category.
   * @param {CategoryUpsertArgs} args - Arguments to update or create a Category.
   * @example
   * // Update or create a Category
   * const category = await prisma.category.upsert({
   *   create: {
   *     // ... data to create a Category
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Category we want to update
   *   }
   * })
   */
  upsert<T extends CategoryUpsertArgs>(args: Prisma.SelectSubset<T, CategoryUpsertArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Categories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CategoryCountArgs} args - Arguments to filter Categories to count.
   * @example
   * // Count the number of Categories
   * const count = await prisma.category.count({
   *   where: {
   *     // ... the filter for the Categories we want to count
   *   }
   * })
  **/
  count<T extends CategoryCountArgs>(
    args?: Prisma.Subset<T, CategoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CategoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Category.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CategoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CategoryAggregateArgs>(args: Prisma.Subset<T, CategoryAggregateArgs>): Prisma.PrismaPromise<GetCategoryAggregateType<T>>

  /**
   * Group by Category.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CategoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CategoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CategoryGroupByArgs['orderBy'] }
      : { orderBy?: CategoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CategoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCategoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Category model
 */
readonly fields: CategoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Category.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CategoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  subCategories<T extends Prisma.Category$subCategoriesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Category$subCategoriesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SubCategoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  expenses<T extends Prisma.Category$expensesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Category$expensesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExpensePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  incomes<T extends Prisma.Category$incomesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Category$incomesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IncomePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  budgets<T extends Prisma.Category$budgetsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Category$budgetsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BudgetPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Category model
 */
export interface CategoryFieldRefs {
  readonly categoryId: Prisma.FieldRef<"Category", 'Int'>
  readonly categoryName: Prisma.FieldRef<"Category", 'String'>
  readonly logoPath: Prisma.FieldRef<"Category", 'String'>
  readonly isExpense: Prisma.FieldRef<"Category", 'Boolean'>
  readonly isIncome: Prisma.FieldRef<"Category", 'Boolean'>
  readonly isActive: Prisma.FieldRef<"Category", 'Boolean'>
  readonly isDeleted: Prisma.FieldRef<"Category", 'Boolean'>
  readonly description: Prisma.FieldRef<"Category", 'String'>
  readonly sequence: Prisma.FieldRef<"Category", 'Decimal'>
  readonly userId: Prisma.FieldRef<"Category", 'Int'>
  readonly created: Prisma.FieldRef<"Category", 'DateTime'>
  readonly modified: Prisma.FieldRef<"Category", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Category findUnique
 */
export type CategoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
  /**
   * Filter, which Category to fetch.
   */
  where: Prisma.CategoryWhereUniqueInput
}

/**
 * Category findUniqueOrThrow
 */
export type CategoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
  /**
   * Filter, which Category to fetch.
   */
  where: Prisma.CategoryWhereUniqueInput
}

/**
 * Category findFirst
 */
export type CategoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
  /**
   * Filter, which Category to fetch.
   */
  where?: Prisma.CategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Categories to fetch.
   */
  orderBy?: Prisma.CategoryOrderByWithRelationInput | Prisma.CategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Categories.
   */
  cursor?: Prisma.CategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Categories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Categories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Categories.
   */
  distinct?: Prisma.CategoryScalarFieldEnum | Prisma.CategoryScalarFieldEnum[]
}

/**
 * Category findFirstOrThrow
 */
export type CategoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
  /**
   * Filter, which Category to fetch.
   */
  where?: Prisma.CategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Categories to fetch.
   */
  orderBy?: Prisma.CategoryOrderByWithRelationInput | Prisma.CategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Categories.
   */
  cursor?: Prisma.CategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Categories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Categories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Categories.
   */
  distinct?: Prisma.CategoryScalarFieldEnum | Prisma.CategoryScalarFieldEnum[]
}

/**
 * Category findMany
 */
export type CategoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
  /**
   * Filter, which Categories to fetch.
   */
  where?: Prisma.CategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Categories to fetch.
   */
  orderBy?: Prisma.CategoryOrderByWithRelationInput | Prisma.CategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Categories.
   */
  cursor?: Prisma.CategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Categories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Categories.
   */
  skip?: number
  distinct?: Prisma.CategoryScalarFieldEnum | Prisma.CategoryScalarFieldEnum[]
}

/**
 * Category create
 */
export type CategoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
  /**
   * The data needed to create a Category.
   */
  data: Prisma.XOR<Prisma.CategoryCreateInput, Prisma.CategoryUncheckedCreateInput>
}

/**
 * Category createMany
 */
export type CategoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Categories.
   */
  data: Prisma.CategoryCreateManyInput | Prisma.CategoryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Category createManyAndReturn
 */
export type CategoryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * The data used to create many Categories.
   */
  data: Prisma.CategoryCreateManyInput | Prisma.CategoryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Category update
 */
export type CategoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
  /**
   * The data needed to update a Category.
   */
  data: Prisma.XOR<Prisma.CategoryUpdateInput, Prisma.CategoryUncheckedUpdateInput>
  /**
   * Choose, which Category to update.
   */
  where: Prisma.CategoryWhereUniqueInput
}

/**
 * Category updateMany
 */
export type CategoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Categories.
   */
  data: Prisma.XOR<Prisma.CategoryUpdateManyMutationInput, Prisma.CategoryUncheckedUpdateManyInput>
  /**
   * Filter which Categories to update
   */
  where?: Prisma.CategoryWhereInput
  /**
   * Limit how many Categories to update.
   */
  limit?: number
}

/**
 * Category updateManyAndReturn
 */
export type CategoryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * The data used to update Categories.
   */
  data: Prisma.XOR<Prisma.CategoryUpdateManyMutationInput, Prisma.CategoryUncheckedUpdateManyInput>
  /**
   * Filter which Categories to update
   */
  where?: Prisma.CategoryWhereInput
  /**
   * Limit how many Categories to update.
   */
  limit?: number
}

/**
 * Category upsert
 */
export type CategoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
  /**
   * The filter to search for the Category to update in case it exists.
   */
  where: Prisma.CategoryWhereUniqueInput
  /**
   * In case the Category found by the `where` argument doesn't exist, create a new Category with this data.
   */
  create: Prisma.XOR<Prisma.CategoryCreateInput, Prisma.CategoryUncheckedCreateInput>
  /**
   * In case the Category was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CategoryUpdateInput, Prisma.CategoryUncheckedUpdateInput>
}

/**
 * Category delete
 */
export type CategoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
  /**
   * Filter which Category to delete.
   */
  where: Prisma.CategoryWhereUniqueInput
}

/**
 * Category deleteMany
 */
export type CategoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Categories to delete
   */
  where?: Prisma.CategoryWhereInput
  /**
   * Limit how many Categories to delete.
   */
  limit?: number
}

/**
 * Category.subCategories
 */
export type Category$subCategoriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubCategory
   */
  select?: Prisma.SubCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubCategory
   */
  omit?: Prisma.SubCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubCategoryInclude<ExtArgs> | null
  where?: Prisma.SubCategoryWhereInput
  orderBy?: Prisma.SubCategoryOrderByWithRelationInput | Prisma.SubCategoryOrderByWithRelationInput[]
  cursor?: Prisma.SubCategoryWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SubCategoryScalarFieldEnum | Prisma.SubCategoryScalarFieldEnum[]
}

/**
 * Category.expenses
 */
export type Category$expensesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Expense
   */
  select?: Prisma.ExpenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Expense
   */
  omit?: Prisma.ExpenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpenseInclude<ExtArgs> | null
  where?: Prisma.ExpenseWhereInput
  orderBy?: Prisma.ExpenseOrderByWithRelationInput | Prisma.ExpenseOrderByWithRelationInput[]
  cursor?: Prisma.ExpenseWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ExpenseScalarFieldEnum | Prisma.ExpenseScalarFieldEnum[]
}

/**
 * Category.incomes
 */
export type Category$incomesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Income
   */
  select?: Prisma.IncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Income
   */
  omit?: Prisma.IncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncomeInclude<ExtArgs> | null
  where?: Prisma.IncomeWhereInput
  orderBy?: Prisma.IncomeOrderByWithRelationInput | Prisma.IncomeOrderByWithRelationInput[]
  cursor?: Prisma.IncomeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.IncomeScalarFieldEnum | Prisma.IncomeScalarFieldEnum[]
}

/**
 * Category.budgets
 */
export type Category$budgetsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Budget
   */
  select?: Prisma.BudgetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Budget
   */
  omit?: Prisma.BudgetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BudgetInclude<ExtArgs> | null
  where?: Prisma.BudgetWhereInput
  orderBy?: Prisma.BudgetOrderByWithRelationInput | Prisma.BudgetOrderByWithRelationInput[]
  cursor?: Prisma.BudgetWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BudgetScalarFieldEnum | Prisma.BudgetScalarFieldEnum[]
}

/**
 * Category without action
 */
export type CategoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
}
