
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Expense` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Expense
 * 
 */
export type ExpenseModel = runtime.Types.Result.DefaultSelection<Prisma.$ExpensePayload>

export type AggregateExpense = {
  _count: ExpenseCountAggregateOutputType | null
  _avg: ExpenseAvgAggregateOutputType | null
  _sum: ExpenseSumAggregateOutputType | null
  _min: ExpenseMinAggregateOutputType | null
  _max: ExpenseMaxAggregateOutputType | null
}

export type ExpenseAvgAggregateOutputType = {
  expenseId: number | null
  amount: runtime.Decimal | null
  categoryId: number | null
  subCategoryId: number | null
  projectId: number | null
  peopleId: number | null
  userId: number | null
}

export type ExpenseSumAggregateOutputType = {
  expenseId: number | null
  amount: runtime.Decimal | null
  categoryId: number | null
  subCategoryId: number | null
  projectId: number | null
  peopleId: number | null
  userId: number | null
}

export type ExpenseMinAggregateOutputType = {
  expenseId: number | null
  expenseDate: Date | null
  amount: runtime.Decimal | null
  expenseDetail: string | null
  attachmentPath: string | null
  description: string | null
  isDeleted: boolean | null
  categoryId: number | null
  subCategoryId: number | null
  projectId: number | null
  peopleId: number | null
  userId: number | null
  created: Date | null
  modified: Date | null
}

export type ExpenseMaxAggregateOutputType = {
  expenseId: number | null
  expenseDate: Date | null
  amount: runtime.Decimal | null
  expenseDetail: string | null
  attachmentPath: string | null
  description: string | null
  isDeleted: boolean | null
  categoryId: number | null
  subCategoryId: number | null
  projectId: number | null
  peopleId: number | null
  userId: number | null
  created: Date | null
  modified: Date | null
}

export type ExpenseCountAggregateOutputType = {
  expenseId: number
  expenseDate: number
  amount: number
  expenseDetail: number
  attachmentPath: number
  description: number
  isDeleted: number
  categoryId: number
  subCategoryId: number
  projectId: number
  peopleId: number
  userId: number
  created: number
  modified: number
  _all: number
}


export type ExpenseAvgAggregateInputType = {
  expenseId?: true
  amount?: true
  categoryId?: true
  subCategoryId?: true
  projectId?: true
  peopleId?: true
  userId?: true
}

export type ExpenseSumAggregateInputType = {
  expenseId?: true
  amount?: true
  categoryId?: true
  subCategoryId?: true
  projectId?: true
  peopleId?: true
  userId?: true
}

export type ExpenseMinAggregateInputType = {
  expenseId?: true
  expenseDate?: true
  amount?: true
  expenseDetail?: true
  attachmentPath?: true
  description?: true
  isDeleted?: true
  categoryId?: true
  subCategoryId?: true
  projectId?: true
  peopleId?: true
  userId?: true
  created?: true
  modified?: true
}

export type ExpenseMaxAggregateInputType = {
  expenseId?: true
  expenseDate?: true
  amount?: true
  expenseDetail?: true
  attachmentPath?: true
  description?: true
  isDeleted?: true
  categoryId?: true
  subCategoryId?: true
  projectId?: true
  peopleId?: true
  userId?: true
  created?: true
  modified?: true
}

export type ExpenseCountAggregateInputType = {
  expenseId?: true
  expenseDate?: true
  amount?: true
  expenseDetail?: true
  attachmentPath?: true
  description?: true
  isDeleted?: true
  categoryId?: true
  subCategoryId?: true
  projectId?: true
  peopleId?: true
  userId?: true
  created?: true
  modified?: true
  _all?: true
}

export type ExpenseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Expense to aggregate.
   */
  where?: Prisma.ExpenseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Expenses to fetch.
   */
  orderBy?: Prisma.ExpenseOrderByWithRelationInput | Prisma.ExpenseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ExpenseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Expenses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Expenses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Expenses
  **/
  _count?: true | ExpenseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ExpenseAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ExpenseSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ExpenseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ExpenseMaxAggregateInputType
}

export type GetExpenseAggregateType<T extends ExpenseAggregateArgs> = {
      [P in keyof T & keyof AggregateExpense]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateExpense[P]>
    : Prisma.GetScalarType<T[P], AggregateExpense[P]>
}




export type ExpenseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ExpenseWhereInput
  orderBy?: Prisma.ExpenseOrderByWithAggregationInput | Prisma.ExpenseOrderByWithAggregationInput[]
  by: Prisma.ExpenseScalarFieldEnum[] | Prisma.ExpenseScalarFieldEnum
  having?: Prisma.ExpenseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ExpenseCountAggregateInputType | true
  _avg?: ExpenseAvgAggregateInputType
  _sum?: ExpenseSumAggregateInputType
  _min?: ExpenseMinAggregateInputType
  _max?: ExpenseMaxAggregateInputType
}

export type ExpenseGroupByOutputType = {
  expenseId: number
  expenseDate: Date
  amount: runtime.Decimal
  expenseDetail: string | null
  attachmentPath: string | null
  description: string | null
  isDeleted: boolean
  categoryId: number | null
  subCategoryId: number | null
  projectId: number | null
  peopleId: number
  userId: number
  created: Date
  modified: Date
  _count: ExpenseCountAggregateOutputType | null
  _avg: ExpenseAvgAggregateOutputType | null
  _sum: ExpenseSumAggregateOutputType | null
  _min: ExpenseMinAggregateOutputType | null
  _max: ExpenseMaxAggregateOutputType | null
}

type GetExpenseGroupByPayload<T extends ExpenseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ExpenseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ExpenseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ExpenseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ExpenseGroupByOutputType[P]>
      }
    >
  >



export type ExpenseWhereInput = {
  AND?: Prisma.ExpenseWhereInput | Prisma.ExpenseWhereInput[]
  OR?: Prisma.ExpenseWhereInput[]
  NOT?: Prisma.ExpenseWhereInput | Prisma.ExpenseWhereInput[]
  expenseId?: Prisma.IntFilter<"Expense"> | number
  expenseDate?: Prisma.DateTimeFilter<"Expense"> | Date | string
  amount?: Prisma.DecimalFilter<"Expense"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: Prisma.StringNullableFilter<"Expense"> | string | null
  attachmentPath?: Prisma.StringNullableFilter<"Expense"> | string | null
  description?: Prisma.StringNullableFilter<"Expense"> | string | null
  isDeleted?: Prisma.BoolFilter<"Expense"> | boolean
  categoryId?: Prisma.IntNullableFilter<"Expense"> | number | null
  subCategoryId?: Prisma.IntNullableFilter<"Expense"> | number | null
  projectId?: Prisma.IntNullableFilter<"Expense"> | number | null
  peopleId?: Prisma.IntFilter<"Expense"> | number
  userId?: Prisma.IntFilter<"Expense"> | number
  created?: Prisma.DateTimeFilter<"Expense"> | Date | string
  modified?: Prisma.DateTimeFilter<"Expense"> | Date | string
  category?: Prisma.XOR<Prisma.CategoryNullableScalarRelationFilter, Prisma.CategoryWhereInput> | null
  subCategory?: Prisma.XOR<Prisma.SubCategoryNullableScalarRelationFilter, Prisma.SubCategoryWhereInput> | null
  project?: Prisma.XOR<Prisma.ProjectNullableScalarRelationFilter, Prisma.ProjectWhereInput> | null
  people?: Prisma.XOR<Prisma.PeopleScalarRelationFilter, Prisma.PeopleWhereInput>
}

export type ExpenseOrderByWithRelationInput = {
  expenseId?: Prisma.SortOrder
  expenseDate?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  expenseDetail?: Prisma.SortOrderInput | Prisma.SortOrder
  attachmentPath?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  categoryId?: Prisma.SortOrderInput | Prisma.SortOrder
  subCategoryId?: Prisma.SortOrderInput | Prisma.SortOrder
  projectId?: Prisma.SortOrderInput | Prisma.SortOrder
  peopleId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  created?: Prisma.SortOrder
  modified?: Prisma.SortOrder
  category?: Prisma.CategoryOrderByWithRelationInput
  subCategory?: Prisma.SubCategoryOrderByWithRelationInput
  project?: Prisma.ProjectOrderByWithRelationInput
  people?: Prisma.PeopleOrderByWithRelationInput
}

export type ExpenseWhereUniqueInput = Prisma.AtLeast<{
  expenseId?: number
  AND?: Prisma.ExpenseWhereInput | Prisma.ExpenseWhereInput[]
  OR?: Prisma.ExpenseWhereInput[]
  NOT?: Prisma.ExpenseWhereInput | Prisma.ExpenseWhereInput[]
  expenseDate?: Prisma.DateTimeFilter<"Expense"> | Date | string
  amount?: Prisma.DecimalFilter<"Expense"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: Prisma.StringNullableFilter<"Expense"> | string | null
  attachmentPath?: Prisma.StringNullableFilter<"Expense"> | string | null
  description?: Prisma.StringNullableFilter<"Expense"> | string | null
  isDeleted?: Prisma.BoolFilter<"Expense"> | boolean
  categoryId?: Prisma.IntNullableFilter<"Expense"> | number | null
  subCategoryId?: Prisma.IntNullableFilter<"Expense"> | number | null
  projectId?: Prisma.IntNullableFilter<"Expense"> | number | null
  peopleId?: Prisma.IntFilter<"Expense"> | number
  userId?: Prisma.IntFilter<"Expense"> | number
  created?: Prisma.DateTimeFilter<"Expense"> | Date | string
  modified?: Prisma.DateTimeFilter<"Expense"> | Date | string
  category?: Prisma.XOR<Prisma.CategoryNullableScalarRelationFilter, Prisma.CategoryWhereInput> | null
  subCategory?: Prisma.XOR<Prisma.SubCategoryNullableScalarRelationFilter, Prisma.SubCategoryWhereInput> | null
  project?: Prisma.XOR<Prisma.ProjectNullableScalarRelationFilter, Prisma.ProjectWhereInput> | null
  people?: Prisma.XOR<Prisma.PeopleScalarRelationFilter, Prisma.PeopleWhereInput>
}, "expenseId">

export type ExpenseOrderByWithAggregationInput = {
  expenseId?: Prisma.SortOrder
  expenseDate?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  expenseDetail?: Prisma.SortOrderInput | Prisma.SortOrder
  attachmentPath?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  categoryId?: Prisma.SortOrderInput | Prisma.SortOrder
  subCategoryId?: Prisma.SortOrderInput | Prisma.SortOrder
  projectId?: Prisma.SortOrderInput | Prisma.SortOrder
  peopleId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  created?: Prisma.SortOrder
  modified?: Prisma.SortOrder
  _count?: Prisma.ExpenseCountOrderByAggregateInput
  _avg?: Prisma.ExpenseAvgOrderByAggregateInput
  _max?: Prisma.ExpenseMaxOrderByAggregateInput
  _min?: Prisma.ExpenseMinOrderByAggregateInput
  _sum?: Prisma.ExpenseSumOrderByAggregateInput
}

export type ExpenseScalarWhereWithAggregatesInput = {
  AND?: Prisma.ExpenseScalarWhereWithAggregatesInput | Prisma.ExpenseScalarWhereWithAggregatesInput[]
  OR?: Prisma.ExpenseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ExpenseScalarWhereWithAggregatesInput | Prisma.ExpenseScalarWhereWithAggregatesInput[]
  expenseId?: Prisma.IntWithAggregatesFilter<"Expense"> | number
  expenseDate?: Prisma.DateTimeWithAggregatesFilter<"Expense"> | Date | string
  amount?: Prisma.DecimalWithAggregatesFilter<"Expense"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: Prisma.StringNullableWithAggregatesFilter<"Expense"> | string | null
  attachmentPath?: Prisma.StringNullableWithAggregatesFilter<"Expense"> | string | null
  description?: Prisma.StringNullableWithAggregatesFilter<"Expense"> | string | null
  isDeleted?: Prisma.BoolWithAggregatesFilter<"Expense"> | boolean
  categoryId?: Prisma.IntNullableWithAggregatesFilter<"Expense"> | number | null
  subCategoryId?: Prisma.IntNullableWithAggregatesFilter<"Expense"> | number | null
  projectId?: Prisma.IntNullableWithAggregatesFilter<"Expense"> | number | null
  peopleId?: Prisma.IntWithAggregatesFilter<"Expense"> | number
  userId?: Prisma.IntWithAggregatesFilter<"Expense"> | number
  created?: Prisma.DateTimeWithAggregatesFilter<"Expense"> | Date | string
  modified?: Prisma.DateTimeWithAggregatesFilter<"Expense"> | Date | string
}

export type ExpenseCreateInput = {
  expenseDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  userId: number
  created?: Date | string
  modified?: Date | string
  category?: Prisma.CategoryCreateNestedOneWithoutExpensesInput
  subCategory?: Prisma.SubCategoryCreateNestedOneWithoutExpensesInput
  project?: Prisma.ProjectCreateNestedOneWithoutExpensesInput
  people: Prisma.PeopleCreateNestedOneWithoutExpensesInput
}

export type ExpenseUncheckedCreateInput = {
  expenseId?: number
  expenseDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  categoryId?: number | null
  subCategoryId?: number | null
  projectId?: number | null
  peopleId: number
  userId: number
  created?: Date | string
  modified?: Date | string
}

export type ExpenseUpdateInput = {
  expenseDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  category?: Prisma.CategoryUpdateOneWithoutExpensesNestedInput
  subCategory?: Prisma.SubCategoryUpdateOneWithoutExpensesNestedInput
  project?: Prisma.ProjectUpdateOneWithoutExpensesNestedInput
  people?: Prisma.PeopleUpdateOneRequiredWithoutExpensesNestedInput
}

export type ExpenseUncheckedUpdateInput = {
  expenseId?: Prisma.IntFieldUpdateOperationsInput | number
  expenseDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  categoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  subCategoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  projectId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  peopleId?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExpenseCreateManyInput = {
  expenseId?: number
  expenseDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  categoryId?: number | null
  subCategoryId?: number | null
  projectId?: number | null
  peopleId: number
  userId: number
  created?: Date | string
  modified?: Date | string
}

export type ExpenseUpdateManyMutationInput = {
  expenseDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExpenseUncheckedUpdateManyInput = {
  expenseId?: Prisma.IntFieldUpdateOperationsInput | number
  expenseDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  categoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  subCategoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  projectId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  peopleId?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExpenseListRelationFilter = {
  every?: Prisma.ExpenseWhereInput
  some?: Prisma.ExpenseWhereInput
  none?: Prisma.ExpenseWhereInput
}

export type ExpenseOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ExpenseCountOrderByAggregateInput = {
  expenseId?: Prisma.SortOrder
  expenseDate?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  expenseDetail?: Prisma.SortOrder
  attachmentPath?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  subCategoryId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  peopleId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  created?: Prisma.SortOrder
  modified?: Prisma.SortOrder
}

export type ExpenseAvgOrderByAggregateInput = {
  expenseId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  subCategoryId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  peopleId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type ExpenseMaxOrderByAggregateInput = {
  expenseId?: Prisma.SortOrder
  expenseDate?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  expenseDetail?: Prisma.SortOrder
  attachmentPath?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  subCategoryId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  peopleId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  created?: Prisma.SortOrder
  modified?: Prisma.SortOrder
}

export type ExpenseMinOrderByAggregateInput = {
  expenseId?: Prisma.SortOrder
  expenseDate?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  expenseDetail?: Prisma.SortOrder
  attachmentPath?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  subCategoryId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  peopleId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  created?: Prisma.SortOrder
  modified?: Prisma.SortOrder
}

export type ExpenseSumOrderByAggregateInput = {
  expenseId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  subCategoryId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  peopleId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type ExpenseCreateNestedManyWithoutPeopleInput = {
  create?: Prisma.XOR<Prisma.ExpenseCreateWithoutPeopleInput, Prisma.ExpenseUncheckedCreateWithoutPeopleInput> | Prisma.ExpenseCreateWithoutPeopleInput[] | Prisma.ExpenseUncheckedCreateWithoutPeopleInput[]
  connectOrCreate?: Prisma.ExpenseCreateOrConnectWithoutPeopleInput | Prisma.ExpenseCreateOrConnectWithoutPeopleInput[]
  createMany?: Prisma.ExpenseCreateManyPeopleInputEnvelope
  connect?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
}

export type ExpenseUncheckedCreateNestedManyWithoutPeopleInput = {
  create?: Prisma.XOR<Prisma.ExpenseCreateWithoutPeopleInput, Prisma.ExpenseUncheckedCreateWithoutPeopleInput> | Prisma.ExpenseCreateWithoutPeopleInput[] | Prisma.ExpenseUncheckedCreateWithoutPeopleInput[]
  connectOrCreate?: Prisma.ExpenseCreateOrConnectWithoutPeopleInput | Prisma.ExpenseCreateOrConnectWithoutPeopleInput[]
  createMany?: Prisma.ExpenseCreateManyPeopleInputEnvelope
  connect?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
}

export type ExpenseUpdateManyWithoutPeopleNestedInput = {
  create?: Prisma.XOR<Prisma.ExpenseCreateWithoutPeopleInput, Prisma.ExpenseUncheckedCreateWithoutPeopleInput> | Prisma.ExpenseCreateWithoutPeopleInput[] | Prisma.ExpenseUncheckedCreateWithoutPeopleInput[]
  connectOrCreate?: Prisma.ExpenseCreateOrConnectWithoutPeopleInput | Prisma.ExpenseCreateOrConnectWithoutPeopleInput[]
  upsert?: Prisma.ExpenseUpsertWithWhereUniqueWithoutPeopleInput | Prisma.ExpenseUpsertWithWhereUniqueWithoutPeopleInput[]
  createMany?: Prisma.ExpenseCreateManyPeopleInputEnvelope
  set?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  disconnect?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  delete?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  connect?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  update?: Prisma.ExpenseUpdateWithWhereUniqueWithoutPeopleInput | Prisma.ExpenseUpdateWithWhereUniqueWithoutPeopleInput[]
  updateMany?: Prisma.ExpenseUpdateManyWithWhereWithoutPeopleInput | Prisma.ExpenseUpdateManyWithWhereWithoutPeopleInput[]
  deleteMany?: Prisma.ExpenseScalarWhereInput | Prisma.ExpenseScalarWhereInput[]
}

export type ExpenseUncheckedUpdateManyWithoutPeopleNestedInput = {
  create?: Prisma.XOR<Prisma.ExpenseCreateWithoutPeopleInput, Prisma.ExpenseUncheckedCreateWithoutPeopleInput> | Prisma.ExpenseCreateWithoutPeopleInput[] | Prisma.ExpenseUncheckedCreateWithoutPeopleInput[]
  connectOrCreate?: Prisma.ExpenseCreateOrConnectWithoutPeopleInput | Prisma.ExpenseCreateOrConnectWithoutPeopleInput[]
  upsert?: Prisma.ExpenseUpsertWithWhereUniqueWithoutPeopleInput | Prisma.ExpenseUpsertWithWhereUniqueWithoutPeopleInput[]
  createMany?: Prisma.ExpenseCreateManyPeopleInputEnvelope
  set?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  disconnect?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  delete?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  connect?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  update?: Prisma.ExpenseUpdateWithWhereUniqueWithoutPeopleInput | Prisma.ExpenseUpdateWithWhereUniqueWithoutPeopleInput[]
  updateMany?: Prisma.ExpenseUpdateManyWithWhereWithoutPeopleInput | Prisma.ExpenseUpdateManyWithWhereWithoutPeopleInput[]
  deleteMany?: Prisma.ExpenseScalarWhereInput | Prisma.ExpenseScalarWhereInput[]
}

export type ExpenseCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.ExpenseCreateWithoutCategoryInput, Prisma.ExpenseUncheckedCreateWithoutCategoryInput> | Prisma.ExpenseCreateWithoutCategoryInput[] | Prisma.ExpenseUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.ExpenseCreateOrConnectWithoutCategoryInput | Prisma.ExpenseCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.ExpenseCreateManyCategoryInputEnvelope
  connect?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
}

export type ExpenseUncheckedCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.ExpenseCreateWithoutCategoryInput, Prisma.ExpenseUncheckedCreateWithoutCategoryInput> | Prisma.ExpenseCreateWithoutCategoryInput[] | Prisma.ExpenseUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.ExpenseCreateOrConnectWithoutCategoryInput | Prisma.ExpenseCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.ExpenseCreateManyCategoryInputEnvelope
  connect?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
}

export type ExpenseUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.ExpenseCreateWithoutCategoryInput, Prisma.ExpenseUncheckedCreateWithoutCategoryInput> | Prisma.ExpenseCreateWithoutCategoryInput[] | Prisma.ExpenseUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.ExpenseCreateOrConnectWithoutCategoryInput | Prisma.ExpenseCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.ExpenseUpsertWithWhereUniqueWithoutCategoryInput | Prisma.ExpenseUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.ExpenseCreateManyCategoryInputEnvelope
  set?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  disconnect?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  delete?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  connect?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  update?: Prisma.ExpenseUpdateWithWhereUniqueWithoutCategoryInput | Prisma.ExpenseUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.ExpenseUpdateManyWithWhereWithoutCategoryInput | Prisma.ExpenseUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.ExpenseScalarWhereInput | Prisma.ExpenseScalarWhereInput[]
}

export type ExpenseUncheckedUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.ExpenseCreateWithoutCategoryInput, Prisma.ExpenseUncheckedCreateWithoutCategoryInput> | Prisma.ExpenseCreateWithoutCategoryInput[] | Prisma.ExpenseUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.ExpenseCreateOrConnectWithoutCategoryInput | Prisma.ExpenseCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.ExpenseUpsertWithWhereUniqueWithoutCategoryInput | Prisma.ExpenseUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.ExpenseCreateManyCategoryInputEnvelope
  set?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  disconnect?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  delete?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  connect?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  update?: Prisma.ExpenseUpdateWithWhereUniqueWithoutCategoryInput | Prisma.ExpenseUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.ExpenseUpdateManyWithWhereWithoutCategoryInput | Prisma.ExpenseUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.ExpenseScalarWhereInput | Prisma.ExpenseScalarWhereInput[]
}

export type ExpenseCreateNestedManyWithoutSubCategoryInput = {
  create?: Prisma.XOR<Prisma.ExpenseCreateWithoutSubCategoryInput, Prisma.ExpenseUncheckedCreateWithoutSubCategoryInput> | Prisma.ExpenseCreateWithoutSubCategoryInput[] | Prisma.ExpenseUncheckedCreateWithoutSubCategoryInput[]
  connectOrCreate?: Prisma.ExpenseCreateOrConnectWithoutSubCategoryInput | Prisma.ExpenseCreateOrConnectWithoutSubCategoryInput[]
  createMany?: Prisma.ExpenseCreateManySubCategoryInputEnvelope
  connect?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
}

export type ExpenseUncheckedCreateNestedManyWithoutSubCategoryInput = {
  create?: Prisma.XOR<Prisma.ExpenseCreateWithoutSubCategoryInput, Prisma.ExpenseUncheckedCreateWithoutSubCategoryInput> | Prisma.ExpenseCreateWithoutSubCategoryInput[] | Prisma.ExpenseUncheckedCreateWithoutSubCategoryInput[]
  connectOrCreate?: Prisma.ExpenseCreateOrConnectWithoutSubCategoryInput | Prisma.ExpenseCreateOrConnectWithoutSubCategoryInput[]
  createMany?: Prisma.ExpenseCreateManySubCategoryInputEnvelope
  connect?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
}

export type ExpenseUpdateManyWithoutSubCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.ExpenseCreateWithoutSubCategoryInput, Prisma.ExpenseUncheckedCreateWithoutSubCategoryInput> | Prisma.ExpenseCreateWithoutSubCategoryInput[] | Prisma.ExpenseUncheckedCreateWithoutSubCategoryInput[]
  connectOrCreate?: Prisma.ExpenseCreateOrConnectWithoutSubCategoryInput | Prisma.ExpenseCreateOrConnectWithoutSubCategoryInput[]
  upsert?: Prisma.ExpenseUpsertWithWhereUniqueWithoutSubCategoryInput | Prisma.ExpenseUpsertWithWhereUniqueWithoutSubCategoryInput[]
  createMany?: Prisma.ExpenseCreateManySubCategoryInputEnvelope
  set?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  disconnect?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  delete?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  connect?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  update?: Prisma.ExpenseUpdateWithWhereUniqueWithoutSubCategoryInput | Prisma.ExpenseUpdateWithWhereUniqueWithoutSubCategoryInput[]
  updateMany?: Prisma.ExpenseUpdateManyWithWhereWithoutSubCategoryInput | Prisma.ExpenseUpdateManyWithWhereWithoutSubCategoryInput[]
  deleteMany?: Prisma.ExpenseScalarWhereInput | Prisma.ExpenseScalarWhereInput[]
}

export type ExpenseUncheckedUpdateManyWithoutSubCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.ExpenseCreateWithoutSubCategoryInput, Prisma.ExpenseUncheckedCreateWithoutSubCategoryInput> | Prisma.ExpenseCreateWithoutSubCategoryInput[] | Prisma.ExpenseUncheckedCreateWithoutSubCategoryInput[]
  connectOrCreate?: Prisma.ExpenseCreateOrConnectWithoutSubCategoryInput | Prisma.ExpenseCreateOrConnectWithoutSubCategoryInput[]
  upsert?: Prisma.ExpenseUpsertWithWhereUniqueWithoutSubCategoryInput | Prisma.ExpenseUpsertWithWhereUniqueWithoutSubCategoryInput[]
  createMany?: Prisma.ExpenseCreateManySubCategoryInputEnvelope
  set?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  disconnect?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  delete?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  connect?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  update?: Prisma.ExpenseUpdateWithWhereUniqueWithoutSubCategoryInput | Prisma.ExpenseUpdateWithWhereUniqueWithoutSubCategoryInput[]
  updateMany?: Prisma.ExpenseUpdateManyWithWhereWithoutSubCategoryInput | Prisma.ExpenseUpdateManyWithWhereWithoutSubCategoryInput[]
  deleteMany?: Prisma.ExpenseScalarWhereInput | Prisma.ExpenseScalarWhereInput[]
}

export type ExpenseCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.ExpenseCreateWithoutProjectInput, Prisma.ExpenseUncheckedCreateWithoutProjectInput> | Prisma.ExpenseCreateWithoutProjectInput[] | Prisma.ExpenseUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ExpenseCreateOrConnectWithoutProjectInput | Prisma.ExpenseCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.ExpenseCreateManyProjectInputEnvelope
  connect?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
}

export type ExpenseUncheckedCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.ExpenseCreateWithoutProjectInput, Prisma.ExpenseUncheckedCreateWithoutProjectInput> | Prisma.ExpenseCreateWithoutProjectInput[] | Prisma.ExpenseUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ExpenseCreateOrConnectWithoutProjectInput | Prisma.ExpenseCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.ExpenseCreateManyProjectInputEnvelope
  connect?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
}

export type ExpenseUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.ExpenseCreateWithoutProjectInput, Prisma.ExpenseUncheckedCreateWithoutProjectInput> | Prisma.ExpenseCreateWithoutProjectInput[] | Prisma.ExpenseUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ExpenseCreateOrConnectWithoutProjectInput | Prisma.ExpenseCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.ExpenseUpsertWithWhereUniqueWithoutProjectInput | Prisma.ExpenseUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.ExpenseCreateManyProjectInputEnvelope
  set?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  disconnect?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  delete?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  connect?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  update?: Prisma.ExpenseUpdateWithWhereUniqueWithoutProjectInput | Prisma.ExpenseUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.ExpenseUpdateManyWithWhereWithoutProjectInput | Prisma.ExpenseUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.ExpenseScalarWhereInput | Prisma.ExpenseScalarWhereInput[]
}

export type ExpenseUncheckedUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.ExpenseCreateWithoutProjectInput, Prisma.ExpenseUncheckedCreateWithoutProjectInput> | Prisma.ExpenseCreateWithoutProjectInput[] | Prisma.ExpenseUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ExpenseCreateOrConnectWithoutProjectInput | Prisma.ExpenseCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.ExpenseUpsertWithWhereUniqueWithoutProjectInput | Prisma.ExpenseUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.ExpenseCreateManyProjectInputEnvelope
  set?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  disconnect?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  delete?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  connect?: Prisma.ExpenseWhereUniqueInput | Prisma.ExpenseWhereUniqueInput[]
  update?: Prisma.ExpenseUpdateWithWhereUniqueWithoutProjectInput | Prisma.ExpenseUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.ExpenseUpdateManyWithWhereWithoutProjectInput | Prisma.ExpenseUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.ExpenseScalarWhereInput | Prisma.ExpenseScalarWhereInput[]
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type ExpenseCreateWithoutPeopleInput = {
  expenseDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  userId: number
  created?: Date | string
  modified?: Date | string
  category?: Prisma.CategoryCreateNestedOneWithoutExpensesInput
  subCategory?: Prisma.SubCategoryCreateNestedOneWithoutExpensesInput
  project?: Prisma.ProjectCreateNestedOneWithoutExpensesInput
}

export type ExpenseUncheckedCreateWithoutPeopleInput = {
  expenseId?: number
  expenseDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  categoryId?: number | null
  subCategoryId?: number | null
  projectId?: number | null
  userId: number
  created?: Date | string
  modified?: Date | string
}

export type ExpenseCreateOrConnectWithoutPeopleInput = {
  where: Prisma.ExpenseWhereUniqueInput
  create: Prisma.XOR<Prisma.ExpenseCreateWithoutPeopleInput, Prisma.ExpenseUncheckedCreateWithoutPeopleInput>
}

export type ExpenseCreateManyPeopleInputEnvelope = {
  data: Prisma.ExpenseCreateManyPeopleInput | Prisma.ExpenseCreateManyPeopleInput[]
  skipDuplicates?: boolean
}

export type ExpenseUpsertWithWhereUniqueWithoutPeopleInput = {
  where: Prisma.ExpenseWhereUniqueInput
  update: Prisma.XOR<Prisma.ExpenseUpdateWithoutPeopleInput, Prisma.ExpenseUncheckedUpdateWithoutPeopleInput>
  create: Prisma.XOR<Prisma.ExpenseCreateWithoutPeopleInput, Prisma.ExpenseUncheckedCreateWithoutPeopleInput>
}

export type ExpenseUpdateWithWhereUniqueWithoutPeopleInput = {
  where: Prisma.ExpenseWhereUniqueInput
  data: Prisma.XOR<Prisma.ExpenseUpdateWithoutPeopleInput, Prisma.ExpenseUncheckedUpdateWithoutPeopleInput>
}

export type ExpenseUpdateManyWithWhereWithoutPeopleInput = {
  where: Prisma.ExpenseScalarWhereInput
  data: Prisma.XOR<Prisma.ExpenseUpdateManyMutationInput, Prisma.ExpenseUncheckedUpdateManyWithoutPeopleInput>
}

export type ExpenseScalarWhereInput = {
  AND?: Prisma.ExpenseScalarWhereInput | Prisma.ExpenseScalarWhereInput[]
  OR?: Prisma.ExpenseScalarWhereInput[]
  NOT?: Prisma.ExpenseScalarWhereInput | Prisma.ExpenseScalarWhereInput[]
  expenseId?: Prisma.IntFilter<"Expense"> | number
  expenseDate?: Prisma.DateTimeFilter<"Expense"> | Date | string
  amount?: Prisma.DecimalFilter<"Expense"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: Prisma.StringNullableFilter<"Expense"> | string | null
  attachmentPath?: Prisma.StringNullableFilter<"Expense"> | string | null
  description?: Prisma.StringNullableFilter<"Expense"> | string | null
  isDeleted?: Prisma.BoolFilter<"Expense"> | boolean
  categoryId?: Prisma.IntNullableFilter<"Expense"> | number | null
  subCategoryId?: Prisma.IntNullableFilter<"Expense"> | number | null
  projectId?: Prisma.IntNullableFilter<"Expense"> | number | null
  peopleId?: Prisma.IntFilter<"Expense"> | number
  userId?: Prisma.IntFilter<"Expense"> | number
  created?: Prisma.DateTimeFilter<"Expense"> | Date | string
  modified?: Prisma.DateTimeFilter<"Expense"> | Date | string
}

export type ExpenseCreateWithoutCategoryInput = {
  expenseDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  userId: number
  created?: Date | string
  modified?: Date | string
  subCategory?: Prisma.SubCategoryCreateNestedOneWithoutExpensesInput
  project?: Prisma.ProjectCreateNestedOneWithoutExpensesInput
  people: Prisma.PeopleCreateNestedOneWithoutExpensesInput
}

export type ExpenseUncheckedCreateWithoutCategoryInput = {
  expenseId?: number
  expenseDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  subCategoryId?: number | null
  projectId?: number | null
  peopleId: number
  userId: number
  created?: Date | string
  modified?: Date | string
}

export type ExpenseCreateOrConnectWithoutCategoryInput = {
  where: Prisma.ExpenseWhereUniqueInput
  create: Prisma.XOR<Prisma.ExpenseCreateWithoutCategoryInput, Prisma.ExpenseUncheckedCreateWithoutCategoryInput>
}

export type ExpenseCreateManyCategoryInputEnvelope = {
  data: Prisma.ExpenseCreateManyCategoryInput | Prisma.ExpenseCreateManyCategoryInput[]
  skipDuplicates?: boolean
}

export type ExpenseUpsertWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.ExpenseWhereUniqueInput
  update: Prisma.XOR<Prisma.ExpenseUpdateWithoutCategoryInput, Prisma.ExpenseUncheckedUpdateWithoutCategoryInput>
  create: Prisma.XOR<Prisma.ExpenseCreateWithoutCategoryInput, Prisma.ExpenseUncheckedCreateWithoutCategoryInput>
}

export type ExpenseUpdateWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.ExpenseWhereUniqueInput
  data: Prisma.XOR<Prisma.ExpenseUpdateWithoutCategoryInput, Prisma.ExpenseUncheckedUpdateWithoutCategoryInput>
}

export type ExpenseUpdateManyWithWhereWithoutCategoryInput = {
  where: Prisma.ExpenseScalarWhereInput
  data: Prisma.XOR<Prisma.ExpenseUpdateManyMutationInput, Prisma.ExpenseUncheckedUpdateManyWithoutCategoryInput>
}

export type ExpenseCreateWithoutSubCategoryInput = {
  expenseDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  userId: number
  created?: Date | string
  modified?: Date | string
  category?: Prisma.CategoryCreateNestedOneWithoutExpensesInput
  project?: Prisma.ProjectCreateNestedOneWithoutExpensesInput
  people: Prisma.PeopleCreateNestedOneWithoutExpensesInput
}

export type ExpenseUncheckedCreateWithoutSubCategoryInput = {
  expenseId?: number
  expenseDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  categoryId?: number | null
  projectId?: number | null
  peopleId: number
  userId: number
  created?: Date | string
  modified?: Date | string
}

export type ExpenseCreateOrConnectWithoutSubCategoryInput = {
  where: Prisma.ExpenseWhereUniqueInput
  create: Prisma.XOR<Prisma.ExpenseCreateWithoutSubCategoryInput, Prisma.ExpenseUncheckedCreateWithoutSubCategoryInput>
}

export type ExpenseCreateManySubCategoryInputEnvelope = {
  data: Prisma.ExpenseCreateManySubCategoryInput | Prisma.ExpenseCreateManySubCategoryInput[]
  skipDuplicates?: boolean
}

export type ExpenseUpsertWithWhereUniqueWithoutSubCategoryInput = {
  where: Prisma.ExpenseWhereUniqueInput
  update: Prisma.XOR<Prisma.ExpenseUpdateWithoutSubCategoryInput, Prisma.ExpenseUncheckedUpdateWithoutSubCategoryInput>
  create: Prisma.XOR<Prisma.ExpenseCreateWithoutSubCategoryInput, Prisma.ExpenseUncheckedCreateWithoutSubCategoryInput>
}

export type ExpenseUpdateWithWhereUniqueWithoutSubCategoryInput = {
  where: Prisma.ExpenseWhereUniqueInput
  data: Prisma.XOR<Prisma.ExpenseUpdateWithoutSubCategoryInput, Prisma.ExpenseUncheckedUpdateWithoutSubCategoryInput>
}

export type ExpenseUpdateManyWithWhereWithoutSubCategoryInput = {
  where: Prisma.ExpenseScalarWhereInput
  data: Prisma.XOR<Prisma.ExpenseUpdateManyMutationInput, Prisma.ExpenseUncheckedUpdateManyWithoutSubCategoryInput>
}

export type ExpenseCreateWithoutProjectInput = {
  expenseDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  userId: number
  created?: Date | string
  modified?: Date | string
  category?: Prisma.CategoryCreateNestedOneWithoutExpensesInput
  subCategory?: Prisma.SubCategoryCreateNestedOneWithoutExpensesInput
  people: Prisma.PeopleCreateNestedOneWithoutExpensesInput
}

export type ExpenseUncheckedCreateWithoutProjectInput = {
  expenseId?: number
  expenseDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  categoryId?: number | null
  subCategoryId?: number | null
  peopleId: number
  userId: number
  created?: Date | string
  modified?: Date | string
}

export type ExpenseCreateOrConnectWithoutProjectInput = {
  where: Prisma.ExpenseWhereUniqueInput
  create: Prisma.XOR<Prisma.ExpenseCreateWithoutProjectInput, Prisma.ExpenseUncheckedCreateWithoutProjectInput>
}

export type ExpenseCreateManyProjectInputEnvelope = {
  data: Prisma.ExpenseCreateManyProjectInput | Prisma.ExpenseCreateManyProjectInput[]
  skipDuplicates?: boolean
}

export type ExpenseUpsertWithWhereUniqueWithoutProjectInput = {
  where: Prisma.ExpenseWhereUniqueInput
  update: Prisma.XOR<Prisma.ExpenseUpdateWithoutProjectInput, Prisma.ExpenseUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.ExpenseCreateWithoutProjectInput, Prisma.ExpenseUncheckedCreateWithoutProjectInput>
}

export type ExpenseUpdateWithWhereUniqueWithoutProjectInput = {
  where: Prisma.ExpenseWhereUniqueInput
  data: Prisma.XOR<Prisma.ExpenseUpdateWithoutProjectInput, Prisma.ExpenseUncheckedUpdateWithoutProjectInput>
}

export type ExpenseUpdateManyWithWhereWithoutProjectInput = {
  where: Prisma.ExpenseScalarWhereInput
  data: Prisma.XOR<Prisma.ExpenseUpdateManyMutationInput, Prisma.ExpenseUncheckedUpdateManyWithoutProjectInput>
}

export type ExpenseCreateManyPeopleInput = {
  expenseId?: number
  expenseDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  categoryId?: number | null
  subCategoryId?: number | null
  projectId?: number | null
  userId: number
  created?: Date | string
  modified?: Date | string
}

export type ExpenseUpdateWithoutPeopleInput = {
  expenseDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  category?: Prisma.CategoryUpdateOneWithoutExpensesNestedInput
  subCategory?: Prisma.SubCategoryUpdateOneWithoutExpensesNestedInput
  project?: Prisma.ProjectUpdateOneWithoutExpensesNestedInput
}

export type ExpenseUncheckedUpdateWithoutPeopleInput = {
  expenseId?: Prisma.IntFieldUpdateOperationsInput | number
  expenseDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  categoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  subCategoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  projectId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExpenseUncheckedUpdateManyWithoutPeopleInput = {
  expenseId?: Prisma.IntFieldUpdateOperationsInput | number
  expenseDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  categoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  subCategoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  projectId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExpenseCreateManyCategoryInput = {
  expenseId?: number
  expenseDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  subCategoryId?: number | null
  projectId?: number | null
  peopleId: number
  userId: number
  created?: Date | string
  modified?: Date | string
}

export type ExpenseUpdateWithoutCategoryInput = {
  expenseDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subCategory?: Prisma.SubCategoryUpdateOneWithoutExpensesNestedInput
  project?: Prisma.ProjectUpdateOneWithoutExpensesNestedInput
  people?: Prisma.PeopleUpdateOneRequiredWithoutExpensesNestedInput
}

export type ExpenseUncheckedUpdateWithoutCategoryInput = {
  expenseId?: Prisma.IntFieldUpdateOperationsInput | number
  expenseDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  subCategoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  projectId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  peopleId?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExpenseUncheckedUpdateManyWithoutCategoryInput = {
  expenseId?: Prisma.IntFieldUpdateOperationsInput | number
  expenseDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  subCategoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  projectId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  peopleId?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExpenseCreateManySubCategoryInput = {
  expenseId?: number
  expenseDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  categoryId?: number | null
  projectId?: number | null
  peopleId: number
  userId: number
  created?: Date | string
  modified?: Date | string
}

export type ExpenseUpdateWithoutSubCategoryInput = {
  expenseDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  category?: Prisma.CategoryUpdateOneWithoutExpensesNestedInput
  project?: Prisma.ProjectUpdateOneWithoutExpensesNestedInput
  people?: Prisma.PeopleUpdateOneRequiredWithoutExpensesNestedInput
}

export type ExpenseUncheckedUpdateWithoutSubCategoryInput = {
  expenseId?: Prisma.IntFieldUpdateOperationsInput | number
  expenseDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  categoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  projectId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  peopleId?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExpenseUncheckedUpdateManyWithoutSubCategoryInput = {
  expenseId?: Prisma.IntFieldUpdateOperationsInput | number
  expenseDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  categoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  projectId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  peopleId?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExpenseCreateManyProjectInput = {
  expenseId?: number
  expenseDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  categoryId?: number | null
  subCategoryId?: number | null
  peopleId: number
  userId: number
  created?: Date | string
  modified?: Date | string
}

export type ExpenseUpdateWithoutProjectInput = {
  expenseDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  category?: Prisma.CategoryUpdateOneWithoutExpensesNestedInput
  subCategory?: Prisma.SubCategoryUpdateOneWithoutExpensesNestedInput
  people?: Prisma.PeopleUpdateOneRequiredWithoutExpensesNestedInput
}

export type ExpenseUncheckedUpdateWithoutProjectInput = {
  expenseId?: Prisma.IntFieldUpdateOperationsInput | number
  expenseDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  categoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  subCategoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  peopleId?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExpenseUncheckedUpdateManyWithoutProjectInput = {
  expenseId?: Prisma.IntFieldUpdateOperationsInput | number
  expenseDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  expenseDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  categoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  subCategoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  peopleId?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ExpenseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  expenseId?: boolean
  expenseDate?: boolean
  amount?: boolean
  expenseDetail?: boolean
  attachmentPath?: boolean
  description?: boolean
  isDeleted?: boolean
  categoryId?: boolean
  subCategoryId?: boolean
  projectId?: boolean
  peopleId?: boolean
  userId?: boolean
  created?: boolean
  modified?: boolean
  category?: boolean | Prisma.Expense$categoryArgs<ExtArgs>
  subCategory?: boolean | Prisma.Expense$subCategoryArgs<ExtArgs>
  project?: boolean | Prisma.Expense$projectArgs<ExtArgs>
  people?: boolean | Prisma.PeopleDefaultArgs<ExtArgs>
}, ExtArgs["result"]["expense"]>

export type ExpenseSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  expenseId?: boolean
  expenseDate?: boolean
  amount?: boolean
  expenseDetail?: boolean
  attachmentPath?: boolean
  description?: boolean
  isDeleted?: boolean
  categoryId?: boolean
  subCategoryId?: boolean
  projectId?: boolean
  peopleId?: boolean
  userId?: boolean
  created?: boolean
  modified?: boolean
  category?: boolean | Prisma.Expense$categoryArgs<ExtArgs>
  subCategory?: boolean | Prisma.Expense$subCategoryArgs<ExtArgs>
  project?: boolean | Prisma.Expense$projectArgs<ExtArgs>
  people?: boolean | Prisma.PeopleDefaultArgs<ExtArgs>
}, ExtArgs["result"]["expense"]>

export type ExpenseSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  expenseId?: boolean
  expenseDate?: boolean
  amount?: boolean
  expenseDetail?: boolean
  attachmentPath?: boolean
  description?: boolean
  isDeleted?: boolean
  categoryId?: boolean
  subCategoryId?: boolean
  projectId?: boolean
  peopleId?: boolean
  userId?: boolean
  created?: boolean
  modified?: boolean
  category?: boolean | Prisma.Expense$categoryArgs<ExtArgs>
  subCategory?: boolean | Prisma.Expense$subCategoryArgs<ExtArgs>
  project?: boolean | Prisma.Expense$projectArgs<ExtArgs>
  people?: boolean | Prisma.PeopleDefaultArgs<ExtArgs>
}, ExtArgs["result"]["expense"]>

export type ExpenseSelectScalar = {
  expenseId?: boolean
  expenseDate?: boolean
  amount?: boolean
  expenseDetail?: boolean
  attachmentPath?: boolean
  description?: boolean
  isDeleted?: boolean
  categoryId?: boolean
  subCategoryId?: boolean
  projectId?: boolean
  peopleId?: boolean
  userId?: boolean
  created?: boolean
  modified?: boolean
}

export type ExpenseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"expenseId" | "expenseDate" | "amount" | "expenseDetail" | "attachmentPath" | "description" | "isDeleted" | "categoryId" | "subCategoryId" | "projectId" | "peopleId" | "userId" | "created" | "modified", ExtArgs["result"]["expense"]>
export type ExpenseInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.Expense$categoryArgs<ExtArgs>
  subCategory?: boolean | Prisma.Expense$subCategoryArgs<ExtArgs>
  project?: boolean | Prisma.Expense$projectArgs<ExtArgs>
  people?: boolean | Prisma.PeopleDefaultArgs<ExtArgs>
}
export type ExpenseIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.Expense$categoryArgs<ExtArgs>
  subCategory?: boolean | Prisma.Expense$subCategoryArgs<ExtArgs>
  project?: boolean | Prisma.Expense$projectArgs<ExtArgs>
  people?: boolean | Prisma.PeopleDefaultArgs<ExtArgs>
}
export type ExpenseIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.Expense$categoryArgs<ExtArgs>
  subCategory?: boolean | Prisma.Expense$subCategoryArgs<ExtArgs>
  project?: boolean | Prisma.Expense$projectArgs<ExtArgs>
  people?: boolean | Prisma.PeopleDefaultArgs<ExtArgs>
}

export type $ExpensePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Expense"
  objects: {
    category: Prisma.$CategoryPayload<ExtArgs> | null
    subCategory: Prisma.$SubCategoryPayload<ExtArgs> | null
    project: Prisma.$ProjectPayload<ExtArgs> | null
    people: Prisma.$PeoplePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    expenseId: number
    expenseDate: Date
    amount: runtime.Decimal
    expenseDetail: string | null
    attachmentPath: string | null
    description: string | null
    isDeleted: boolean
    categoryId: number | null
    subCategoryId: number | null
    projectId: number | null
    peopleId: number
    userId: number
    created: Date
    modified: Date
  }, ExtArgs["result"]["expense"]>
  composites: {}
}

export type ExpenseGetPayload<S extends boolean | null | undefined | ExpenseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ExpensePayload, S>

export type ExpenseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ExpenseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ExpenseCountAggregateInputType | true
  }

export interface ExpenseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Expense'], meta: { name: 'Expense' } }
  /**
   * Find zero or one Expense that matches the filter.
   * @param {ExpenseFindUniqueArgs} args - Arguments to find a Expense
   * @example
   * // Get one Expense
   * const expense = await prisma.expense.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ExpenseFindUniqueArgs>(args: Prisma.SelectSubset<T, ExpenseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ExpenseClient<runtime.Types.Result.GetResult<Prisma.$ExpensePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Expense that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ExpenseFindUniqueOrThrowArgs} args - Arguments to find a Expense
   * @example
   * // Get one Expense
   * const expense = await prisma.expense.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ExpenseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ExpenseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ExpenseClient<runtime.Types.Result.GetResult<Prisma.$ExpensePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Expense that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExpenseFindFirstArgs} args - Arguments to find a Expense
   * @example
   * // Get one Expense
   * const expense = await prisma.expense.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ExpenseFindFirstArgs>(args?: Prisma.SelectSubset<T, ExpenseFindFirstArgs<ExtArgs>>): Prisma.Prisma__ExpenseClient<runtime.Types.Result.GetResult<Prisma.$ExpensePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Expense that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExpenseFindFirstOrThrowArgs} args - Arguments to find a Expense
   * @example
   * // Get one Expense
   * const expense = await prisma.expense.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ExpenseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ExpenseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ExpenseClient<runtime.Types.Result.GetResult<Prisma.$ExpensePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Expenses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExpenseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Expenses
   * const expenses = await prisma.expense.findMany()
   * 
   * // Get first 10 Expenses
   * const expenses = await prisma.expense.findMany({ take: 10 })
   * 
   * // Only select the `expenseId`
   * const expenseWithExpenseIdOnly = await prisma.expense.findMany({ select: { expenseId: true } })
   * 
   */
  findMany<T extends ExpenseFindManyArgs>(args?: Prisma.SelectSubset<T, ExpenseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExpensePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Expense.
   * @param {ExpenseCreateArgs} args - Arguments to create a Expense.
   * @example
   * // Create one Expense
   * const Expense = await prisma.expense.create({
   *   data: {
   *     // ... data to create a Expense
   *   }
   * })
   * 
   */
  create<T extends ExpenseCreateArgs>(args: Prisma.SelectSubset<T, ExpenseCreateArgs<ExtArgs>>): Prisma.Prisma__ExpenseClient<runtime.Types.Result.GetResult<Prisma.$ExpensePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Expenses.
   * @param {ExpenseCreateManyArgs} args - Arguments to create many Expenses.
   * @example
   * // Create many Expenses
   * const expense = await prisma.expense.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ExpenseCreateManyArgs>(args?: Prisma.SelectSubset<T, ExpenseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Expenses and returns the data saved in the database.
   * @param {ExpenseCreateManyAndReturnArgs} args - Arguments to create many Expenses.
   * @example
   * // Create many Expenses
   * const expense = await prisma.expense.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Expenses and only return the `expenseId`
   * const expenseWithExpenseIdOnly = await prisma.expense.createManyAndReturn({
   *   select: { expenseId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ExpenseCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ExpenseCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExpensePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Expense.
   * @param {ExpenseDeleteArgs} args - Arguments to delete one Expense.
   * @example
   * // Delete one Expense
   * const Expense = await prisma.expense.delete({
   *   where: {
   *     // ... filter to delete one Expense
   *   }
   * })
   * 
   */
  delete<T extends ExpenseDeleteArgs>(args: Prisma.SelectSubset<T, ExpenseDeleteArgs<ExtArgs>>): Prisma.Prisma__ExpenseClient<runtime.Types.Result.GetResult<Prisma.$ExpensePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Expense.
   * @param {ExpenseUpdateArgs} args - Arguments to update one Expense.
   * @example
   * // Update one Expense
   * const expense = await prisma.expense.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ExpenseUpdateArgs>(args: Prisma.SelectSubset<T, ExpenseUpdateArgs<ExtArgs>>): Prisma.Prisma__ExpenseClient<runtime.Types.Result.GetResult<Prisma.$ExpensePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Expenses.
   * @param {ExpenseDeleteManyArgs} args - Arguments to filter Expenses to delete.
   * @example
   * // Delete a few Expenses
   * const { count } = await prisma.expense.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ExpenseDeleteManyArgs>(args?: Prisma.SelectSubset<T, ExpenseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Expenses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExpenseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Expenses
   * const expense = await prisma.expense.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ExpenseUpdateManyArgs>(args: Prisma.SelectSubset<T, ExpenseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Expenses and returns the data updated in the database.
   * @param {ExpenseUpdateManyAndReturnArgs} args - Arguments to update many Expenses.
   * @example
   * // Update many Expenses
   * const expense = await prisma.expense.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Expenses and only return the `expenseId`
   * const expenseWithExpenseIdOnly = await prisma.expense.updateManyAndReturn({
   *   select: { expenseId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ExpenseUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ExpenseUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExpensePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Expense.
   * @param {ExpenseUpsertArgs} args - Arguments to update or create a Expense.
   * @example
   * // Update or create a Expense
   * const expense = await prisma.expense.upsert({
   *   create: {
   *     // ... data to create a Expense
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Expense we want to update
   *   }
   * })
   */
  upsert<T extends ExpenseUpsertArgs>(args: Prisma.SelectSubset<T, ExpenseUpsertArgs<ExtArgs>>): Prisma.Prisma__ExpenseClient<runtime.Types.Result.GetResult<Prisma.$ExpensePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Expenses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExpenseCountArgs} args - Arguments to filter Expenses to count.
   * @example
   * // Count the number of Expenses
   * const count = await prisma.expense.count({
   *   where: {
   *     // ... the filter for the Expenses we want to count
   *   }
   * })
  **/
  count<T extends ExpenseCountArgs>(
    args?: Prisma.Subset<T, ExpenseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ExpenseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Expense.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExpenseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ExpenseAggregateArgs>(args: Prisma.Subset<T, ExpenseAggregateArgs>): Prisma.PrismaPromise<GetExpenseAggregateType<T>>

  /**
   * Group by Expense.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExpenseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ExpenseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ExpenseGroupByArgs['orderBy'] }
      : { orderBy?: ExpenseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ExpenseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetExpenseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Expense model
 */
readonly fields: ExpenseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Expense.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ExpenseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  category<T extends Prisma.Expense$categoryArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Expense$categoryArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  subCategory<T extends Prisma.Expense$subCategoryArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Expense$subCategoryArgs<ExtArgs>>): Prisma.Prisma__SubCategoryClient<runtime.Types.Result.GetResult<Prisma.$SubCategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  project<T extends Prisma.Expense$projectArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Expense$projectArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  people<T extends Prisma.PeopleDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PeopleDefaultArgs<ExtArgs>>): Prisma.Prisma__PeopleClient<runtime.Types.Result.GetResult<Prisma.$PeoplePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Expense model
 */
export interface ExpenseFieldRefs {
  readonly expenseId: Prisma.FieldRef<"Expense", 'Int'>
  readonly expenseDate: Prisma.FieldRef<"Expense", 'DateTime'>
  readonly amount: Prisma.FieldRef<"Expense", 'Decimal'>
  readonly expenseDetail: Prisma.FieldRef<"Expense", 'String'>
  readonly attachmentPath: Prisma.FieldRef<"Expense", 'String'>
  readonly description: Prisma.FieldRef<"Expense", 'String'>
  readonly isDeleted: Prisma.FieldRef<"Expense", 'Boolean'>
  readonly categoryId: Prisma.FieldRef<"Expense", 'Int'>
  readonly subCategoryId: Prisma.FieldRef<"Expense", 'Int'>
  readonly projectId: Prisma.FieldRef<"Expense", 'Int'>
  readonly peopleId: Prisma.FieldRef<"Expense", 'Int'>
  readonly userId: Prisma.FieldRef<"Expense", 'Int'>
  readonly created: Prisma.FieldRef<"Expense", 'DateTime'>
  readonly modified: Prisma.FieldRef<"Expense", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Expense findUnique
 */
export type ExpenseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Expense
   */
  select?: Prisma.ExpenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Expense
   */
  omit?: Prisma.ExpenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpenseInclude<ExtArgs> | null
  /**
   * Filter, which Expense to fetch.
   */
  where: Prisma.ExpenseWhereUniqueInput
}

/**
 * Expense findUniqueOrThrow
 */
export type ExpenseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Expense
   */
  select?: Prisma.ExpenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Expense
   */
  omit?: Prisma.ExpenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpenseInclude<ExtArgs> | null
  /**
   * Filter, which Expense to fetch.
   */
  where: Prisma.ExpenseWhereUniqueInput
}

/**
 * Expense findFirst
 */
export type ExpenseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Expense
   */
  select?: Prisma.ExpenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Expense
   */
  omit?: Prisma.ExpenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpenseInclude<ExtArgs> | null
  /**
   * Filter, which Expense to fetch.
   */
  where?: Prisma.ExpenseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Expenses to fetch.
   */
  orderBy?: Prisma.ExpenseOrderByWithRelationInput | Prisma.ExpenseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Expenses.
   */
  cursor?: Prisma.ExpenseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Expenses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Expenses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Expenses.
   */
  distinct?: Prisma.ExpenseScalarFieldEnum | Prisma.ExpenseScalarFieldEnum[]
}

/**
 * Expense findFirstOrThrow
 */
export type ExpenseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Expense
   */
  select?: Prisma.ExpenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Expense
   */
  omit?: Prisma.ExpenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpenseInclude<ExtArgs> | null
  /**
   * Filter, which Expense to fetch.
   */
  where?: Prisma.ExpenseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Expenses to fetch.
   */
  orderBy?: Prisma.ExpenseOrderByWithRelationInput | Prisma.ExpenseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Expenses.
   */
  cursor?: Prisma.ExpenseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Expenses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Expenses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Expenses.
   */
  distinct?: Prisma.ExpenseScalarFieldEnum | Prisma.ExpenseScalarFieldEnum[]
}

/**
 * Expense findMany
 */
export type ExpenseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Expense
   */
  select?: Prisma.ExpenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Expense
   */
  omit?: Prisma.ExpenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpenseInclude<ExtArgs> | null
  /**
   * Filter, which Expenses to fetch.
   */
  where?: Prisma.ExpenseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Expenses to fetch.
   */
  orderBy?: Prisma.ExpenseOrderByWithRelationInput | Prisma.ExpenseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Expenses.
   */
  cursor?: Prisma.ExpenseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Expenses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Expenses.
   */
  skip?: number
  distinct?: Prisma.ExpenseScalarFieldEnum | Prisma.ExpenseScalarFieldEnum[]
}

/**
 * Expense create
 */
export type ExpenseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Expense
   */
  select?: Prisma.ExpenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Expense
   */
  omit?: Prisma.ExpenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpenseInclude<ExtArgs> | null
  /**
   * The data needed to create a Expense.
   */
  data: Prisma.XOR<Prisma.ExpenseCreateInput, Prisma.ExpenseUncheckedCreateInput>
}

/**
 * Expense createMany
 */
export type ExpenseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Expenses.
   */
  data: Prisma.ExpenseCreateManyInput | Prisma.ExpenseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Expense createManyAndReturn
 */
export type ExpenseCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Expense
   */
  select?: Prisma.ExpenseSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Expense
   */
  omit?: Prisma.ExpenseOmit<ExtArgs> | null
  /**
   * The data used to create many Expenses.
   */
  data: Prisma.ExpenseCreateManyInput | Prisma.ExpenseCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpenseIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Expense update
 */
export type ExpenseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Expense
   */
  select?: Prisma.ExpenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Expense
   */
  omit?: Prisma.ExpenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpenseInclude<ExtArgs> | null
  /**
   * The data needed to update a Expense.
   */
  data: Prisma.XOR<Prisma.ExpenseUpdateInput, Prisma.ExpenseUncheckedUpdateInput>
  /**
   * Choose, which Expense to update.
   */
  where: Prisma.ExpenseWhereUniqueInput
}

/**
 * Expense updateMany
 */
export type ExpenseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Expenses.
   */
  data: Prisma.XOR<Prisma.ExpenseUpdateManyMutationInput, Prisma.ExpenseUncheckedUpdateManyInput>
  /**
   * Filter which Expenses to update
   */
  where?: Prisma.ExpenseWhereInput
  /**
   * Limit how many Expenses to update.
   */
  limit?: number
}

/**
 * Expense updateManyAndReturn
 */
export type ExpenseUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Expense
   */
  select?: Prisma.ExpenseSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Expense
   */
  omit?: Prisma.ExpenseOmit<ExtArgs> | null
  /**
   * The data used to update Expenses.
   */
  data: Prisma.XOR<Prisma.ExpenseUpdateManyMutationInput, Prisma.ExpenseUncheckedUpdateManyInput>
  /**
   * Filter which Expenses to update
   */
  where?: Prisma.ExpenseWhereInput
  /**
   * Limit how many Expenses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpenseIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Expense upsert
 */
export type ExpenseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Expense
   */
  select?: Prisma.ExpenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Expense
   */
  omit?: Prisma.ExpenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpenseInclude<ExtArgs> | null
  /**
   * The filter to search for the Expense to update in case it exists.
   */
  where: Prisma.ExpenseWhereUniqueInput
  /**
   * In case the Expense found by the `where` argument doesn't exist, create a new Expense with this data.
   */
  create: Prisma.XOR<Prisma.ExpenseCreateInput, Prisma.ExpenseUncheckedCreateInput>
  /**
   * In case the Expense was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ExpenseUpdateInput, Prisma.ExpenseUncheckedUpdateInput>
}

/**
 * Expense delete
 */
export type ExpenseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Expense
   */
  select?: Prisma.ExpenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Expense
   */
  omit?: Prisma.ExpenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpenseInclude<ExtArgs> | null
  /**
   * Filter which Expense to delete.
   */
  where: Prisma.ExpenseWhereUniqueInput
}

/**
 * Expense deleteMany
 */
export type ExpenseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Expenses to delete
   */
  where?: Prisma.ExpenseWhereInput
  /**
   * Limit how many Expenses to delete.
   */
  limit?: number
}

/**
 * Expense.category
 */
export type Expense$categoryArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
  where?: Prisma.CategoryWhereInput
}

/**
 * Expense.subCategory
 */
export type Expense$subCategoryArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubCategory
   */
  select?: Prisma.SubCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubCategory
   */
  omit?: Prisma.SubCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubCategoryInclude<ExtArgs> | null
  where?: Prisma.SubCategoryWhereInput
}

/**
 * Expense.project
 */
export type Expense$projectArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  where?: Prisma.ProjectWhereInput
}

/**
 * Expense without action
 */
export type ExpenseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Expense
   */
  select?: Prisma.ExpenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Expense
   */
  omit?: Prisma.ExpenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpenseInclude<ExtArgs> | null
}
