
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Income` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Income
 * 
 */
export type IncomeModel = runtime.Types.Result.DefaultSelection<Prisma.$IncomePayload>

export type AggregateIncome = {
  _count: IncomeCountAggregateOutputType | null
  _avg: IncomeAvgAggregateOutputType | null
  _sum: IncomeSumAggregateOutputType | null
  _min: IncomeMinAggregateOutputType | null
  _max: IncomeMaxAggregateOutputType | null
}

export type IncomeAvgAggregateOutputType = {
  incomeId: number | null
  amount: runtime.Decimal | null
  categoryId: number | null
  subCategoryId: number | null
  projectId: number | null
  peopleId: number | null
  userId: number | null
}

export type IncomeSumAggregateOutputType = {
  incomeId: number | null
  amount: runtime.Decimal | null
  categoryId: number | null
  subCategoryId: number | null
  projectId: number | null
  peopleId: number | null
  userId: number | null
}

export type IncomeMinAggregateOutputType = {
  incomeId: number | null
  incomeDate: Date | null
  amount: runtime.Decimal | null
  incomeDetail: string | null
  attachmentPath: string | null
  description: string | null
  isDeleted: boolean | null
  categoryId: number | null
  subCategoryId: number | null
  projectId: number | null
  peopleId: number | null
  userId: number | null
  created: Date | null
  modified: Date | null
}

export type IncomeMaxAggregateOutputType = {
  incomeId: number | null
  incomeDate: Date | null
  amount: runtime.Decimal | null
  incomeDetail: string | null
  attachmentPath: string | null
  description: string | null
  isDeleted: boolean | null
  categoryId: number | null
  subCategoryId: number | null
  projectId: number | null
  peopleId: number | null
  userId: number | null
  created: Date | null
  modified: Date | null
}

export type IncomeCountAggregateOutputType = {
  incomeId: number
  incomeDate: number
  amount: number
  incomeDetail: number
  attachmentPath: number
  description: number
  isDeleted: number
  categoryId: number
  subCategoryId: number
  projectId: number
  peopleId: number
  userId: number
  created: number
  modified: number
  _all: number
}


export type IncomeAvgAggregateInputType = {
  incomeId?: true
  amount?: true
  categoryId?: true
  subCategoryId?: true
  projectId?: true
  peopleId?: true
  userId?: true
}

export type IncomeSumAggregateInputType = {
  incomeId?: true
  amount?: true
  categoryId?: true
  subCategoryId?: true
  projectId?: true
  peopleId?: true
  userId?: true
}

export type IncomeMinAggregateInputType = {
  incomeId?: true
  incomeDate?: true
  amount?: true
  incomeDetail?: true
  attachmentPath?: true
  description?: true
  isDeleted?: true
  categoryId?: true
  subCategoryId?: true
  projectId?: true
  peopleId?: true
  userId?: true
  created?: true
  modified?: true
}

export type IncomeMaxAggregateInputType = {
  incomeId?: true
  incomeDate?: true
  amount?: true
  incomeDetail?: true
  attachmentPath?: true
  description?: true
  isDeleted?: true
  categoryId?: true
  subCategoryId?: true
  projectId?: true
  peopleId?: true
  userId?: true
  created?: true
  modified?: true
}

export type IncomeCountAggregateInputType = {
  incomeId?: true
  incomeDate?: true
  amount?: true
  incomeDetail?: true
  attachmentPath?: true
  description?: true
  isDeleted?: true
  categoryId?: true
  subCategoryId?: true
  projectId?: true
  peopleId?: true
  userId?: true
  created?: true
  modified?: true
  _all?: true
}

export type IncomeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Income to aggregate.
   */
  where?: Prisma.IncomeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Incomes to fetch.
   */
  orderBy?: Prisma.IncomeOrderByWithRelationInput | Prisma.IncomeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.IncomeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Incomes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Incomes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Incomes
  **/
  _count?: true | IncomeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: IncomeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: IncomeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: IncomeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: IncomeMaxAggregateInputType
}

export type GetIncomeAggregateType<T extends IncomeAggregateArgs> = {
      [P in keyof T & keyof AggregateIncome]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateIncome[P]>
    : Prisma.GetScalarType<T[P], AggregateIncome[P]>
}




export type IncomeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.IncomeWhereInput
  orderBy?: Prisma.IncomeOrderByWithAggregationInput | Prisma.IncomeOrderByWithAggregationInput[]
  by: Prisma.IncomeScalarFieldEnum[] | Prisma.IncomeScalarFieldEnum
  having?: Prisma.IncomeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: IncomeCountAggregateInputType | true
  _avg?: IncomeAvgAggregateInputType
  _sum?: IncomeSumAggregateInputType
  _min?: IncomeMinAggregateInputType
  _max?: IncomeMaxAggregateInputType
}

export type IncomeGroupByOutputType = {
  incomeId: number
  incomeDate: Date
  amount: runtime.Decimal
  incomeDetail: string | null
  attachmentPath: string | null
  description: string | null
  isDeleted: boolean
  categoryId: number | null
  subCategoryId: number | null
  projectId: number | null
  peopleId: number
  userId: number
  created: Date
  modified: Date
  _count: IncomeCountAggregateOutputType | null
  _avg: IncomeAvgAggregateOutputType | null
  _sum: IncomeSumAggregateOutputType | null
  _min: IncomeMinAggregateOutputType | null
  _max: IncomeMaxAggregateOutputType | null
}

type GetIncomeGroupByPayload<T extends IncomeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<IncomeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof IncomeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], IncomeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], IncomeGroupByOutputType[P]>
      }
    >
  >



export type IncomeWhereInput = {
  AND?: Prisma.IncomeWhereInput | Prisma.IncomeWhereInput[]
  OR?: Prisma.IncomeWhereInput[]
  NOT?: Prisma.IncomeWhereInput | Prisma.IncomeWhereInput[]
  incomeId?: Prisma.IntFilter<"Income"> | number
  incomeDate?: Prisma.DateTimeFilter<"Income"> | Date | string
  amount?: Prisma.DecimalFilter<"Income"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: Prisma.StringNullableFilter<"Income"> | string | null
  attachmentPath?: Prisma.StringNullableFilter<"Income"> | string | null
  description?: Prisma.StringNullableFilter<"Income"> | string | null
  isDeleted?: Prisma.BoolFilter<"Income"> | boolean
  categoryId?: Prisma.IntNullableFilter<"Income"> | number | null
  subCategoryId?: Prisma.IntNullableFilter<"Income"> | number | null
  projectId?: Prisma.IntNullableFilter<"Income"> | number | null
  peopleId?: Prisma.IntFilter<"Income"> | number
  userId?: Prisma.IntFilter<"Income"> | number
  created?: Prisma.DateTimeFilter<"Income"> | Date | string
  modified?: Prisma.DateTimeFilter<"Income"> | Date | string
  category?: Prisma.XOR<Prisma.CategoryNullableScalarRelationFilter, Prisma.CategoryWhereInput> | null
  subCategory?: Prisma.XOR<Prisma.SubCategoryNullableScalarRelationFilter, Prisma.SubCategoryWhereInput> | null
  project?: Prisma.XOR<Prisma.ProjectNullableScalarRelationFilter, Prisma.ProjectWhereInput> | null
  people?: Prisma.XOR<Prisma.PeopleScalarRelationFilter, Prisma.PeopleWhereInput>
}

export type IncomeOrderByWithRelationInput = {
  incomeId?: Prisma.SortOrder
  incomeDate?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  incomeDetail?: Prisma.SortOrderInput | Prisma.SortOrder
  attachmentPath?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  categoryId?: Prisma.SortOrderInput | Prisma.SortOrder
  subCategoryId?: Prisma.SortOrderInput | Prisma.SortOrder
  projectId?: Prisma.SortOrderInput | Prisma.SortOrder
  peopleId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  created?: Prisma.SortOrder
  modified?: Prisma.SortOrder
  category?: Prisma.CategoryOrderByWithRelationInput
  subCategory?: Prisma.SubCategoryOrderByWithRelationInput
  project?: Prisma.ProjectOrderByWithRelationInput
  people?: Prisma.PeopleOrderByWithRelationInput
}

export type IncomeWhereUniqueInput = Prisma.AtLeast<{
  incomeId?: number
  AND?: Prisma.IncomeWhereInput | Prisma.IncomeWhereInput[]
  OR?: Prisma.IncomeWhereInput[]
  NOT?: Prisma.IncomeWhereInput | Prisma.IncomeWhereInput[]
  incomeDate?: Prisma.DateTimeFilter<"Income"> | Date | string
  amount?: Prisma.DecimalFilter<"Income"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: Prisma.StringNullableFilter<"Income"> | string | null
  attachmentPath?: Prisma.StringNullableFilter<"Income"> | string | null
  description?: Prisma.StringNullableFilter<"Income"> | string | null
  isDeleted?: Prisma.BoolFilter<"Income"> | boolean
  categoryId?: Prisma.IntNullableFilter<"Income"> | number | null
  subCategoryId?: Prisma.IntNullableFilter<"Income"> | number | null
  projectId?: Prisma.IntNullableFilter<"Income"> | number | null
  peopleId?: Prisma.IntFilter<"Income"> | number
  userId?: Prisma.IntFilter<"Income"> | number
  created?: Prisma.DateTimeFilter<"Income"> | Date | string
  modified?: Prisma.DateTimeFilter<"Income"> | Date | string
  category?: Prisma.XOR<Prisma.CategoryNullableScalarRelationFilter, Prisma.CategoryWhereInput> | null
  subCategory?: Prisma.XOR<Prisma.SubCategoryNullableScalarRelationFilter, Prisma.SubCategoryWhereInput> | null
  project?: Prisma.XOR<Prisma.ProjectNullableScalarRelationFilter, Prisma.ProjectWhereInput> | null
  people?: Prisma.XOR<Prisma.PeopleScalarRelationFilter, Prisma.PeopleWhereInput>
}, "incomeId">

export type IncomeOrderByWithAggregationInput = {
  incomeId?: Prisma.SortOrder
  incomeDate?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  incomeDetail?: Prisma.SortOrderInput | Prisma.SortOrder
  attachmentPath?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  categoryId?: Prisma.SortOrderInput | Prisma.SortOrder
  subCategoryId?: Prisma.SortOrderInput | Prisma.SortOrder
  projectId?: Prisma.SortOrderInput | Prisma.SortOrder
  peopleId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  created?: Prisma.SortOrder
  modified?: Prisma.SortOrder
  _count?: Prisma.IncomeCountOrderByAggregateInput
  _avg?: Prisma.IncomeAvgOrderByAggregateInput
  _max?: Prisma.IncomeMaxOrderByAggregateInput
  _min?: Prisma.IncomeMinOrderByAggregateInput
  _sum?: Prisma.IncomeSumOrderByAggregateInput
}

export type IncomeScalarWhereWithAggregatesInput = {
  AND?: Prisma.IncomeScalarWhereWithAggregatesInput | Prisma.IncomeScalarWhereWithAggregatesInput[]
  OR?: Prisma.IncomeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.IncomeScalarWhereWithAggregatesInput | Prisma.IncomeScalarWhereWithAggregatesInput[]
  incomeId?: Prisma.IntWithAggregatesFilter<"Income"> | number
  incomeDate?: Prisma.DateTimeWithAggregatesFilter<"Income"> | Date | string
  amount?: Prisma.DecimalWithAggregatesFilter<"Income"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: Prisma.StringNullableWithAggregatesFilter<"Income"> | string | null
  attachmentPath?: Prisma.StringNullableWithAggregatesFilter<"Income"> | string | null
  description?: Prisma.StringNullableWithAggregatesFilter<"Income"> | string | null
  isDeleted?: Prisma.BoolWithAggregatesFilter<"Income"> | boolean
  categoryId?: Prisma.IntNullableWithAggregatesFilter<"Income"> | number | null
  subCategoryId?: Prisma.IntNullableWithAggregatesFilter<"Income"> | number | null
  projectId?: Prisma.IntNullableWithAggregatesFilter<"Income"> | number | null
  peopleId?: Prisma.IntWithAggregatesFilter<"Income"> | number
  userId?: Prisma.IntWithAggregatesFilter<"Income"> | number
  created?: Prisma.DateTimeWithAggregatesFilter<"Income"> | Date | string
  modified?: Prisma.DateTimeWithAggregatesFilter<"Income"> | Date | string
}

export type IncomeCreateInput = {
  incomeDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  userId: number
  created?: Date | string
  modified?: Date | string
  category?: Prisma.CategoryCreateNestedOneWithoutIncomesInput
  subCategory?: Prisma.SubCategoryCreateNestedOneWithoutIncomesInput
  project?: Prisma.ProjectCreateNestedOneWithoutIncomesInput
  people: Prisma.PeopleCreateNestedOneWithoutIncomesInput
}

export type IncomeUncheckedCreateInput = {
  incomeId?: number
  incomeDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  categoryId?: number | null
  subCategoryId?: number | null
  projectId?: number | null
  peopleId: number
  userId: number
  created?: Date | string
  modified?: Date | string
}

export type IncomeUpdateInput = {
  incomeDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  category?: Prisma.CategoryUpdateOneWithoutIncomesNestedInput
  subCategory?: Prisma.SubCategoryUpdateOneWithoutIncomesNestedInput
  project?: Prisma.ProjectUpdateOneWithoutIncomesNestedInput
  people?: Prisma.PeopleUpdateOneRequiredWithoutIncomesNestedInput
}

export type IncomeUncheckedUpdateInput = {
  incomeId?: Prisma.IntFieldUpdateOperationsInput | number
  incomeDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  categoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  subCategoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  projectId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  peopleId?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IncomeCreateManyInput = {
  incomeId?: number
  incomeDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  categoryId?: number | null
  subCategoryId?: number | null
  projectId?: number | null
  peopleId: number
  userId: number
  created?: Date | string
  modified?: Date | string
}

export type IncomeUpdateManyMutationInput = {
  incomeDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IncomeUncheckedUpdateManyInput = {
  incomeId?: Prisma.IntFieldUpdateOperationsInput | number
  incomeDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  categoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  subCategoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  projectId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  peopleId?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IncomeListRelationFilter = {
  every?: Prisma.IncomeWhereInput
  some?: Prisma.IncomeWhereInput
  none?: Prisma.IncomeWhereInput
}

export type IncomeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type IncomeCountOrderByAggregateInput = {
  incomeId?: Prisma.SortOrder
  incomeDate?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  incomeDetail?: Prisma.SortOrder
  attachmentPath?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  subCategoryId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  peopleId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  created?: Prisma.SortOrder
  modified?: Prisma.SortOrder
}

export type IncomeAvgOrderByAggregateInput = {
  incomeId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  subCategoryId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  peopleId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type IncomeMaxOrderByAggregateInput = {
  incomeId?: Prisma.SortOrder
  incomeDate?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  incomeDetail?: Prisma.SortOrder
  attachmentPath?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  subCategoryId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  peopleId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  created?: Prisma.SortOrder
  modified?: Prisma.SortOrder
}

export type IncomeMinOrderByAggregateInput = {
  incomeId?: Prisma.SortOrder
  incomeDate?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  incomeDetail?: Prisma.SortOrder
  attachmentPath?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  subCategoryId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  peopleId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  created?: Prisma.SortOrder
  modified?: Prisma.SortOrder
}

export type IncomeSumOrderByAggregateInput = {
  incomeId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  subCategoryId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  peopleId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type IncomeCreateNestedManyWithoutPeopleInput = {
  create?: Prisma.XOR<Prisma.IncomeCreateWithoutPeopleInput, Prisma.IncomeUncheckedCreateWithoutPeopleInput> | Prisma.IncomeCreateWithoutPeopleInput[] | Prisma.IncomeUncheckedCreateWithoutPeopleInput[]
  connectOrCreate?: Prisma.IncomeCreateOrConnectWithoutPeopleInput | Prisma.IncomeCreateOrConnectWithoutPeopleInput[]
  createMany?: Prisma.IncomeCreateManyPeopleInputEnvelope
  connect?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
}

export type IncomeUncheckedCreateNestedManyWithoutPeopleInput = {
  create?: Prisma.XOR<Prisma.IncomeCreateWithoutPeopleInput, Prisma.IncomeUncheckedCreateWithoutPeopleInput> | Prisma.IncomeCreateWithoutPeopleInput[] | Prisma.IncomeUncheckedCreateWithoutPeopleInput[]
  connectOrCreate?: Prisma.IncomeCreateOrConnectWithoutPeopleInput | Prisma.IncomeCreateOrConnectWithoutPeopleInput[]
  createMany?: Prisma.IncomeCreateManyPeopleInputEnvelope
  connect?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
}

export type IncomeUpdateManyWithoutPeopleNestedInput = {
  create?: Prisma.XOR<Prisma.IncomeCreateWithoutPeopleInput, Prisma.IncomeUncheckedCreateWithoutPeopleInput> | Prisma.IncomeCreateWithoutPeopleInput[] | Prisma.IncomeUncheckedCreateWithoutPeopleInput[]
  connectOrCreate?: Prisma.IncomeCreateOrConnectWithoutPeopleInput | Prisma.IncomeCreateOrConnectWithoutPeopleInput[]
  upsert?: Prisma.IncomeUpsertWithWhereUniqueWithoutPeopleInput | Prisma.IncomeUpsertWithWhereUniqueWithoutPeopleInput[]
  createMany?: Prisma.IncomeCreateManyPeopleInputEnvelope
  set?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  disconnect?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  delete?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  connect?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  update?: Prisma.IncomeUpdateWithWhereUniqueWithoutPeopleInput | Prisma.IncomeUpdateWithWhereUniqueWithoutPeopleInput[]
  updateMany?: Prisma.IncomeUpdateManyWithWhereWithoutPeopleInput | Prisma.IncomeUpdateManyWithWhereWithoutPeopleInput[]
  deleteMany?: Prisma.IncomeScalarWhereInput | Prisma.IncomeScalarWhereInput[]
}

export type IncomeUncheckedUpdateManyWithoutPeopleNestedInput = {
  create?: Prisma.XOR<Prisma.IncomeCreateWithoutPeopleInput, Prisma.IncomeUncheckedCreateWithoutPeopleInput> | Prisma.IncomeCreateWithoutPeopleInput[] | Prisma.IncomeUncheckedCreateWithoutPeopleInput[]
  connectOrCreate?: Prisma.IncomeCreateOrConnectWithoutPeopleInput | Prisma.IncomeCreateOrConnectWithoutPeopleInput[]
  upsert?: Prisma.IncomeUpsertWithWhereUniqueWithoutPeopleInput | Prisma.IncomeUpsertWithWhereUniqueWithoutPeopleInput[]
  createMany?: Prisma.IncomeCreateManyPeopleInputEnvelope
  set?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  disconnect?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  delete?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  connect?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  update?: Prisma.IncomeUpdateWithWhereUniqueWithoutPeopleInput | Prisma.IncomeUpdateWithWhereUniqueWithoutPeopleInput[]
  updateMany?: Prisma.IncomeUpdateManyWithWhereWithoutPeopleInput | Prisma.IncomeUpdateManyWithWhereWithoutPeopleInput[]
  deleteMany?: Prisma.IncomeScalarWhereInput | Prisma.IncomeScalarWhereInput[]
}

export type IncomeCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.IncomeCreateWithoutCategoryInput, Prisma.IncomeUncheckedCreateWithoutCategoryInput> | Prisma.IncomeCreateWithoutCategoryInput[] | Prisma.IncomeUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.IncomeCreateOrConnectWithoutCategoryInput | Prisma.IncomeCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.IncomeCreateManyCategoryInputEnvelope
  connect?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
}

export type IncomeUncheckedCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.IncomeCreateWithoutCategoryInput, Prisma.IncomeUncheckedCreateWithoutCategoryInput> | Prisma.IncomeCreateWithoutCategoryInput[] | Prisma.IncomeUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.IncomeCreateOrConnectWithoutCategoryInput | Prisma.IncomeCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.IncomeCreateManyCategoryInputEnvelope
  connect?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
}

export type IncomeUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.IncomeCreateWithoutCategoryInput, Prisma.IncomeUncheckedCreateWithoutCategoryInput> | Prisma.IncomeCreateWithoutCategoryInput[] | Prisma.IncomeUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.IncomeCreateOrConnectWithoutCategoryInput | Prisma.IncomeCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.IncomeUpsertWithWhereUniqueWithoutCategoryInput | Prisma.IncomeUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.IncomeCreateManyCategoryInputEnvelope
  set?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  disconnect?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  delete?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  connect?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  update?: Prisma.IncomeUpdateWithWhereUniqueWithoutCategoryInput | Prisma.IncomeUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.IncomeUpdateManyWithWhereWithoutCategoryInput | Prisma.IncomeUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.IncomeScalarWhereInput | Prisma.IncomeScalarWhereInput[]
}

export type IncomeUncheckedUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.IncomeCreateWithoutCategoryInput, Prisma.IncomeUncheckedCreateWithoutCategoryInput> | Prisma.IncomeCreateWithoutCategoryInput[] | Prisma.IncomeUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.IncomeCreateOrConnectWithoutCategoryInput | Prisma.IncomeCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.IncomeUpsertWithWhereUniqueWithoutCategoryInput | Prisma.IncomeUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.IncomeCreateManyCategoryInputEnvelope
  set?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  disconnect?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  delete?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  connect?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  update?: Prisma.IncomeUpdateWithWhereUniqueWithoutCategoryInput | Prisma.IncomeUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.IncomeUpdateManyWithWhereWithoutCategoryInput | Prisma.IncomeUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.IncomeScalarWhereInput | Prisma.IncomeScalarWhereInput[]
}

export type IncomeCreateNestedManyWithoutSubCategoryInput = {
  create?: Prisma.XOR<Prisma.IncomeCreateWithoutSubCategoryInput, Prisma.IncomeUncheckedCreateWithoutSubCategoryInput> | Prisma.IncomeCreateWithoutSubCategoryInput[] | Prisma.IncomeUncheckedCreateWithoutSubCategoryInput[]
  connectOrCreate?: Prisma.IncomeCreateOrConnectWithoutSubCategoryInput | Prisma.IncomeCreateOrConnectWithoutSubCategoryInput[]
  createMany?: Prisma.IncomeCreateManySubCategoryInputEnvelope
  connect?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
}

export type IncomeUncheckedCreateNestedManyWithoutSubCategoryInput = {
  create?: Prisma.XOR<Prisma.IncomeCreateWithoutSubCategoryInput, Prisma.IncomeUncheckedCreateWithoutSubCategoryInput> | Prisma.IncomeCreateWithoutSubCategoryInput[] | Prisma.IncomeUncheckedCreateWithoutSubCategoryInput[]
  connectOrCreate?: Prisma.IncomeCreateOrConnectWithoutSubCategoryInput | Prisma.IncomeCreateOrConnectWithoutSubCategoryInput[]
  createMany?: Prisma.IncomeCreateManySubCategoryInputEnvelope
  connect?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
}

export type IncomeUpdateManyWithoutSubCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.IncomeCreateWithoutSubCategoryInput, Prisma.IncomeUncheckedCreateWithoutSubCategoryInput> | Prisma.IncomeCreateWithoutSubCategoryInput[] | Prisma.IncomeUncheckedCreateWithoutSubCategoryInput[]
  connectOrCreate?: Prisma.IncomeCreateOrConnectWithoutSubCategoryInput | Prisma.IncomeCreateOrConnectWithoutSubCategoryInput[]
  upsert?: Prisma.IncomeUpsertWithWhereUniqueWithoutSubCategoryInput | Prisma.IncomeUpsertWithWhereUniqueWithoutSubCategoryInput[]
  createMany?: Prisma.IncomeCreateManySubCategoryInputEnvelope
  set?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  disconnect?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  delete?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  connect?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  update?: Prisma.IncomeUpdateWithWhereUniqueWithoutSubCategoryInput | Prisma.IncomeUpdateWithWhereUniqueWithoutSubCategoryInput[]
  updateMany?: Prisma.IncomeUpdateManyWithWhereWithoutSubCategoryInput | Prisma.IncomeUpdateManyWithWhereWithoutSubCategoryInput[]
  deleteMany?: Prisma.IncomeScalarWhereInput | Prisma.IncomeScalarWhereInput[]
}

export type IncomeUncheckedUpdateManyWithoutSubCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.IncomeCreateWithoutSubCategoryInput, Prisma.IncomeUncheckedCreateWithoutSubCategoryInput> | Prisma.IncomeCreateWithoutSubCategoryInput[] | Prisma.IncomeUncheckedCreateWithoutSubCategoryInput[]
  connectOrCreate?: Prisma.IncomeCreateOrConnectWithoutSubCategoryInput | Prisma.IncomeCreateOrConnectWithoutSubCategoryInput[]
  upsert?: Prisma.IncomeUpsertWithWhereUniqueWithoutSubCategoryInput | Prisma.IncomeUpsertWithWhereUniqueWithoutSubCategoryInput[]
  createMany?: Prisma.IncomeCreateManySubCategoryInputEnvelope
  set?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  disconnect?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  delete?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  connect?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  update?: Prisma.IncomeUpdateWithWhereUniqueWithoutSubCategoryInput | Prisma.IncomeUpdateWithWhereUniqueWithoutSubCategoryInput[]
  updateMany?: Prisma.IncomeUpdateManyWithWhereWithoutSubCategoryInput | Prisma.IncomeUpdateManyWithWhereWithoutSubCategoryInput[]
  deleteMany?: Prisma.IncomeScalarWhereInput | Prisma.IncomeScalarWhereInput[]
}

export type IncomeCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.IncomeCreateWithoutProjectInput, Prisma.IncomeUncheckedCreateWithoutProjectInput> | Prisma.IncomeCreateWithoutProjectInput[] | Prisma.IncomeUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.IncomeCreateOrConnectWithoutProjectInput | Prisma.IncomeCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.IncomeCreateManyProjectInputEnvelope
  connect?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
}

export type IncomeUncheckedCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.IncomeCreateWithoutProjectInput, Prisma.IncomeUncheckedCreateWithoutProjectInput> | Prisma.IncomeCreateWithoutProjectInput[] | Prisma.IncomeUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.IncomeCreateOrConnectWithoutProjectInput | Prisma.IncomeCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.IncomeCreateManyProjectInputEnvelope
  connect?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
}

export type IncomeUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.IncomeCreateWithoutProjectInput, Prisma.IncomeUncheckedCreateWithoutProjectInput> | Prisma.IncomeCreateWithoutProjectInput[] | Prisma.IncomeUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.IncomeCreateOrConnectWithoutProjectInput | Prisma.IncomeCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.IncomeUpsertWithWhereUniqueWithoutProjectInput | Prisma.IncomeUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.IncomeCreateManyProjectInputEnvelope
  set?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  disconnect?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  delete?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  connect?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  update?: Prisma.IncomeUpdateWithWhereUniqueWithoutProjectInput | Prisma.IncomeUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.IncomeUpdateManyWithWhereWithoutProjectInput | Prisma.IncomeUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.IncomeScalarWhereInput | Prisma.IncomeScalarWhereInput[]
}

export type IncomeUncheckedUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.IncomeCreateWithoutProjectInput, Prisma.IncomeUncheckedCreateWithoutProjectInput> | Prisma.IncomeCreateWithoutProjectInput[] | Prisma.IncomeUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.IncomeCreateOrConnectWithoutProjectInput | Prisma.IncomeCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.IncomeUpsertWithWhereUniqueWithoutProjectInput | Prisma.IncomeUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.IncomeCreateManyProjectInputEnvelope
  set?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  disconnect?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  delete?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  connect?: Prisma.IncomeWhereUniqueInput | Prisma.IncomeWhereUniqueInput[]
  update?: Prisma.IncomeUpdateWithWhereUniqueWithoutProjectInput | Prisma.IncomeUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.IncomeUpdateManyWithWhereWithoutProjectInput | Prisma.IncomeUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.IncomeScalarWhereInput | Prisma.IncomeScalarWhereInput[]
}

export type IncomeCreateWithoutPeopleInput = {
  incomeDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  userId: number
  created?: Date | string
  modified?: Date | string
  category?: Prisma.CategoryCreateNestedOneWithoutIncomesInput
  subCategory?: Prisma.SubCategoryCreateNestedOneWithoutIncomesInput
  project?: Prisma.ProjectCreateNestedOneWithoutIncomesInput
}

export type IncomeUncheckedCreateWithoutPeopleInput = {
  incomeId?: number
  incomeDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  categoryId?: number | null
  subCategoryId?: number | null
  projectId?: number | null
  userId: number
  created?: Date | string
  modified?: Date | string
}

export type IncomeCreateOrConnectWithoutPeopleInput = {
  where: Prisma.IncomeWhereUniqueInput
  create: Prisma.XOR<Prisma.IncomeCreateWithoutPeopleInput, Prisma.IncomeUncheckedCreateWithoutPeopleInput>
}

export type IncomeCreateManyPeopleInputEnvelope = {
  data: Prisma.IncomeCreateManyPeopleInput | Prisma.IncomeCreateManyPeopleInput[]
  skipDuplicates?: boolean
}

export type IncomeUpsertWithWhereUniqueWithoutPeopleInput = {
  where: Prisma.IncomeWhereUniqueInput
  update: Prisma.XOR<Prisma.IncomeUpdateWithoutPeopleInput, Prisma.IncomeUncheckedUpdateWithoutPeopleInput>
  create: Prisma.XOR<Prisma.IncomeCreateWithoutPeopleInput, Prisma.IncomeUncheckedCreateWithoutPeopleInput>
}

export type IncomeUpdateWithWhereUniqueWithoutPeopleInput = {
  where: Prisma.IncomeWhereUniqueInput
  data: Prisma.XOR<Prisma.IncomeUpdateWithoutPeopleInput, Prisma.IncomeUncheckedUpdateWithoutPeopleInput>
}

export type IncomeUpdateManyWithWhereWithoutPeopleInput = {
  where: Prisma.IncomeScalarWhereInput
  data: Prisma.XOR<Prisma.IncomeUpdateManyMutationInput, Prisma.IncomeUncheckedUpdateManyWithoutPeopleInput>
}

export type IncomeScalarWhereInput = {
  AND?: Prisma.IncomeScalarWhereInput | Prisma.IncomeScalarWhereInput[]
  OR?: Prisma.IncomeScalarWhereInput[]
  NOT?: Prisma.IncomeScalarWhereInput | Prisma.IncomeScalarWhereInput[]
  incomeId?: Prisma.IntFilter<"Income"> | number
  incomeDate?: Prisma.DateTimeFilter<"Income"> | Date | string
  amount?: Prisma.DecimalFilter<"Income"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: Prisma.StringNullableFilter<"Income"> | string | null
  attachmentPath?: Prisma.StringNullableFilter<"Income"> | string | null
  description?: Prisma.StringNullableFilter<"Income"> | string | null
  isDeleted?: Prisma.BoolFilter<"Income"> | boolean
  categoryId?: Prisma.IntNullableFilter<"Income"> | number | null
  subCategoryId?: Prisma.IntNullableFilter<"Income"> | number | null
  projectId?: Prisma.IntNullableFilter<"Income"> | number | null
  peopleId?: Prisma.IntFilter<"Income"> | number
  userId?: Prisma.IntFilter<"Income"> | number
  created?: Prisma.DateTimeFilter<"Income"> | Date | string
  modified?: Prisma.DateTimeFilter<"Income"> | Date | string
}

export type IncomeCreateWithoutCategoryInput = {
  incomeDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  userId: number
  created?: Date | string
  modified?: Date | string
  subCategory?: Prisma.SubCategoryCreateNestedOneWithoutIncomesInput
  project?: Prisma.ProjectCreateNestedOneWithoutIncomesInput
  people: Prisma.PeopleCreateNestedOneWithoutIncomesInput
}

export type IncomeUncheckedCreateWithoutCategoryInput = {
  incomeId?: number
  incomeDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  subCategoryId?: number | null
  projectId?: number | null
  peopleId: number
  userId: number
  created?: Date | string
  modified?: Date | string
}

export type IncomeCreateOrConnectWithoutCategoryInput = {
  where: Prisma.IncomeWhereUniqueInput
  create: Prisma.XOR<Prisma.IncomeCreateWithoutCategoryInput, Prisma.IncomeUncheckedCreateWithoutCategoryInput>
}

export type IncomeCreateManyCategoryInputEnvelope = {
  data: Prisma.IncomeCreateManyCategoryInput | Prisma.IncomeCreateManyCategoryInput[]
  skipDuplicates?: boolean
}

export type IncomeUpsertWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.IncomeWhereUniqueInput
  update: Prisma.XOR<Prisma.IncomeUpdateWithoutCategoryInput, Prisma.IncomeUncheckedUpdateWithoutCategoryInput>
  create: Prisma.XOR<Prisma.IncomeCreateWithoutCategoryInput, Prisma.IncomeUncheckedCreateWithoutCategoryInput>
}

export type IncomeUpdateWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.IncomeWhereUniqueInput
  data: Prisma.XOR<Prisma.IncomeUpdateWithoutCategoryInput, Prisma.IncomeUncheckedUpdateWithoutCategoryInput>
}

export type IncomeUpdateManyWithWhereWithoutCategoryInput = {
  where: Prisma.IncomeScalarWhereInput
  data: Prisma.XOR<Prisma.IncomeUpdateManyMutationInput, Prisma.IncomeUncheckedUpdateManyWithoutCategoryInput>
}

export type IncomeCreateWithoutSubCategoryInput = {
  incomeDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  userId: number
  created?: Date | string
  modified?: Date | string
  category?: Prisma.CategoryCreateNestedOneWithoutIncomesInput
  project?: Prisma.ProjectCreateNestedOneWithoutIncomesInput
  people: Prisma.PeopleCreateNestedOneWithoutIncomesInput
}

export type IncomeUncheckedCreateWithoutSubCategoryInput = {
  incomeId?: number
  incomeDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  categoryId?: number | null
  projectId?: number | null
  peopleId: number
  userId: number
  created?: Date | string
  modified?: Date | string
}

export type IncomeCreateOrConnectWithoutSubCategoryInput = {
  where: Prisma.IncomeWhereUniqueInput
  create: Prisma.XOR<Prisma.IncomeCreateWithoutSubCategoryInput, Prisma.IncomeUncheckedCreateWithoutSubCategoryInput>
}

export type IncomeCreateManySubCategoryInputEnvelope = {
  data: Prisma.IncomeCreateManySubCategoryInput | Prisma.IncomeCreateManySubCategoryInput[]
  skipDuplicates?: boolean
}

export type IncomeUpsertWithWhereUniqueWithoutSubCategoryInput = {
  where: Prisma.IncomeWhereUniqueInput
  update: Prisma.XOR<Prisma.IncomeUpdateWithoutSubCategoryInput, Prisma.IncomeUncheckedUpdateWithoutSubCategoryInput>
  create: Prisma.XOR<Prisma.IncomeCreateWithoutSubCategoryInput, Prisma.IncomeUncheckedCreateWithoutSubCategoryInput>
}

export type IncomeUpdateWithWhereUniqueWithoutSubCategoryInput = {
  where: Prisma.IncomeWhereUniqueInput
  data: Prisma.XOR<Prisma.IncomeUpdateWithoutSubCategoryInput, Prisma.IncomeUncheckedUpdateWithoutSubCategoryInput>
}

export type IncomeUpdateManyWithWhereWithoutSubCategoryInput = {
  where: Prisma.IncomeScalarWhereInput
  data: Prisma.XOR<Prisma.IncomeUpdateManyMutationInput, Prisma.IncomeUncheckedUpdateManyWithoutSubCategoryInput>
}

export type IncomeCreateWithoutProjectInput = {
  incomeDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  userId: number
  created?: Date | string
  modified?: Date | string
  category?: Prisma.CategoryCreateNestedOneWithoutIncomesInput
  subCategory?: Prisma.SubCategoryCreateNestedOneWithoutIncomesInput
  people: Prisma.PeopleCreateNestedOneWithoutIncomesInput
}

export type IncomeUncheckedCreateWithoutProjectInput = {
  incomeId?: number
  incomeDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  categoryId?: number | null
  subCategoryId?: number | null
  peopleId: number
  userId: number
  created?: Date | string
  modified?: Date | string
}

export type IncomeCreateOrConnectWithoutProjectInput = {
  where: Prisma.IncomeWhereUniqueInput
  create: Prisma.XOR<Prisma.IncomeCreateWithoutProjectInput, Prisma.IncomeUncheckedCreateWithoutProjectInput>
}

export type IncomeCreateManyProjectInputEnvelope = {
  data: Prisma.IncomeCreateManyProjectInput | Prisma.IncomeCreateManyProjectInput[]
  skipDuplicates?: boolean
}

export type IncomeUpsertWithWhereUniqueWithoutProjectInput = {
  where: Prisma.IncomeWhereUniqueInput
  update: Prisma.XOR<Prisma.IncomeUpdateWithoutProjectInput, Prisma.IncomeUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.IncomeCreateWithoutProjectInput, Prisma.IncomeUncheckedCreateWithoutProjectInput>
}

export type IncomeUpdateWithWhereUniqueWithoutProjectInput = {
  where: Prisma.IncomeWhereUniqueInput
  data: Prisma.XOR<Prisma.IncomeUpdateWithoutProjectInput, Prisma.IncomeUncheckedUpdateWithoutProjectInput>
}

export type IncomeUpdateManyWithWhereWithoutProjectInput = {
  where: Prisma.IncomeScalarWhereInput
  data: Prisma.XOR<Prisma.IncomeUpdateManyMutationInput, Prisma.IncomeUncheckedUpdateManyWithoutProjectInput>
}

export type IncomeCreateManyPeopleInput = {
  incomeId?: number
  incomeDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  categoryId?: number | null
  subCategoryId?: number | null
  projectId?: number | null
  userId: number
  created?: Date | string
  modified?: Date | string
}

export type IncomeUpdateWithoutPeopleInput = {
  incomeDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  category?: Prisma.CategoryUpdateOneWithoutIncomesNestedInput
  subCategory?: Prisma.SubCategoryUpdateOneWithoutIncomesNestedInput
  project?: Prisma.ProjectUpdateOneWithoutIncomesNestedInput
}

export type IncomeUncheckedUpdateWithoutPeopleInput = {
  incomeId?: Prisma.IntFieldUpdateOperationsInput | number
  incomeDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  categoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  subCategoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  projectId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IncomeUncheckedUpdateManyWithoutPeopleInput = {
  incomeId?: Prisma.IntFieldUpdateOperationsInput | number
  incomeDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  categoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  subCategoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  projectId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IncomeCreateManyCategoryInput = {
  incomeId?: number
  incomeDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  subCategoryId?: number | null
  projectId?: number | null
  peopleId: number
  userId: number
  created?: Date | string
  modified?: Date | string
}

export type IncomeUpdateWithoutCategoryInput = {
  incomeDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  subCategory?: Prisma.SubCategoryUpdateOneWithoutIncomesNestedInput
  project?: Prisma.ProjectUpdateOneWithoutIncomesNestedInput
  people?: Prisma.PeopleUpdateOneRequiredWithoutIncomesNestedInput
}

export type IncomeUncheckedUpdateWithoutCategoryInput = {
  incomeId?: Prisma.IntFieldUpdateOperationsInput | number
  incomeDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  subCategoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  projectId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  peopleId?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IncomeUncheckedUpdateManyWithoutCategoryInput = {
  incomeId?: Prisma.IntFieldUpdateOperationsInput | number
  incomeDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  subCategoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  projectId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  peopleId?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IncomeCreateManySubCategoryInput = {
  incomeId?: number
  incomeDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  categoryId?: number | null
  projectId?: number | null
  peopleId: number
  userId: number
  created?: Date | string
  modified?: Date | string
}

export type IncomeUpdateWithoutSubCategoryInput = {
  incomeDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  category?: Prisma.CategoryUpdateOneWithoutIncomesNestedInput
  project?: Prisma.ProjectUpdateOneWithoutIncomesNestedInput
  people?: Prisma.PeopleUpdateOneRequiredWithoutIncomesNestedInput
}

export type IncomeUncheckedUpdateWithoutSubCategoryInput = {
  incomeId?: Prisma.IntFieldUpdateOperationsInput | number
  incomeDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  categoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  projectId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  peopleId?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IncomeUncheckedUpdateManyWithoutSubCategoryInput = {
  incomeId?: Prisma.IntFieldUpdateOperationsInput | number
  incomeDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  categoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  projectId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  peopleId?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IncomeCreateManyProjectInput = {
  incomeId?: number
  incomeDate: Date | string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: string | null
  attachmentPath?: string | null
  description?: string | null
  isDeleted?: boolean
  categoryId?: number | null
  subCategoryId?: number | null
  peopleId: number
  userId: number
  created?: Date | string
  modified?: Date | string
}

export type IncomeUpdateWithoutProjectInput = {
  incomeDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  category?: Prisma.CategoryUpdateOneWithoutIncomesNestedInput
  subCategory?: Prisma.SubCategoryUpdateOneWithoutIncomesNestedInput
  people?: Prisma.PeopleUpdateOneRequiredWithoutIncomesNestedInput
}

export type IncomeUncheckedUpdateWithoutProjectInput = {
  incomeId?: Prisma.IntFieldUpdateOperationsInput | number
  incomeDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  categoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  subCategoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  peopleId?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IncomeUncheckedUpdateManyWithoutProjectInput = {
  incomeId?: Prisma.IntFieldUpdateOperationsInput | number
  incomeDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  incomeDetail?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  attachmentPath?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  categoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  subCategoryId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  peopleId?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type IncomeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  incomeId?: boolean
  incomeDate?: boolean
  amount?: boolean
  incomeDetail?: boolean
  attachmentPath?: boolean
  description?: boolean
  isDeleted?: boolean
  categoryId?: boolean
  subCategoryId?: boolean
  projectId?: boolean
  peopleId?: boolean
  userId?: boolean
  created?: boolean
  modified?: boolean
  category?: boolean | Prisma.Income$categoryArgs<ExtArgs>
  subCategory?: boolean | Prisma.Income$subCategoryArgs<ExtArgs>
  project?: boolean | Prisma.Income$projectArgs<ExtArgs>
  people?: boolean | Prisma.PeopleDefaultArgs<ExtArgs>
}, ExtArgs["result"]["income"]>

export type IncomeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  incomeId?: boolean
  incomeDate?: boolean
  amount?: boolean
  incomeDetail?: boolean
  attachmentPath?: boolean
  description?: boolean
  isDeleted?: boolean
  categoryId?: boolean
  subCategoryId?: boolean
  projectId?: boolean
  peopleId?: boolean
  userId?: boolean
  created?: boolean
  modified?: boolean
  category?: boolean | Prisma.Income$categoryArgs<ExtArgs>
  subCategory?: boolean | Prisma.Income$subCategoryArgs<ExtArgs>
  project?: boolean | Prisma.Income$projectArgs<ExtArgs>
  people?: boolean | Prisma.PeopleDefaultArgs<ExtArgs>
}, ExtArgs["result"]["income"]>

export type IncomeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  incomeId?: boolean
  incomeDate?: boolean
  amount?: boolean
  incomeDetail?: boolean
  attachmentPath?: boolean
  description?: boolean
  isDeleted?: boolean
  categoryId?: boolean
  subCategoryId?: boolean
  projectId?: boolean
  peopleId?: boolean
  userId?: boolean
  created?: boolean
  modified?: boolean
  category?: boolean | Prisma.Income$categoryArgs<ExtArgs>
  subCategory?: boolean | Prisma.Income$subCategoryArgs<ExtArgs>
  project?: boolean | Prisma.Income$projectArgs<ExtArgs>
  people?: boolean | Prisma.PeopleDefaultArgs<ExtArgs>
}, ExtArgs["result"]["income"]>

export type IncomeSelectScalar = {
  incomeId?: boolean
  incomeDate?: boolean
  amount?: boolean
  incomeDetail?: boolean
  attachmentPath?: boolean
  description?: boolean
  isDeleted?: boolean
  categoryId?: boolean
  subCategoryId?: boolean
  projectId?: boolean
  peopleId?: boolean
  userId?: boolean
  created?: boolean
  modified?: boolean
}

export type IncomeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"incomeId" | "incomeDate" | "amount" | "incomeDetail" | "attachmentPath" | "description" | "isDeleted" | "categoryId" | "subCategoryId" | "projectId" | "peopleId" | "userId" | "created" | "modified", ExtArgs["result"]["income"]>
export type IncomeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.Income$categoryArgs<ExtArgs>
  subCategory?: boolean | Prisma.Income$subCategoryArgs<ExtArgs>
  project?: boolean | Prisma.Income$projectArgs<ExtArgs>
  people?: boolean | Prisma.PeopleDefaultArgs<ExtArgs>
}
export type IncomeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.Income$categoryArgs<ExtArgs>
  subCategory?: boolean | Prisma.Income$subCategoryArgs<ExtArgs>
  project?: boolean | Prisma.Income$projectArgs<ExtArgs>
  people?: boolean | Prisma.PeopleDefaultArgs<ExtArgs>
}
export type IncomeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.Income$categoryArgs<ExtArgs>
  subCategory?: boolean | Prisma.Income$subCategoryArgs<ExtArgs>
  project?: boolean | Prisma.Income$projectArgs<ExtArgs>
  people?: boolean | Prisma.PeopleDefaultArgs<ExtArgs>
}

export type $IncomePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Income"
  objects: {
    category: Prisma.$CategoryPayload<ExtArgs> | null
    subCategory: Prisma.$SubCategoryPayload<ExtArgs> | null
    project: Prisma.$ProjectPayload<ExtArgs> | null
    people: Prisma.$PeoplePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    incomeId: number
    incomeDate: Date
    amount: runtime.Decimal
    incomeDetail: string | null
    attachmentPath: string | null
    description: string | null
    isDeleted: boolean
    categoryId: number | null
    subCategoryId: number | null
    projectId: number | null
    peopleId: number
    userId: number
    created: Date
    modified: Date
  }, ExtArgs["result"]["income"]>
  composites: {}
}

export type IncomeGetPayload<S extends boolean | null | undefined | IncomeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$IncomePayload, S>

export type IncomeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<IncomeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: IncomeCountAggregateInputType | true
  }

export interface IncomeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Income'], meta: { name: 'Income' } }
  /**
   * Find zero or one Income that matches the filter.
   * @param {IncomeFindUniqueArgs} args - Arguments to find a Income
   * @example
   * // Get one Income
   * const income = await prisma.income.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends IncomeFindUniqueArgs>(args: Prisma.SelectSubset<T, IncomeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__IncomeClient<runtime.Types.Result.GetResult<Prisma.$IncomePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Income that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {IncomeFindUniqueOrThrowArgs} args - Arguments to find a Income
   * @example
   * // Get one Income
   * const income = await prisma.income.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends IncomeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, IncomeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__IncomeClient<runtime.Types.Result.GetResult<Prisma.$IncomePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Income that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IncomeFindFirstArgs} args - Arguments to find a Income
   * @example
   * // Get one Income
   * const income = await prisma.income.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends IncomeFindFirstArgs>(args?: Prisma.SelectSubset<T, IncomeFindFirstArgs<ExtArgs>>): Prisma.Prisma__IncomeClient<runtime.Types.Result.GetResult<Prisma.$IncomePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Income that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IncomeFindFirstOrThrowArgs} args - Arguments to find a Income
   * @example
   * // Get one Income
   * const income = await prisma.income.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends IncomeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, IncomeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__IncomeClient<runtime.Types.Result.GetResult<Prisma.$IncomePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Incomes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IncomeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Incomes
   * const incomes = await prisma.income.findMany()
   * 
   * // Get first 10 Incomes
   * const incomes = await prisma.income.findMany({ take: 10 })
   * 
   * // Only select the `incomeId`
   * const incomeWithIncomeIdOnly = await prisma.income.findMany({ select: { incomeId: true } })
   * 
   */
  findMany<T extends IncomeFindManyArgs>(args?: Prisma.SelectSubset<T, IncomeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IncomePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Income.
   * @param {IncomeCreateArgs} args - Arguments to create a Income.
   * @example
   * // Create one Income
   * const Income = await prisma.income.create({
   *   data: {
   *     // ... data to create a Income
   *   }
   * })
   * 
   */
  create<T extends IncomeCreateArgs>(args: Prisma.SelectSubset<T, IncomeCreateArgs<ExtArgs>>): Prisma.Prisma__IncomeClient<runtime.Types.Result.GetResult<Prisma.$IncomePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Incomes.
   * @param {IncomeCreateManyArgs} args - Arguments to create many Incomes.
   * @example
   * // Create many Incomes
   * const income = await prisma.income.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends IncomeCreateManyArgs>(args?: Prisma.SelectSubset<T, IncomeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Incomes and returns the data saved in the database.
   * @param {IncomeCreateManyAndReturnArgs} args - Arguments to create many Incomes.
   * @example
   * // Create many Incomes
   * const income = await prisma.income.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Incomes and only return the `incomeId`
   * const incomeWithIncomeIdOnly = await prisma.income.createManyAndReturn({
   *   select: { incomeId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends IncomeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, IncomeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IncomePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Income.
   * @param {IncomeDeleteArgs} args - Arguments to delete one Income.
   * @example
   * // Delete one Income
   * const Income = await prisma.income.delete({
   *   where: {
   *     // ... filter to delete one Income
   *   }
   * })
   * 
   */
  delete<T extends IncomeDeleteArgs>(args: Prisma.SelectSubset<T, IncomeDeleteArgs<ExtArgs>>): Prisma.Prisma__IncomeClient<runtime.Types.Result.GetResult<Prisma.$IncomePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Income.
   * @param {IncomeUpdateArgs} args - Arguments to update one Income.
   * @example
   * // Update one Income
   * const income = await prisma.income.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends IncomeUpdateArgs>(args: Prisma.SelectSubset<T, IncomeUpdateArgs<ExtArgs>>): Prisma.Prisma__IncomeClient<runtime.Types.Result.GetResult<Prisma.$IncomePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Incomes.
   * @param {IncomeDeleteManyArgs} args - Arguments to filter Incomes to delete.
   * @example
   * // Delete a few Incomes
   * const { count } = await prisma.income.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends IncomeDeleteManyArgs>(args?: Prisma.SelectSubset<T, IncomeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Incomes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IncomeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Incomes
   * const income = await prisma.income.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends IncomeUpdateManyArgs>(args: Prisma.SelectSubset<T, IncomeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Incomes and returns the data updated in the database.
   * @param {IncomeUpdateManyAndReturnArgs} args - Arguments to update many Incomes.
   * @example
   * // Update many Incomes
   * const income = await prisma.income.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Incomes and only return the `incomeId`
   * const incomeWithIncomeIdOnly = await prisma.income.updateManyAndReturn({
   *   select: { incomeId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends IncomeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, IncomeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IncomePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Income.
   * @param {IncomeUpsertArgs} args - Arguments to update or create a Income.
   * @example
   * // Update or create a Income
   * const income = await prisma.income.upsert({
   *   create: {
   *     // ... data to create a Income
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Income we want to update
   *   }
   * })
   */
  upsert<T extends IncomeUpsertArgs>(args: Prisma.SelectSubset<T, IncomeUpsertArgs<ExtArgs>>): Prisma.Prisma__IncomeClient<runtime.Types.Result.GetResult<Prisma.$IncomePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Incomes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IncomeCountArgs} args - Arguments to filter Incomes to count.
   * @example
   * // Count the number of Incomes
   * const count = await prisma.income.count({
   *   where: {
   *     // ... the filter for the Incomes we want to count
   *   }
   * })
  **/
  count<T extends IncomeCountArgs>(
    args?: Prisma.Subset<T, IncomeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], IncomeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Income.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IncomeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends IncomeAggregateArgs>(args: Prisma.Subset<T, IncomeAggregateArgs>): Prisma.PrismaPromise<GetIncomeAggregateType<T>>

  /**
   * Group by Income.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IncomeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends IncomeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: IncomeGroupByArgs['orderBy'] }
      : { orderBy?: IncomeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, IncomeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetIncomeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Income model
 */
readonly fields: IncomeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Income.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__IncomeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  category<T extends Prisma.Income$categoryArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Income$categoryArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  subCategory<T extends Prisma.Income$subCategoryArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Income$subCategoryArgs<ExtArgs>>): Prisma.Prisma__SubCategoryClient<runtime.Types.Result.GetResult<Prisma.$SubCategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  project<T extends Prisma.Income$projectArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Income$projectArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  people<T extends Prisma.PeopleDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PeopleDefaultArgs<ExtArgs>>): Prisma.Prisma__PeopleClient<runtime.Types.Result.GetResult<Prisma.$PeoplePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Income model
 */
export interface IncomeFieldRefs {
  readonly incomeId: Prisma.FieldRef<"Income", 'Int'>
  readonly incomeDate: Prisma.FieldRef<"Income", 'DateTime'>
  readonly amount: Prisma.FieldRef<"Income", 'Decimal'>
  readonly incomeDetail: Prisma.FieldRef<"Income", 'String'>
  readonly attachmentPath: Prisma.FieldRef<"Income", 'String'>
  readonly description: Prisma.FieldRef<"Income", 'String'>
  readonly isDeleted: Prisma.FieldRef<"Income", 'Boolean'>
  readonly categoryId: Prisma.FieldRef<"Income", 'Int'>
  readonly subCategoryId: Prisma.FieldRef<"Income", 'Int'>
  readonly projectId: Prisma.FieldRef<"Income", 'Int'>
  readonly peopleId: Prisma.FieldRef<"Income", 'Int'>
  readonly userId: Prisma.FieldRef<"Income", 'Int'>
  readonly created: Prisma.FieldRef<"Income", 'DateTime'>
  readonly modified: Prisma.FieldRef<"Income", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Income findUnique
 */
export type IncomeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Income
   */
  select?: Prisma.IncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Income
   */
  omit?: Prisma.IncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncomeInclude<ExtArgs> | null
  /**
   * Filter, which Income to fetch.
   */
  where: Prisma.IncomeWhereUniqueInput
}

/**
 * Income findUniqueOrThrow
 */
export type IncomeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Income
   */
  select?: Prisma.IncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Income
   */
  omit?: Prisma.IncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncomeInclude<ExtArgs> | null
  /**
   * Filter, which Income to fetch.
   */
  where: Prisma.IncomeWhereUniqueInput
}

/**
 * Income findFirst
 */
export type IncomeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Income
   */
  select?: Prisma.IncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Income
   */
  omit?: Prisma.IncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncomeInclude<ExtArgs> | null
  /**
   * Filter, which Income to fetch.
   */
  where?: Prisma.IncomeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Incomes to fetch.
   */
  orderBy?: Prisma.IncomeOrderByWithRelationInput | Prisma.IncomeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Incomes.
   */
  cursor?: Prisma.IncomeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Incomes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Incomes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Incomes.
   */
  distinct?: Prisma.IncomeScalarFieldEnum | Prisma.IncomeScalarFieldEnum[]
}

/**
 * Income findFirstOrThrow
 */
export type IncomeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Income
   */
  select?: Prisma.IncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Income
   */
  omit?: Prisma.IncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncomeInclude<ExtArgs> | null
  /**
   * Filter, which Income to fetch.
   */
  where?: Prisma.IncomeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Incomes to fetch.
   */
  orderBy?: Prisma.IncomeOrderByWithRelationInput | Prisma.IncomeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Incomes.
   */
  cursor?: Prisma.IncomeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Incomes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Incomes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Incomes.
   */
  distinct?: Prisma.IncomeScalarFieldEnum | Prisma.IncomeScalarFieldEnum[]
}

/**
 * Income findMany
 */
export type IncomeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Income
   */
  select?: Prisma.IncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Income
   */
  omit?: Prisma.IncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncomeInclude<ExtArgs> | null
  /**
   * Filter, which Incomes to fetch.
   */
  where?: Prisma.IncomeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Incomes to fetch.
   */
  orderBy?: Prisma.IncomeOrderByWithRelationInput | Prisma.IncomeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Incomes.
   */
  cursor?: Prisma.IncomeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Incomes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Incomes.
   */
  skip?: number
  distinct?: Prisma.IncomeScalarFieldEnum | Prisma.IncomeScalarFieldEnum[]
}

/**
 * Income create
 */
export type IncomeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Income
   */
  select?: Prisma.IncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Income
   */
  omit?: Prisma.IncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncomeInclude<ExtArgs> | null
  /**
   * The data needed to create a Income.
   */
  data: Prisma.XOR<Prisma.IncomeCreateInput, Prisma.IncomeUncheckedCreateInput>
}

/**
 * Income createMany
 */
export type IncomeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Incomes.
   */
  data: Prisma.IncomeCreateManyInput | Prisma.IncomeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Income createManyAndReturn
 */
export type IncomeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Income
   */
  select?: Prisma.IncomeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Income
   */
  omit?: Prisma.IncomeOmit<ExtArgs> | null
  /**
   * The data used to create many Incomes.
   */
  data: Prisma.IncomeCreateManyInput | Prisma.IncomeCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncomeIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Income update
 */
export type IncomeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Income
   */
  select?: Prisma.IncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Income
   */
  omit?: Prisma.IncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncomeInclude<ExtArgs> | null
  /**
   * The data needed to update a Income.
   */
  data: Prisma.XOR<Prisma.IncomeUpdateInput, Prisma.IncomeUncheckedUpdateInput>
  /**
   * Choose, which Income to update.
   */
  where: Prisma.IncomeWhereUniqueInput
}

/**
 * Income updateMany
 */
export type IncomeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Incomes.
   */
  data: Prisma.XOR<Prisma.IncomeUpdateManyMutationInput, Prisma.IncomeUncheckedUpdateManyInput>
  /**
   * Filter which Incomes to update
   */
  where?: Prisma.IncomeWhereInput
  /**
   * Limit how many Incomes to update.
   */
  limit?: number
}

/**
 * Income updateManyAndReturn
 */
export type IncomeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Income
   */
  select?: Prisma.IncomeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Income
   */
  omit?: Prisma.IncomeOmit<ExtArgs> | null
  /**
   * The data used to update Incomes.
   */
  data: Prisma.XOR<Prisma.IncomeUpdateManyMutationInput, Prisma.IncomeUncheckedUpdateManyInput>
  /**
   * Filter which Incomes to update
   */
  where?: Prisma.IncomeWhereInput
  /**
   * Limit how many Incomes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncomeIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Income upsert
 */
export type IncomeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Income
   */
  select?: Prisma.IncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Income
   */
  omit?: Prisma.IncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncomeInclude<ExtArgs> | null
  /**
   * The filter to search for the Income to update in case it exists.
   */
  where: Prisma.IncomeWhereUniqueInput
  /**
   * In case the Income found by the `where` argument doesn't exist, create a new Income with this data.
   */
  create: Prisma.XOR<Prisma.IncomeCreateInput, Prisma.IncomeUncheckedCreateInput>
  /**
   * In case the Income was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.IncomeUpdateInput, Prisma.IncomeUncheckedUpdateInput>
}

/**
 * Income delete
 */
export type IncomeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Income
   */
  select?: Prisma.IncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Income
   */
  omit?: Prisma.IncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncomeInclude<ExtArgs> | null
  /**
   * Filter which Income to delete.
   */
  where: Prisma.IncomeWhereUniqueInput
}

/**
 * Income deleteMany
 */
export type IncomeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Incomes to delete
   */
  where?: Prisma.IncomeWhereInput
  /**
   * Limit how many Incomes to delete.
   */
  limit?: number
}

/**
 * Income.category
 */
export type Income$categoryArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
  where?: Prisma.CategoryWhereInput
}

/**
 * Income.subCategory
 */
export type Income$subCategoryArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SubCategory
   */
  select?: Prisma.SubCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SubCategory
   */
  omit?: Prisma.SubCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SubCategoryInclude<ExtArgs> | null
  where?: Prisma.SubCategoryWhereInput
}

/**
 * Income.project
 */
export type Income$projectArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  where?: Prisma.ProjectWhereInput
}

/**
 * Income without action
 */
export type IncomeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Income
   */
  select?: Prisma.IncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Income
   */
  omit?: Prisma.IncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncomeInclude<ExtArgs> | null
}
