
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `People` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model People
 * 
 */
export type PeopleModel = runtime.Types.Result.DefaultSelection<Prisma.$PeoplePayload>

export type AggregatePeople = {
  _count: PeopleCountAggregateOutputType | null
  _avg: PeopleAvgAggregateOutputType | null
  _sum: PeopleSumAggregateOutputType | null
  _min: PeopleMinAggregateOutputType | null
  _max: PeopleMaxAggregateOutputType | null
}

export type PeopleAvgAggregateOutputType = {
  peopleId: number | null
  tokenVersion: number | null
  userId: number | null
}

export type PeopleSumAggregateOutputType = {
  peopleId: number | null
  tokenVersion: number | null
  userId: number | null
}

export type PeopleMinAggregateOutputType = {
  peopleId: number | null
  peopleCode: string | null
  peopleName: string | null
  email: string | null
  password: string | null
  mobileNo: string | null
  description: string | null
  profileImage: string | null
  isActive: boolean | null
  isDeleted: boolean | null
  tokenVersion: number | null
  userId: number | null
  created: Date | null
  modified: Date | null
}

export type PeopleMaxAggregateOutputType = {
  peopleId: number | null
  peopleCode: string | null
  peopleName: string | null
  email: string | null
  password: string | null
  mobileNo: string | null
  description: string | null
  profileImage: string | null
  isActive: boolean | null
  isDeleted: boolean | null
  tokenVersion: number | null
  userId: number | null
  created: Date | null
  modified: Date | null
}

export type PeopleCountAggregateOutputType = {
  peopleId: number
  peopleCode: number
  peopleName: number
  email: number
  password: number
  mobileNo: number
  description: number
  profileImage: number
  isActive: number
  isDeleted: number
  tokenVersion: number
  userId: number
  created: number
  modified: number
  _all: number
}


export type PeopleAvgAggregateInputType = {
  peopleId?: true
  tokenVersion?: true
  userId?: true
}

export type PeopleSumAggregateInputType = {
  peopleId?: true
  tokenVersion?: true
  userId?: true
}

export type PeopleMinAggregateInputType = {
  peopleId?: true
  peopleCode?: true
  peopleName?: true
  email?: true
  password?: true
  mobileNo?: true
  description?: true
  profileImage?: true
  isActive?: true
  isDeleted?: true
  tokenVersion?: true
  userId?: true
  created?: true
  modified?: true
}

export type PeopleMaxAggregateInputType = {
  peopleId?: true
  peopleCode?: true
  peopleName?: true
  email?: true
  password?: true
  mobileNo?: true
  description?: true
  profileImage?: true
  isActive?: true
  isDeleted?: true
  tokenVersion?: true
  userId?: true
  created?: true
  modified?: true
}

export type PeopleCountAggregateInputType = {
  peopleId?: true
  peopleCode?: true
  peopleName?: true
  email?: true
  password?: true
  mobileNo?: true
  description?: true
  profileImage?: true
  isActive?: true
  isDeleted?: true
  tokenVersion?: true
  userId?: true
  created?: true
  modified?: true
  _all?: true
}

export type PeopleAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which People to aggregate.
   */
  where?: Prisma.PeopleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of People to fetch.
   */
  orderBy?: Prisma.PeopleOrderByWithRelationInput | Prisma.PeopleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PeopleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` People from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` People.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned People
  **/
  _count?: true | PeopleCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PeopleAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PeopleSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PeopleMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PeopleMaxAggregateInputType
}

export type GetPeopleAggregateType<T extends PeopleAggregateArgs> = {
      [P in keyof T & keyof AggregatePeople]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePeople[P]>
    : Prisma.GetScalarType<T[P], AggregatePeople[P]>
}




export type PeopleGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PeopleWhereInput
  orderBy?: Prisma.PeopleOrderByWithAggregationInput | Prisma.PeopleOrderByWithAggregationInput[]
  by: Prisma.PeopleScalarFieldEnum[] | Prisma.PeopleScalarFieldEnum
  having?: Prisma.PeopleScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PeopleCountAggregateInputType | true
  _avg?: PeopleAvgAggregateInputType
  _sum?: PeopleSumAggregateInputType
  _min?: PeopleMinAggregateInputType
  _max?: PeopleMaxAggregateInputType
}

export type PeopleGroupByOutputType = {
  peopleId: number
  peopleCode: string | null
  peopleName: string
  email: string | null
  password: string | null
  mobileNo: string | null
  description: string | null
  profileImage: string | null
  isActive: boolean
  isDeleted: boolean
  tokenVersion: number
  userId: number
  created: Date
  modified: Date
  _count: PeopleCountAggregateOutputType | null
  _avg: PeopleAvgAggregateOutputType | null
  _sum: PeopleSumAggregateOutputType | null
  _min: PeopleMinAggregateOutputType | null
  _max: PeopleMaxAggregateOutputType | null
}

type GetPeopleGroupByPayload<T extends PeopleGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PeopleGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PeopleGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PeopleGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PeopleGroupByOutputType[P]>
      }
    >
  >



export type PeopleWhereInput = {
  AND?: Prisma.PeopleWhereInput | Prisma.PeopleWhereInput[]
  OR?: Prisma.PeopleWhereInput[]
  NOT?: Prisma.PeopleWhereInput | Prisma.PeopleWhereInput[]
  peopleId?: Prisma.IntFilter<"People"> | number
  peopleCode?: Prisma.StringNullableFilter<"People"> | string | null
  peopleName?: Prisma.StringFilter<"People"> | string
  email?: Prisma.StringNullableFilter<"People"> | string | null
  password?: Prisma.StringNullableFilter<"People"> | string | null
  mobileNo?: Prisma.StringNullableFilter<"People"> | string | null
  description?: Prisma.StringNullableFilter<"People"> | string | null
  profileImage?: Prisma.StringNullableFilter<"People"> | string | null
  isActive?: Prisma.BoolFilter<"People"> | boolean
  isDeleted?: Prisma.BoolFilter<"People"> | boolean
  tokenVersion?: Prisma.IntFilter<"People"> | number
  userId?: Prisma.IntFilter<"People"> | number
  created?: Prisma.DateTimeFilter<"People"> | Date | string
  modified?: Prisma.DateTimeFilter<"People"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  expenses?: Prisma.ExpenseListRelationFilter
  incomes?: Prisma.IncomeListRelationFilter
  notifications?: Prisma.NotificationListRelationFilter
}

export type PeopleOrderByWithRelationInput = {
  peopleId?: Prisma.SortOrder
  peopleCode?: Prisma.SortOrderInput | Prisma.SortOrder
  peopleName?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  password?: Prisma.SortOrderInput | Prisma.SortOrder
  mobileNo?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  profileImage?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  tokenVersion?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  created?: Prisma.SortOrder
  modified?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  expenses?: Prisma.ExpenseOrderByRelationAggregateInput
  incomes?: Prisma.IncomeOrderByRelationAggregateInput
  notifications?: Prisma.NotificationOrderByRelationAggregateInput
}

export type PeopleWhereUniqueInput = Prisma.AtLeast<{
  peopleId?: number
  AND?: Prisma.PeopleWhereInput | Prisma.PeopleWhereInput[]
  OR?: Prisma.PeopleWhereInput[]
  NOT?: Prisma.PeopleWhereInput | Prisma.PeopleWhereInput[]
  peopleCode?: Prisma.StringNullableFilter<"People"> | string | null
  peopleName?: Prisma.StringFilter<"People"> | string
  email?: Prisma.StringNullableFilter<"People"> | string | null
  password?: Prisma.StringNullableFilter<"People"> | string | null
  mobileNo?: Prisma.StringNullableFilter<"People"> | string | null
  description?: Prisma.StringNullableFilter<"People"> | string | null
  profileImage?: Prisma.StringNullableFilter<"People"> | string | null
  isActive?: Prisma.BoolFilter<"People"> | boolean
  isDeleted?: Prisma.BoolFilter<"People"> | boolean
  tokenVersion?: Prisma.IntFilter<"People"> | number
  userId?: Prisma.IntFilter<"People"> | number
  created?: Prisma.DateTimeFilter<"People"> | Date | string
  modified?: Prisma.DateTimeFilter<"People"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  expenses?: Prisma.ExpenseListRelationFilter
  incomes?: Prisma.IncomeListRelationFilter
  notifications?: Prisma.NotificationListRelationFilter
}, "peopleId">

export type PeopleOrderByWithAggregationInput = {
  peopleId?: Prisma.SortOrder
  peopleCode?: Prisma.SortOrderInput | Prisma.SortOrder
  peopleName?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  password?: Prisma.SortOrderInput | Prisma.SortOrder
  mobileNo?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  profileImage?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  tokenVersion?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  created?: Prisma.SortOrder
  modified?: Prisma.SortOrder
  _count?: Prisma.PeopleCountOrderByAggregateInput
  _avg?: Prisma.PeopleAvgOrderByAggregateInput
  _max?: Prisma.PeopleMaxOrderByAggregateInput
  _min?: Prisma.PeopleMinOrderByAggregateInput
  _sum?: Prisma.PeopleSumOrderByAggregateInput
}

export type PeopleScalarWhereWithAggregatesInput = {
  AND?: Prisma.PeopleScalarWhereWithAggregatesInput | Prisma.PeopleScalarWhereWithAggregatesInput[]
  OR?: Prisma.PeopleScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PeopleScalarWhereWithAggregatesInput | Prisma.PeopleScalarWhereWithAggregatesInput[]
  peopleId?: Prisma.IntWithAggregatesFilter<"People"> | number
  peopleCode?: Prisma.StringNullableWithAggregatesFilter<"People"> | string | null
  peopleName?: Prisma.StringWithAggregatesFilter<"People"> | string
  email?: Prisma.StringNullableWithAggregatesFilter<"People"> | string | null
  password?: Prisma.StringNullableWithAggregatesFilter<"People"> | string | null
  mobileNo?: Prisma.StringNullableWithAggregatesFilter<"People"> | string | null
  description?: Prisma.StringNullableWithAggregatesFilter<"People"> | string | null
  profileImage?: Prisma.StringNullableWithAggregatesFilter<"People"> | string | null
  isActive?: Prisma.BoolWithAggregatesFilter<"People"> | boolean
  isDeleted?: Prisma.BoolWithAggregatesFilter<"People"> | boolean
  tokenVersion?: Prisma.IntWithAggregatesFilter<"People"> | number
  userId?: Prisma.IntWithAggregatesFilter<"People"> | number
  created?: Prisma.DateTimeWithAggregatesFilter<"People"> | Date | string
  modified?: Prisma.DateTimeWithAggregatesFilter<"People"> | Date | string
}

export type PeopleCreateInput = {
  peopleCode?: string | null
  peopleName: string
  email?: string | null
  password?: string | null
  mobileNo?: string | null
  description?: string | null
  profileImage?: string | null
  isActive?: boolean
  isDeleted?: boolean
  tokenVersion?: number
  created?: Date | string
  modified?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPeoplesInput
  expenses?: Prisma.ExpenseCreateNestedManyWithoutPeopleInput
  incomes?: Prisma.IncomeCreateNestedManyWithoutPeopleInput
  notifications?: Prisma.NotificationCreateNestedManyWithoutPeopleInput
}

export type PeopleUncheckedCreateInput = {
  peopleId?: number
  peopleCode?: string | null
  peopleName: string
  email?: string | null
  password?: string | null
  mobileNo?: string | null
  description?: string | null
  profileImage?: string | null
  isActive?: boolean
  isDeleted?: boolean
  tokenVersion?: number
  userId: number
  created?: Date | string
  modified?: Date | string
  expenses?: Prisma.ExpenseUncheckedCreateNestedManyWithoutPeopleInput
  incomes?: Prisma.IncomeUncheckedCreateNestedManyWithoutPeopleInput
  notifications?: Prisma.NotificationUncheckedCreateNestedManyWithoutPeopleInput
}

export type PeopleUpdateInput = {
  peopleCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  peopleName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mobileNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  tokenVersion?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPeoplesNestedInput
  expenses?: Prisma.ExpenseUpdateManyWithoutPeopleNestedInput
  incomes?: Prisma.IncomeUpdateManyWithoutPeopleNestedInput
  notifications?: Prisma.NotificationUpdateManyWithoutPeopleNestedInput
}

export type PeopleUncheckedUpdateInput = {
  peopleId?: Prisma.IntFieldUpdateOperationsInput | number
  peopleCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  peopleName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mobileNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  tokenVersion?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expenses?: Prisma.ExpenseUncheckedUpdateManyWithoutPeopleNestedInput
  incomes?: Prisma.IncomeUncheckedUpdateManyWithoutPeopleNestedInput
  notifications?: Prisma.NotificationUncheckedUpdateManyWithoutPeopleNestedInput
}

export type PeopleCreateManyInput = {
  peopleId?: number
  peopleCode?: string | null
  peopleName: string
  email?: string | null
  password?: string | null
  mobileNo?: string | null
  description?: string | null
  profileImage?: string | null
  isActive?: boolean
  isDeleted?: boolean
  tokenVersion?: number
  userId: number
  created?: Date | string
  modified?: Date | string
}

export type PeopleUpdateManyMutationInput = {
  peopleCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  peopleName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mobileNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  tokenVersion?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PeopleUncheckedUpdateManyInput = {
  peopleId?: Prisma.IntFieldUpdateOperationsInput | number
  peopleCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  peopleName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mobileNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  tokenVersion?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PeopleListRelationFilter = {
  every?: Prisma.PeopleWhereInput
  some?: Prisma.PeopleWhereInput
  none?: Prisma.PeopleWhereInput
}

export type PeopleOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PeopleCountOrderByAggregateInput = {
  peopleId?: Prisma.SortOrder
  peopleCode?: Prisma.SortOrder
  peopleName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  mobileNo?: Prisma.SortOrder
  description?: Prisma.SortOrder
  profileImage?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  tokenVersion?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  created?: Prisma.SortOrder
  modified?: Prisma.SortOrder
}

export type PeopleAvgOrderByAggregateInput = {
  peopleId?: Prisma.SortOrder
  tokenVersion?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type PeopleMaxOrderByAggregateInput = {
  peopleId?: Prisma.SortOrder
  peopleCode?: Prisma.SortOrder
  peopleName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  mobileNo?: Prisma.SortOrder
  description?: Prisma.SortOrder
  profileImage?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  tokenVersion?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  created?: Prisma.SortOrder
  modified?: Prisma.SortOrder
}

export type PeopleMinOrderByAggregateInput = {
  peopleId?: Prisma.SortOrder
  peopleCode?: Prisma.SortOrder
  peopleName?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  mobileNo?: Prisma.SortOrder
  description?: Prisma.SortOrder
  profileImage?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  tokenVersion?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  created?: Prisma.SortOrder
  modified?: Prisma.SortOrder
}

export type PeopleSumOrderByAggregateInput = {
  peopleId?: Prisma.SortOrder
  tokenVersion?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type PeopleScalarRelationFilter = {
  is?: Prisma.PeopleWhereInput
  isNot?: Prisma.PeopleWhereInput
}

export type PeopleNullableScalarRelationFilter = {
  is?: Prisma.PeopleWhereInput | null
  isNot?: Prisma.PeopleWhereInput | null
}

export type PeopleCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PeopleCreateWithoutUserInput, Prisma.PeopleUncheckedCreateWithoutUserInput> | Prisma.PeopleCreateWithoutUserInput[] | Prisma.PeopleUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PeopleCreateOrConnectWithoutUserInput | Prisma.PeopleCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.PeopleCreateManyUserInputEnvelope
  connect?: Prisma.PeopleWhereUniqueInput | Prisma.PeopleWhereUniqueInput[]
}

export type PeopleUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PeopleCreateWithoutUserInput, Prisma.PeopleUncheckedCreateWithoutUserInput> | Prisma.PeopleCreateWithoutUserInput[] | Prisma.PeopleUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PeopleCreateOrConnectWithoutUserInput | Prisma.PeopleCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.PeopleCreateManyUserInputEnvelope
  connect?: Prisma.PeopleWhereUniqueInput | Prisma.PeopleWhereUniqueInput[]
}

export type PeopleUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PeopleCreateWithoutUserInput, Prisma.PeopleUncheckedCreateWithoutUserInput> | Prisma.PeopleCreateWithoutUserInput[] | Prisma.PeopleUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PeopleCreateOrConnectWithoutUserInput | Prisma.PeopleCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.PeopleUpsertWithWhereUniqueWithoutUserInput | Prisma.PeopleUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.PeopleCreateManyUserInputEnvelope
  set?: Prisma.PeopleWhereUniqueInput | Prisma.PeopleWhereUniqueInput[]
  disconnect?: Prisma.PeopleWhereUniqueInput | Prisma.PeopleWhereUniqueInput[]
  delete?: Prisma.PeopleWhereUniqueInput | Prisma.PeopleWhereUniqueInput[]
  connect?: Prisma.PeopleWhereUniqueInput | Prisma.PeopleWhereUniqueInput[]
  update?: Prisma.PeopleUpdateWithWhereUniqueWithoutUserInput | Prisma.PeopleUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.PeopleUpdateManyWithWhereWithoutUserInput | Prisma.PeopleUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.PeopleScalarWhereInput | Prisma.PeopleScalarWhereInput[]
}

export type PeopleUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PeopleCreateWithoutUserInput, Prisma.PeopleUncheckedCreateWithoutUserInput> | Prisma.PeopleCreateWithoutUserInput[] | Prisma.PeopleUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PeopleCreateOrConnectWithoutUserInput | Prisma.PeopleCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.PeopleUpsertWithWhereUniqueWithoutUserInput | Prisma.PeopleUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.PeopleCreateManyUserInputEnvelope
  set?: Prisma.PeopleWhereUniqueInput | Prisma.PeopleWhereUniqueInput[]
  disconnect?: Prisma.PeopleWhereUniqueInput | Prisma.PeopleWhereUniqueInput[]
  delete?: Prisma.PeopleWhereUniqueInput | Prisma.PeopleWhereUniqueInput[]
  connect?: Prisma.PeopleWhereUniqueInput | Prisma.PeopleWhereUniqueInput[]
  update?: Prisma.PeopleUpdateWithWhereUniqueWithoutUserInput | Prisma.PeopleUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.PeopleUpdateManyWithWhereWithoutUserInput | Prisma.PeopleUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.PeopleScalarWhereInput | Prisma.PeopleScalarWhereInput[]
}

export type PeopleCreateNestedOneWithoutExpensesInput = {
  create?: Prisma.XOR<Prisma.PeopleCreateWithoutExpensesInput, Prisma.PeopleUncheckedCreateWithoutExpensesInput>
  connectOrCreate?: Prisma.PeopleCreateOrConnectWithoutExpensesInput
  connect?: Prisma.PeopleWhereUniqueInput
}

export type PeopleUpdateOneRequiredWithoutExpensesNestedInput = {
  create?: Prisma.XOR<Prisma.PeopleCreateWithoutExpensesInput, Prisma.PeopleUncheckedCreateWithoutExpensesInput>
  connectOrCreate?: Prisma.PeopleCreateOrConnectWithoutExpensesInput
  upsert?: Prisma.PeopleUpsertWithoutExpensesInput
  connect?: Prisma.PeopleWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PeopleUpdateToOneWithWhereWithoutExpensesInput, Prisma.PeopleUpdateWithoutExpensesInput>, Prisma.PeopleUncheckedUpdateWithoutExpensesInput>
}

export type PeopleCreateNestedOneWithoutIncomesInput = {
  create?: Prisma.XOR<Prisma.PeopleCreateWithoutIncomesInput, Prisma.PeopleUncheckedCreateWithoutIncomesInput>
  connectOrCreate?: Prisma.PeopleCreateOrConnectWithoutIncomesInput
  connect?: Prisma.PeopleWhereUniqueInput
}

export type PeopleUpdateOneRequiredWithoutIncomesNestedInput = {
  create?: Prisma.XOR<Prisma.PeopleCreateWithoutIncomesInput, Prisma.PeopleUncheckedCreateWithoutIncomesInput>
  connectOrCreate?: Prisma.PeopleCreateOrConnectWithoutIncomesInput
  upsert?: Prisma.PeopleUpsertWithoutIncomesInput
  connect?: Prisma.PeopleWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PeopleUpdateToOneWithWhereWithoutIncomesInput, Prisma.PeopleUpdateWithoutIncomesInput>, Prisma.PeopleUncheckedUpdateWithoutIncomesInput>
}

export type PeopleCreateNestedOneWithoutNotificationsInput = {
  create?: Prisma.XOR<Prisma.PeopleCreateWithoutNotificationsInput, Prisma.PeopleUncheckedCreateWithoutNotificationsInput>
  connectOrCreate?: Prisma.PeopleCreateOrConnectWithoutNotificationsInput
  connect?: Prisma.PeopleWhereUniqueInput
}

export type PeopleUpdateOneWithoutNotificationsNestedInput = {
  create?: Prisma.XOR<Prisma.PeopleCreateWithoutNotificationsInput, Prisma.PeopleUncheckedCreateWithoutNotificationsInput>
  connectOrCreate?: Prisma.PeopleCreateOrConnectWithoutNotificationsInput
  upsert?: Prisma.PeopleUpsertWithoutNotificationsInput
  disconnect?: Prisma.PeopleWhereInput | boolean
  delete?: Prisma.PeopleWhereInput | boolean
  connect?: Prisma.PeopleWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PeopleUpdateToOneWithWhereWithoutNotificationsInput, Prisma.PeopleUpdateWithoutNotificationsInput>, Prisma.PeopleUncheckedUpdateWithoutNotificationsInput>
}

export type PeopleCreateWithoutUserInput = {
  peopleCode?: string | null
  peopleName: string
  email?: string | null
  password?: string | null
  mobileNo?: string | null
  description?: string | null
  profileImage?: string | null
  isActive?: boolean
  isDeleted?: boolean
  tokenVersion?: number
  created?: Date | string
  modified?: Date | string
  expenses?: Prisma.ExpenseCreateNestedManyWithoutPeopleInput
  incomes?: Prisma.IncomeCreateNestedManyWithoutPeopleInput
  notifications?: Prisma.NotificationCreateNestedManyWithoutPeopleInput
}

export type PeopleUncheckedCreateWithoutUserInput = {
  peopleId?: number
  peopleCode?: string | null
  peopleName: string
  email?: string | null
  password?: string | null
  mobileNo?: string | null
  description?: string | null
  profileImage?: string | null
  isActive?: boolean
  isDeleted?: boolean
  tokenVersion?: number
  created?: Date | string
  modified?: Date | string
  expenses?: Prisma.ExpenseUncheckedCreateNestedManyWithoutPeopleInput
  incomes?: Prisma.IncomeUncheckedCreateNestedManyWithoutPeopleInput
  notifications?: Prisma.NotificationUncheckedCreateNestedManyWithoutPeopleInput
}

export type PeopleCreateOrConnectWithoutUserInput = {
  where: Prisma.PeopleWhereUniqueInput
  create: Prisma.XOR<Prisma.PeopleCreateWithoutUserInput, Prisma.PeopleUncheckedCreateWithoutUserInput>
}

export type PeopleCreateManyUserInputEnvelope = {
  data: Prisma.PeopleCreateManyUserInput | Prisma.PeopleCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type PeopleUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.PeopleWhereUniqueInput
  update: Prisma.XOR<Prisma.PeopleUpdateWithoutUserInput, Prisma.PeopleUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.PeopleCreateWithoutUserInput, Prisma.PeopleUncheckedCreateWithoutUserInput>
}

export type PeopleUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.PeopleWhereUniqueInput
  data: Prisma.XOR<Prisma.PeopleUpdateWithoutUserInput, Prisma.PeopleUncheckedUpdateWithoutUserInput>
}

export type PeopleUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.PeopleScalarWhereInput
  data: Prisma.XOR<Prisma.PeopleUpdateManyMutationInput, Prisma.PeopleUncheckedUpdateManyWithoutUserInput>
}

export type PeopleScalarWhereInput = {
  AND?: Prisma.PeopleScalarWhereInput | Prisma.PeopleScalarWhereInput[]
  OR?: Prisma.PeopleScalarWhereInput[]
  NOT?: Prisma.PeopleScalarWhereInput | Prisma.PeopleScalarWhereInput[]
  peopleId?: Prisma.IntFilter<"People"> | number
  peopleCode?: Prisma.StringNullableFilter<"People"> | string | null
  peopleName?: Prisma.StringFilter<"People"> | string
  email?: Prisma.StringNullableFilter<"People"> | string | null
  password?: Prisma.StringNullableFilter<"People"> | string | null
  mobileNo?: Prisma.StringNullableFilter<"People"> | string | null
  description?: Prisma.StringNullableFilter<"People"> | string | null
  profileImage?: Prisma.StringNullableFilter<"People"> | string | null
  isActive?: Prisma.BoolFilter<"People"> | boolean
  isDeleted?: Prisma.BoolFilter<"People"> | boolean
  tokenVersion?: Prisma.IntFilter<"People"> | number
  userId?: Prisma.IntFilter<"People"> | number
  created?: Prisma.DateTimeFilter<"People"> | Date | string
  modified?: Prisma.DateTimeFilter<"People"> | Date | string
}

export type PeopleCreateWithoutExpensesInput = {
  peopleCode?: string | null
  peopleName: string
  email?: string | null
  password?: string | null
  mobileNo?: string | null
  description?: string | null
  profileImage?: string | null
  isActive?: boolean
  isDeleted?: boolean
  tokenVersion?: number
  created?: Date | string
  modified?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPeoplesInput
  incomes?: Prisma.IncomeCreateNestedManyWithoutPeopleInput
  notifications?: Prisma.NotificationCreateNestedManyWithoutPeopleInput
}

export type PeopleUncheckedCreateWithoutExpensesInput = {
  peopleId?: number
  peopleCode?: string | null
  peopleName: string
  email?: string | null
  password?: string | null
  mobileNo?: string | null
  description?: string | null
  profileImage?: string | null
  isActive?: boolean
  isDeleted?: boolean
  tokenVersion?: number
  userId: number
  created?: Date | string
  modified?: Date | string
  incomes?: Prisma.IncomeUncheckedCreateNestedManyWithoutPeopleInput
  notifications?: Prisma.NotificationUncheckedCreateNestedManyWithoutPeopleInput
}

export type PeopleCreateOrConnectWithoutExpensesInput = {
  where: Prisma.PeopleWhereUniqueInput
  create: Prisma.XOR<Prisma.PeopleCreateWithoutExpensesInput, Prisma.PeopleUncheckedCreateWithoutExpensesInput>
}

export type PeopleUpsertWithoutExpensesInput = {
  update: Prisma.XOR<Prisma.PeopleUpdateWithoutExpensesInput, Prisma.PeopleUncheckedUpdateWithoutExpensesInput>
  create: Prisma.XOR<Prisma.PeopleCreateWithoutExpensesInput, Prisma.PeopleUncheckedCreateWithoutExpensesInput>
  where?: Prisma.PeopleWhereInput
}

export type PeopleUpdateToOneWithWhereWithoutExpensesInput = {
  where?: Prisma.PeopleWhereInput
  data: Prisma.XOR<Prisma.PeopleUpdateWithoutExpensesInput, Prisma.PeopleUncheckedUpdateWithoutExpensesInput>
}

export type PeopleUpdateWithoutExpensesInput = {
  peopleCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  peopleName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mobileNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  tokenVersion?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPeoplesNestedInput
  incomes?: Prisma.IncomeUpdateManyWithoutPeopleNestedInput
  notifications?: Prisma.NotificationUpdateManyWithoutPeopleNestedInput
}

export type PeopleUncheckedUpdateWithoutExpensesInput = {
  peopleId?: Prisma.IntFieldUpdateOperationsInput | number
  peopleCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  peopleName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mobileNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  tokenVersion?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  incomes?: Prisma.IncomeUncheckedUpdateManyWithoutPeopleNestedInput
  notifications?: Prisma.NotificationUncheckedUpdateManyWithoutPeopleNestedInput
}

export type PeopleCreateWithoutIncomesInput = {
  peopleCode?: string | null
  peopleName: string
  email?: string | null
  password?: string | null
  mobileNo?: string | null
  description?: string | null
  profileImage?: string | null
  isActive?: boolean
  isDeleted?: boolean
  tokenVersion?: number
  created?: Date | string
  modified?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPeoplesInput
  expenses?: Prisma.ExpenseCreateNestedManyWithoutPeopleInput
  notifications?: Prisma.NotificationCreateNestedManyWithoutPeopleInput
}

export type PeopleUncheckedCreateWithoutIncomesInput = {
  peopleId?: number
  peopleCode?: string | null
  peopleName: string
  email?: string | null
  password?: string | null
  mobileNo?: string | null
  description?: string | null
  profileImage?: string | null
  isActive?: boolean
  isDeleted?: boolean
  tokenVersion?: number
  userId: number
  created?: Date | string
  modified?: Date | string
  expenses?: Prisma.ExpenseUncheckedCreateNestedManyWithoutPeopleInput
  notifications?: Prisma.NotificationUncheckedCreateNestedManyWithoutPeopleInput
}

export type PeopleCreateOrConnectWithoutIncomesInput = {
  where: Prisma.PeopleWhereUniqueInput
  create: Prisma.XOR<Prisma.PeopleCreateWithoutIncomesInput, Prisma.PeopleUncheckedCreateWithoutIncomesInput>
}

export type PeopleUpsertWithoutIncomesInput = {
  update: Prisma.XOR<Prisma.PeopleUpdateWithoutIncomesInput, Prisma.PeopleUncheckedUpdateWithoutIncomesInput>
  create: Prisma.XOR<Prisma.PeopleCreateWithoutIncomesInput, Prisma.PeopleUncheckedCreateWithoutIncomesInput>
  where?: Prisma.PeopleWhereInput
}

export type PeopleUpdateToOneWithWhereWithoutIncomesInput = {
  where?: Prisma.PeopleWhereInput
  data: Prisma.XOR<Prisma.PeopleUpdateWithoutIncomesInput, Prisma.PeopleUncheckedUpdateWithoutIncomesInput>
}

export type PeopleUpdateWithoutIncomesInput = {
  peopleCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  peopleName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mobileNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  tokenVersion?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPeoplesNestedInput
  expenses?: Prisma.ExpenseUpdateManyWithoutPeopleNestedInput
  notifications?: Prisma.NotificationUpdateManyWithoutPeopleNestedInput
}

export type PeopleUncheckedUpdateWithoutIncomesInput = {
  peopleId?: Prisma.IntFieldUpdateOperationsInput | number
  peopleCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  peopleName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mobileNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  tokenVersion?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expenses?: Prisma.ExpenseUncheckedUpdateManyWithoutPeopleNestedInput
  notifications?: Prisma.NotificationUncheckedUpdateManyWithoutPeopleNestedInput
}

export type PeopleCreateWithoutNotificationsInput = {
  peopleCode?: string | null
  peopleName: string
  email?: string | null
  password?: string | null
  mobileNo?: string | null
  description?: string | null
  profileImage?: string | null
  isActive?: boolean
  isDeleted?: boolean
  tokenVersion?: number
  created?: Date | string
  modified?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPeoplesInput
  expenses?: Prisma.ExpenseCreateNestedManyWithoutPeopleInput
  incomes?: Prisma.IncomeCreateNestedManyWithoutPeopleInput
}

export type PeopleUncheckedCreateWithoutNotificationsInput = {
  peopleId?: number
  peopleCode?: string | null
  peopleName: string
  email?: string | null
  password?: string | null
  mobileNo?: string | null
  description?: string | null
  profileImage?: string | null
  isActive?: boolean
  isDeleted?: boolean
  tokenVersion?: number
  userId: number
  created?: Date | string
  modified?: Date | string
  expenses?: Prisma.ExpenseUncheckedCreateNestedManyWithoutPeopleInput
  incomes?: Prisma.IncomeUncheckedCreateNestedManyWithoutPeopleInput
}

export type PeopleCreateOrConnectWithoutNotificationsInput = {
  where: Prisma.PeopleWhereUniqueInput
  create: Prisma.XOR<Prisma.PeopleCreateWithoutNotificationsInput, Prisma.PeopleUncheckedCreateWithoutNotificationsInput>
}

export type PeopleUpsertWithoutNotificationsInput = {
  update: Prisma.XOR<Prisma.PeopleUpdateWithoutNotificationsInput, Prisma.PeopleUncheckedUpdateWithoutNotificationsInput>
  create: Prisma.XOR<Prisma.PeopleCreateWithoutNotificationsInput, Prisma.PeopleUncheckedCreateWithoutNotificationsInput>
  where?: Prisma.PeopleWhereInput
}

export type PeopleUpdateToOneWithWhereWithoutNotificationsInput = {
  where?: Prisma.PeopleWhereInput
  data: Prisma.XOR<Prisma.PeopleUpdateWithoutNotificationsInput, Prisma.PeopleUncheckedUpdateWithoutNotificationsInput>
}

export type PeopleUpdateWithoutNotificationsInput = {
  peopleCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  peopleName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mobileNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  tokenVersion?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPeoplesNestedInput
  expenses?: Prisma.ExpenseUpdateManyWithoutPeopleNestedInput
  incomes?: Prisma.IncomeUpdateManyWithoutPeopleNestedInput
}

export type PeopleUncheckedUpdateWithoutNotificationsInput = {
  peopleId?: Prisma.IntFieldUpdateOperationsInput | number
  peopleCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  peopleName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mobileNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  tokenVersion?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expenses?: Prisma.ExpenseUncheckedUpdateManyWithoutPeopleNestedInput
  incomes?: Prisma.IncomeUncheckedUpdateManyWithoutPeopleNestedInput
}

export type PeopleCreateManyUserInput = {
  peopleId?: number
  peopleCode?: string | null
  peopleName: string
  email?: string | null
  password?: string | null
  mobileNo?: string | null
  description?: string | null
  profileImage?: string | null
  isActive?: boolean
  isDeleted?: boolean
  tokenVersion?: number
  created?: Date | string
  modified?: Date | string
}

export type PeopleUpdateWithoutUserInput = {
  peopleCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  peopleName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mobileNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  tokenVersion?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expenses?: Prisma.ExpenseUpdateManyWithoutPeopleNestedInput
  incomes?: Prisma.IncomeUpdateManyWithoutPeopleNestedInput
  notifications?: Prisma.NotificationUpdateManyWithoutPeopleNestedInput
}

export type PeopleUncheckedUpdateWithoutUserInput = {
  peopleId?: Prisma.IntFieldUpdateOperationsInput | number
  peopleCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  peopleName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mobileNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  tokenVersion?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expenses?: Prisma.ExpenseUncheckedUpdateManyWithoutPeopleNestedInput
  incomes?: Prisma.IncomeUncheckedUpdateManyWithoutPeopleNestedInput
  notifications?: Prisma.NotificationUncheckedUpdateManyWithoutPeopleNestedInput
}

export type PeopleUncheckedUpdateManyWithoutUserInput = {
  peopleId?: Prisma.IntFieldUpdateOperationsInput | number
  peopleCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  peopleName?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mobileNo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profileImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  tokenVersion?: Prisma.IntFieldUpdateOperationsInput | number
  created?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modified?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type PeopleCountOutputType
 */

export type PeopleCountOutputType = {
  expenses: number
  incomes: number
  notifications: number
}

export type PeopleCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  expenses?: boolean | PeopleCountOutputTypeCountExpensesArgs
  incomes?: boolean | PeopleCountOutputTypeCountIncomesArgs
  notifications?: boolean | PeopleCountOutputTypeCountNotificationsArgs
}

/**
 * PeopleCountOutputType without action
 */
export type PeopleCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PeopleCountOutputType
   */
  select?: Prisma.PeopleCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PeopleCountOutputType without action
 */
export type PeopleCountOutputTypeCountExpensesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ExpenseWhereInput
}

/**
 * PeopleCountOutputType without action
 */
export type PeopleCountOutputTypeCountIncomesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.IncomeWhereInput
}

/**
 * PeopleCountOutputType without action
 */
export type PeopleCountOutputTypeCountNotificationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NotificationWhereInput
}


export type PeopleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  peopleId?: boolean
  peopleCode?: boolean
  peopleName?: boolean
  email?: boolean
  password?: boolean
  mobileNo?: boolean
  description?: boolean
  profileImage?: boolean
  isActive?: boolean
  isDeleted?: boolean
  tokenVersion?: boolean
  userId?: boolean
  created?: boolean
  modified?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  expenses?: boolean | Prisma.People$expensesArgs<ExtArgs>
  incomes?: boolean | Prisma.People$incomesArgs<ExtArgs>
  notifications?: boolean | Prisma.People$notificationsArgs<ExtArgs>
  _count?: boolean | Prisma.PeopleCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["people"]>

export type PeopleSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  peopleId?: boolean
  peopleCode?: boolean
  peopleName?: boolean
  email?: boolean
  password?: boolean
  mobileNo?: boolean
  description?: boolean
  profileImage?: boolean
  isActive?: boolean
  isDeleted?: boolean
  tokenVersion?: boolean
  userId?: boolean
  created?: boolean
  modified?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["people"]>

export type PeopleSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  peopleId?: boolean
  peopleCode?: boolean
  peopleName?: boolean
  email?: boolean
  password?: boolean
  mobileNo?: boolean
  description?: boolean
  profileImage?: boolean
  isActive?: boolean
  isDeleted?: boolean
  tokenVersion?: boolean
  userId?: boolean
  created?: boolean
  modified?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["people"]>

export type PeopleSelectScalar = {
  peopleId?: boolean
  peopleCode?: boolean
  peopleName?: boolean
  email?: boolean
  password?: boolean
  mobileNo?: boolean
  description?: boolean
  profileImage?: boolean
  isActive?: boolean
  isDeleted?: boolean
  tokenVersion?: boolean
  userId?: boolean
  created?: boolean
  modified?: boolean
}

export type PeopleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"peopleId" | "peopleCode" | "peopleName" | "email" | "password" | "mobileNo" | "description" | "profileImage" | "isActive" | "isDeleted" | "tokenVersion" | "userId" | "created" | "modified", ExtArgs["result"]["people"]>
export type PeopleInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  expenses?: boolean | Prisma.People$expensesArgs<ExtArgs>
  incomes?: boolean | Prisma.People$incomesArgs<ExtArgs>
  notifications?: boolean | Prisma.People$notificationsArgs<ExtArgs>
  _count?: boolean | Prisma.PeopleCountOutputTypeDefaultArgs<ExtArgs>
}
export type PeopleIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type PeopleIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $PeoplePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "People"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    expenses: Prisma.$ExpensePayload<ExtArgs>[]
    incomes: Prisma.$IncomePayload<ExtArgs>[]
    notifications: Prisma.$NotificationPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    peopleId: number
    peopleCode: string | null
    peopleName: string
    email: string | null
    password: string | null
    mobileNo: string | null
    description: string | null
    profileImage: string | null
    isActive: boolean
    isDeleted: boolean
    tokenVersion: number
    userId: number
    created: Date
    modified: Date
  }, ExtArgs["result"]["people"]>
  composites: {}
}

export type PeopleGetPayload<S extends boolean | null | undefined | PeopleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PeoplePayload, S>

export type PeopleCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PeopleFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PeopleCountAggregateInputType | true
  }

export interface PeopleDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['People'], meta: { name: 'People' } }
  /**
   * Find zero or one People that matches the filter.
   * @param {PeopleFindUniqueArgs} args - Arguments to find a People
   * @example
   * // Get one People
   * const people = await prisma.people.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PeopleFindUniqueArgs>(args: Prisma.SelectSubset<T, PeopleFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PeopleClient<runtime.Types.Result.GetResult<Prisma.$PeoplePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one People that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PeopleFindUniqueOrThrowArgs} args - Arguments to find a People
   * @example
   * // Get one People
   * const people = await prisma.people.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PeopleFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PeopleFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PeopleClient<runtime.Types.Result.GetResult<Prisma.$PeoplePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first People that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PeopleFindFirstArgs} args - Arguments to find a People
   * @example
   * // Get one People
   * const people = await prisma.people.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PeopleFindFirstArgs>(args?: Prisma.SelectSubset<T, PeopleFindFirstArgs<ExtArgs>>): Prisma.Prisma__PeopleClient<runtime.Types.Result.GetResult<Prisma.$PeoplePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first People that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PeopleFindFirstOrThrowArgs} args - Arguments to find a People
   * @example
   * // Get one People
   * const people = await prisma.people.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PeopleFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PeopleFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PeopleClient<runtime.Types.Result.GetResult<Prisma.$PeoplePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more People that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PeopleFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all People
   * const people = await prisma.people.findMany()
   * 
   * // Get first 10 People
   * const people = await prisma.people.findMany({ take: 10 })
   * 
   * // Only select the `peopleId`
   * const peopleWithPeopleIdOnly = await prisma.people.findMany({ select: { peopleId: true } })
   * 
   */
  findMany<T extends PeopleFindManyArgs>(args?: Prisma.SelectSubset<T, PeopleFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PeoplePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a People.
   * @param {PeopleCreateArgs} args - Arguments to create a People.
   * @example
   * // Create one People
   * const People = await prisma.people.create({
   *   data: {
   *     // ... data to create a People
   *   }
   * })
   * 
   */
  create<T extends PeopleCreateArgs>(args: Prisma.SelectSubset<T, PeopleCreateArgs<ExtArgs>>): Prisma.Prisma__PeopleClient<runtime.Types.Result.GetResult<Prisma.$PeoplePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many People.
   * @param {PeopleCreateManyArgs} args - Arguments to create many People.
   * @example
   * // Create many People
   * const people = await prisma.people.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PeopleCreateManyArgs>(args?: Prisma.SelectSubset<T, PeopleCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many People and returns the data saved in the database.
   * @param {PeopleCreateManyAndReturnArgs} args - Arguments to create many People.
   * @example
   * // Create many People
   * const people = await prisma.people.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many People and only return the `peopleId`
   * const peopleWithPeopleIdOnly = await prisma.people.createManyAndReturn({
   *   select: { peopleId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PeopleCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PeopleCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PeoplePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a People.
   * @param {PeopleDeleteArgs} args - Arguments to delete one People.
   * @example
   * // Delete one People
   * const People = await prisma.people.delete({
   *   where: {
   *     // ... filter to delete one People
   *   }
   * })
   * 
   */
  delete<T extends PeopleDeleteArgs>(args: Prisma.SelectSubset<T, PeopleDeleteArgs<ExtArgs>>): Prisma.Prisma__PeopleClient<runtime.Types.Result.GetResult<Prisma.$PeoplePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one People.
   * @param {PeopleUpdateArgs} args - Arguments to update one People.
   * @example
   * // Update one People
   * const people = await prisma.people.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PeopleUpdateArgs>(args: Prisma.SelectSubset<T, PeopleUpdateArgs<ExtArgs>>): Prisma.Prisma__PeopleClient<runtime.Types.Result.GetResult<Prisma.$PeoplePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more People.
   * @param {PeopleDeleteManyArgs} args - Arguments to filter People to delete.
   * @example
   * // Delete a few People
   * const { count } = await prisma.people.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PeopleDeleteManyArgs>(args?: Prisma.SelectSubset<T, PeopleDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more People.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PeopleUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many People
   * const people = await prisma.people.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PeopleUpdateManyArgs>(args: Prisma.SelectSubset<T, PeopleUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more People and returns the data updated in the database.
   * @param {PeopleUpdateManyAndReturnArgs} args - Arguments to update many People.
   * @example
   * // Update many People
   * const people = await prisma.people.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more People and only return the `peopleId`
   * const peopleWithPeopleIdOnly = await prisma.people.updateManyAndReturn({
   *   select: { peopleId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PeopleUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PeopleUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PeoplePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one People.
   * @param {PeopleUpsertArgs} args - Arguments to update or create a People.
   * @example
   * // Update or create a People
   * const people = await prisma.people.upsert({
   *   create: {
   *     // ... data to create a People
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the People we want to update
   *   }
   * })
   */
  upsert<T extends PeopleUpsertArgs>(args: Prisma.SelectSubset<T, PeopleUpsertArgs<ExtArgs>>): Prisma.Prisma__PeopleClient<runtime.Types.Result.GetResult<Prisma.$PeoplePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of People.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PeopleCountArgs} args - Arguments to filter People to count.
   * @example
   * // Count the number of People
   * const count = await prisma.people.count({
   *   where: {
   *     // ... the filter for the People we want to count
   *   }
   * })
  **/
  count<T extends PeopleCountArgs>(
    args?: Prisma.Subset<T, PeopleCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PeopleCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a People.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PeopleAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PeopleAggregateArgs>(args: Prisma.Subset<T, PeopleAggregateArgs>): Prisma.PrismaPromise<GetPeopleAggregateType<T>>

  /**
   * Group by People.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PeopleGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PeopleGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PeopleGroupByArgs['orderBy'] }
      : { orderBy?: PeopleGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PeopleGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPeopleGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the People model
 */
readonly fields: PeopleFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for People.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PeopleClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  expenses<T extends Prisma.People$expensesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.People$expensesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExpensePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  incomes<T extends Prisma.People$incomesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.People$incomesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IncomePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  notifications<T extends Prisma.People$notificationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.People$notificationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NotificationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the People model
 */
export interface PeopleFieldRefs {
  readonly peopleId: Prisma.FieldRef<"People", 'Int'>
  readonly peopleCode: Prisma.FieldRef<"People", 'String'>
  readonly peopleName: Prisma.FieldRef<"People", 'String'>
  readonly email: Prisma.FieldRef<"People", 'String'>
  readonly password: Prisma.FieldRef<"People", 'String'>
  readonly mobileNo: Prisma.FieldRef<"People", 'String'>
  readonly description: Prisma.FieldRef<"People", 'String'>
  readonly profileImage: Prisma.FieldRef<"People", 'String'>
  readonly isActive: Prisma.FieldRef<"People", 'Boolean'>
  readonly isDeleted: Prisma.FieldRef<"People", 'Boolean'>
  readonly tokenVersion: Prisma.FieldRef<"People", 'Int'>
  readonly userId: Prisma.FieldRef<"People", 'Int'>
  readonly created: Prisma.FieldRef<"People", 'DateTime'>
  readonly modified: Prisma.FieldRef<"People", 'DateTime'>
}
    

// Custom InputTypes
/**
 * People findUnique
 */
export type PeopleFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the People
   */
  select?: Prisma.PeopleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the People
   */
  omit?: Prisma.PeopleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PeopleInclude<ExtArgs> | null
  /**
   * Filter, which People to fetch.
   */
  where: Prisma.PeopleWhereUniqueInput
}

/**
 * People findUniqueOrThrow
 */
export type PeopleFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the People
   */
  select?: Prisma.PeopleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the People
   */
  omit?: Prisma.PeopleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PeopleInclude<ExtArgs> | null
  /**
   * Filter, which People to fetch.
   */
  where: Prisma.PeopleWhereUniqueInput
}

/**
 * People findFirst
 */
export type PeopleFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the People
   */
  select?: Prisma.PeopleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the People
   */
  omit?: Prisma.PeopleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PeopleInclude<ExtArgs> | null
  /**
   * Filter, which People to fetch.
   */
  where?: Prisma.PeopleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of People to fetch.
   */
  orderBy?: Prisma.PeopleOrderByWithRelationInput | Prisma.PeopleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for People.
   */
  cursor?: Prisma.PeopleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` People from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` People.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of People.
   */
  distinct?: Prisma.PeopleScalarFieldEnum | Prisma.PeopleScalarFieldEnum[]
}

/**
 * People findFirstOrThrow
 */
export type PeopleFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the People
   */
  select?: Prisma.PeopleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the People
   */
  omit?: Prisma.PeopleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PeopleInclude<ExtArgs> | null
  /**
   * Filter, which People to fetch.
   */
  where?: Prisma.PeopleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of People to fetch.
   */
  orderBy?: Prisma.PeopleOrderByWithRelationInput | Prisma.PeopleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for People.
   */
  cursor?: Prisma.PeopleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` People from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` People.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of People.
   */
  distinct?: Prisma.PeopleScalarFieldEnum | Prisma.PeopleScalarFieldEnum[]
}

/**
 * People findMany
 */
export type PeopleFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the People
   */
  select?: Prisma.PeopleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the People
   */
  omit?: Prisma.PeopleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PeopleInclude<ExtArgs> | null
  /**
   * Filter, which People to fetch.
   */
  where?: Prisma.PeopleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of People to fetch.
   */
  orderBy?: Prisma.PeopleOrderByWithRelationInput | Prisma.PeopleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing People.
   */
  cursor?: Prisma.PeopleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` People from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` People.
   */
  skip?: number
  distinct?: Prisma.PeopleScalarFieldEnum | Prisma.PeopleScalarFieldEnum[]
}

/**
 * People create
 */
export type PeopleCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the People
   */
  select?: Prisma.PeopleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the People
   */
  omit?: Prisma.PeopleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PeopleInclude<ExtArgs> | null
  /**
   * The data needed to create a People.
   */
  data: Prisma.XOR<Prisma.PeopleCreateInput, Prisma.PeopleUncheckedCreateInput>
}

/**
 * People createMany
 */
export type PeopleCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many People.
   */
  data: Prisma.PeopleCreateManyInput | Prisma.PeopleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * People createManyAndReturn
 */
export type PeopleCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the People
   */
  select?: Prisma.PeopleSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the People
   */
  omit?: Prisma.PeopleOmit<ExtArgs> | null
  /**
   * The data used to create many People.
   */
  data: Prisma.PeopleCreateManyInput | Prisma.PeopleCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PeopleIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * People update
 */
export type PeopleUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the People
   */
  select?: Prisma.PeopleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the People
   */
  omit?: Prisma.PeopleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PeopleInclude<ExtArgs> | null
  /**
   * The data needed to update a People.
   */
  data: Prisma.XOR<Prisma.PeopleUpdateInput, Prisma.PeopleUncheckedUpdateInput>
  /**
   * Choose, which People to update.
   */
  where: Prisma.PeopleWhereUniqueInput
}

/**
 * People updateMany
 */
export type PeopleUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update People.
   */
  data: Prisma.XOR<Prisma.PeopleUpdateManyMutationInput, Prisma.PeopleUncheckedUpdateManyInput>
  /**
   * Filter which People to update
   */
  where?: Prisma.PeopleWhereInput
  /**
   * Limit how many People to update.
   */
  limit?: number
}

/**
 * People updateManyAndReturn
 */
export type PeopleUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the People
   */
  select?: Prisma.PeopleSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the People
   */
  omit?: Prisma.PeopleOmit<ExtArgs> | null
  /**
   * The data used to update People.
   */
  data: Prisma.XOR<Prisma.PeopleUpdateManyMutationInput, Prisma.PeopleUncheckedUpdateManyInput>
  /**
   * Filter which People to update
   */
  where?: Prisma.PeopleWhereInput
  /**
   * Limit how many People to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PeopleIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * People upsert
 */
export type PeopleUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the People
   */
  select?: Prisma.PeopleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the People
   */
  omit?: Prisma.PeopleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PeopleInclude<ExtArgs> | null
  /**
   * The filter to search for the People to update in case it exists.
   */
  where: Prisma.PeopleWhereUniqueInput
  /**
   * In case the People found by the `where` argument doesn't exist, create a new People with this data.
   */
  create: Prisma.XOR<Prisma.PeopleCreateInput, Prisma.PeopleUncheckedCreateInput>
  /**
   * In case the People was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PeopleUpdateInput, Prisma.PeopleUncheckedUpdateInput>
}

/**
 * People delete
 */
export type PeopleDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the People
   */
  select?: Prisma.PeopleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the People
   */
  omit?: Prisma.PeopleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PeopleInclude<ExtArgs> | null
  /**
   * Filter which People to delete.
   */
  where: Prisma.PeopleWhereUniqueInput
}

/**
 * People deleteMany
 */
export type PeopleDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which People to delete
   */
  where?: Prisma.PeopleWhereInput
  /**
   * Limit how many People to delete.
   */
  limit?: number
}

/**
 * People.expenses
 */
export type People$expensesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Expense
   */
  select?: Prisma.ExpenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Expense
   */
  omit?: Prisma.ExpenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpenseInclude<ExtArgs> | null
  where?: Prisma.ExpenseWhereInput
  orderBy?: Prisma.ExpenseOrderByWithRelationInput | Prisma.ExpenseOrderByWithRelationInput[]
  cursor?: Prisma.ExpenseWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ExpenseScalarFieldEnum | Prisma.ExpenseScalarFieldEnum[]
}

/**
 * People.incomes
 */
export type People$incomesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Income
   */
  select?: Prisma.IncomeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Income
   */
  omit?: Prisma.IncomeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncomeInclude<ExtArgs> | null
  where?: Prisma.IncomeWhereInput
  orderBy?: Prisma.IncomeOrderByWithRelationInput | Prisma.IncomeOrderByWithRelationInput[]
  cursor?: Prisma.IncomeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.IncomeScalarFieldEnum | Prisma.IncomeScalarFieldEnum[]
}

/**
 * People.notifications
 */
export type People$notificationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Notification
   */
  select?: Prisma.NotificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Notification
   */
  omit?: Prisma.NotificationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotificationInclude<ExtArgs> | null
  where?: Prisma.NotificationWhereInput
  orderBy?: Prisma.NotificationOrderByWithRelationInput | Prisma.NotificationOrderByWithRelationInput[]
  cursor?: Prisma.NotificationWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.NotificationScalarFieldEnum | Prisma.NotificationScalarFieldEnum[]
}

/**
 * People without action
 */
export type PeopleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the People
   */
  select?: Prisma.PeopleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the People
   */
  omit?: Prisma.PeopleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PeopleInclude<ExtArgs> | null
}
